export type ForumSection={slug:string;title:string;icon:string;description:string;categories:string[]};
// Önceki geniş forum mimarisi veri kaybı olmadan burada tutulur. Bu liste public
// rotalarda kullanılmaz; yalnızca yönetim arşivi için kaynak olarak kalır.
export const archivedForumSections:ForumSection[]=[
{slug:'sky-bozum-duyurular',title:'Sky Bozum ve Duyurular',icon:'✦',description:'Topluluk kuralları, platform yenilikleri ve resmî bilgilendirmeler.',categories:['Forum kuralları','Sky Bozum duyuruları','Yeni özellikler','Kampanyalar ve fırsatlar','Öneri ve geri bildirim']},
{slug:'yeni-baslayanlar',title:'Yeni Başlayanlar',icon:'◎',description:'Forumu, dijital hizmetleri ve temel internet araçlarını yeni kullananlar için başlangıç alanı.',categories:['Foruma başlangıç','Temel internet bilgileri','İlk web sitesi','İlk online satış','Sık sorulan sorular']},
{slug:'mobil-odeme',title:'Mobil Ödeme',icon:'▣',description:'Operatör limitleri, faturaya yansıtma, hata ve güvenlik konuları.',categories:['Vodafone mobil ödeme','Turkcell mobil ödeme','Türk Telekom mobil ödeme','Limit ve fatura işlemleri','Hata ve çözüm yolları','Güvenli kullanım']},
{slug:'dijital-kodlar',title:'Dijital Kodlar ve Gift Card',icon:'◇',description:'Oyun kodları, hediye kartları, bölge uyumu ve güvenli teslim süreçleri.',categories:['Apple Gift Card','Google Play kodları','Steam cüzdan kodları','Razer Gold','Oyun ve E-PIN kodları','Kod güvenliği']},
{slug:'sikayet-ve-cozum',title:'Şikâyet ve Çözüm',icon:'!',description:'Sorunların belgeli biçimde paylaşılması ve çözüm durumunun takip edilmesi.',categories:['Bozum işlemi şikâyetleri','Operatör sorunları','Dijital kod sorunları','Online alışveriş şikâyetleri','Çözülen şikâyetler','Yanıt bekleyenler']},
{slug:'dijital-guvenlik',title:'Dijital Güvenlik',icon:'⌾',description:'Hesap güvenliği, dolandırıcılık belirtileri, kimlik avı ve veri koruma.',categories:['Hesap güvenliği','Dolandırıcılık uyarıları','Kimlik avı ve sahte bağlantılar','Şifre ve iki aşamalı doğrulama','Kişisel veri güvenliği','Güvenlik haberleri']},
{slug:'webmaster-genel',title:'Webmaster Genel',icon:'⌘',description:'Site sahiplerinin genel soruları, deneyimleri ve proje değerlendirmeleri.',categories:['Webmaster gündemi','Site değerlendirme','Proje fikirleri','Araç ve kaynak önerileri','Sorun ve çözümler','Webmaster dayanışması']},
{slug:'web-gelistirme',title:'Web Geliştirme',icon:'</>',description:'Ön yüz, arka uç, performans, erişilebilirlik ve web standartları.',categories:['HTML ve CSS','JavaScript ve TypeScript','React ve Next.js','Sunucu tarafı geliştirme','Web performansı','Erişilebilirlik']},
{slug:'cms-ve-wordpress',title:'CMS ve WordPress',icon:'W',description:'İçerik yönetim sistemlerinin kurulumu, bakımı, tema ve eklentileri.',categories:['WordPress başlangıç','Tema geliştirme','Eklenti seçimi','Güvenlik ve yedekleme','Hızlandırma','Diğer içerik sistemleri']},
{slug:'seo-ve-arama',title:'SEO ve Arama Motorları',icon:'↗',description:'Teknik SEO, içerik kalitesi, ölçüm ve arama görünürlüğü.',categories:['SEO başlangıç','Teknik SEO','İçerik ve arama niyeti','Search Console','Yerel SEO','SEO sorunları ve analiz']},
{slug:'yapay-zeka',title:'Yapay Zekâ Araçları',icon:'✧',description:'Yapay zekâ araçlarının üretken, güvenli ve şeffaf kullanım biçimleri.',categories:['Yapay zekâ başlangıç','Metin ve araştırma araçları','Görsel üretim','Kodlama yardımcıları','Otomasyon fikirleri','Doğruluk ve etik']},
{slug:'grafik-ve-tasarim',title:'Grafik ve Tasarım',icon:'◈',description:'Görsel tasarım, kullanıcı deneyimi, marka dili ve üretim araçları.',categories:['Grafik tasarım temelleri','UI ve UX tasarımı','Logo ve kurumsal kimlik','Adobe araçları','Canva ve pratik araçlar','Tasarım geri bildirimi']},
{slug:'sosyal-medya',title:'Sosyal Medya',icon:'#',description:'Platform güvenliği, içerik planlama, ölçüm ve topluluk yönetimi.',categories:['Instagram','YouTube','TikTok','Facebook','X ve Threads','Sosyal medya güvenliği']},
{slug:'e-ticaret',title:'E-Ticaret',icon:'₺',description:'Mağaza kurulumu, ürün, ödeme, teslimat ve tüketici deneyimi.',categories:['E-ticarete başlangıç','Mağaza altyapıları','Ürün ve stok yönetimi','Ödeme yöntemleri','Kargo ve teslimat','İade ve tüketici hakları']},
{slug:'pazaryerleri',title:'Pazaryerleri',icon:'▤',description:'Pazaryeri mağazalarının operasyonu, komisyonları ve müşteri süreçleri.',categories:['Trendyol','Hepsiburada','Amazon Türkiye','N11','Etsy ve global pazarlar','Pazaryeri operasyonu']},
{slug:'dijital-pazarlama',title:'Dijital Pazarlama',icon:'◉',description:'Reklam ölçümü, hedef kitle, dönüşüm ve sürdürülebilir büyüme.',categories:['Google Ads','Meta reklamları','İçerik pazarlaması','E-posta pazarlaması','Dönüşüm ölçümü','Bütçe ve performans']},
{slug:'icerik-uretimi',title:'İçerik Üretimi',icon:'¶',description:'Makaleler, video, görsel ve yayın planlarında kalite odaklı üretim.',categories:['Makale hazırlama','Editörlük ve doğrulama','Video içerik','İçerik takvimi','Kaynak kullanımı','Telif ve lisans']},
{slug:'domain-ve-hosting',title:'Domain ve Hosting',icon:'◎',description:'Alan adı, barındırma, DNS, SSL ve sunucu seçimi hakkında teknik bilgi.',categories:['Alan adı seçimi','Domain transferi','Hosting seçimi','DNS ve SSL','Sunucu yönetimi','Kesinti ve teknik sorunlar']},
{slug:'yazilim-ve-programlama',title:'Yazılım ve Programlama',icon:'{ }',description:'Programlama dilleri, uygulama geliştirme ve yazılım pratiği.',categories:['Programlamaya başlangıç','Python','PHP','Mobil uygulamalar','Veritabanları','Git ve proje yönetimi']},
{slug:'teknoloji-gundemi',title:'Teknoloji Gündemi',icon:'⚡',description:'Yeni ürünler, platform değişiklikleri ve doğrulanmış teknoloji gelişmeleri.',categories:['Teknoloji haberleri','Mobil cihazlar','Uygulamalar ve servisler','İşletim sistemleri','İnternet teknolojileri','Yeni ürün değerlendirmeleri']},
{slug:'donanim-ve-teknik-destek',title:'Donanım ve Teknik Destek',icon:'⚙',description:'Bilgisayar, telefon, ağ ve çevre birimi sorunları için yardımlaşma.',categories:['Bilgisayar donanımı','Telefon ve tablet','Ağ ve modem','Çevre birimleri','Arıza ve teknik destek','Hangisini almalıyım']},
{slug:'girisimcilik',title:'Girişimcilik ve İş Fikirleri',icon:'▲',description:'Fikir doğrulama, küçük işletme, maliyet ve büyüme deneyimleri.',categories:['İş fikri değerlendirme','Girişime başlangıç','Maliyet ve bütçe','Müşteri bulma','Markalaşma','Başarısızlık ve dersler']},
{slug:'freelance-ve-hizmetler',title:'Freelance ve Hizmetler',icon:'◆',description:'Freelance çalışma, hizmet kapsamı, teklif ve güvenli iş ilişkileri.',categories:['Freelance başlangıç','Teklif hazırlama','Müşteri iletişimi','Sözleşme ve teslim','Portföy geliştirme','Hizmet deneyimleri']},
{slug:'sohbet',title:'Sohbet ve Topluluk',icon:'☵',description:'Üyelerin kendini tanıttığı, gündemi ve günlük ilgi alanlarını konuştuğu bölüm.',categories:['Tanışma alanı','Güncel konular','Oyun ve eğlence','Film, dizi ve müzik','Öneriler','Serbest sohbet']},
{slug:'forum-destek',title:'Forum Destek',icon:'?',description:'Üyelik, içerik bildirimi, teknik sorun ve forum kullanım desteği.',categories:['Üyelik ve hesap sorunları','Forum kullanım rehberi','İçerik şikâyeti','Teknik sorun bildirimi','Öneri ve geri bildirim']}
];

export const forumSections:ForumSection[]=[
{slug:'mobil-odeme-operatorler',title:'Mobil Ödeme & Operatörler',icon:'▣',description:'Mobil ödeme sistemleri, operatörler, limitler ve işlem süreçleri hakkında bilgi ve destek.',categories:['Mobil Ödeme Genel','Turkcell','Vodafone','Türk Telekom','Mobil Ödeme Limit & Sorunları']},
{slug:'dijital-kod-hediye-kartlari',title:'Dijital Kod & Hediye Kartları',icon:'◇',description:'Razer Gold, Apple, Steam ve diğer dijital kodlar hakkında kullanım ve bozum bilgileri.',categories:['Razer Gold TL','Razer Gold USD','Apple / iTunes','Steam','Kod Sorunları']},
{slug:'dijital-cuzdanlar',title:'Dijital Cüzdanlar',icon:'◉',description:'Paycell, Pokus, Vodafone Pay ve dijital cüzdan işlemleri hakkında rehber ve destek.',categories:['Paycell','Pokus','Vodafone Pay','Dijital Cüzdan Limitleri','Dijital Cüzdan Sorunları']},
{slug:'bozum-oranlar',title:'Bozum & Oranlar',icon:'₺',description:'Bozum oranları, hesaplama, komisyonlar ve ödeme süreci hakkında bilgiler.',categories:['Güncel Oranlar','Oran Hesaplama','Komisyonlar','Ödeme Süresi','Yüksek Oran Uyarıları']},
{slug:'guvenlik-dolandiricilik',title:'Güvenlik & Dolandırıcılık',icon:'⌁',description:'Güvenli işlem, kişisel bilgi paylaşımı, sahte siteler ve dolandırıcılıktan korunma rehberleri.',categories:['Güvenli İşlem','Paylaşılmaması Gereken Bilgiler','Sahte Siteler','WhatsApp Güvenliği','Şüpheli İşlem Bildirimleri']},
{slug:'sky-bozum-destek-topluluk',title:'Sky Bozum Destek & Topluluk',icon:'✦',description:'Sky Bozum kullanımı, duyurular, öneriler ve topluluk konuşmaları.',categories:['Duyurular','Nasıl İşlem Yapılır?','Sık Sorulanlar','Öneri & Geri Bildirim','Genel Sohbet']},
];

export const slugifyForumCategory=(value:string)=>value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

export type ForumStarterTopic={slug:string;sectionSlug:string;category:string;categorySlug:string;title:string;summary:string;body:string[];author:'Sky Bozum Yönetim';publishedAt:string};
const starter=(sectionSlug:string,category:string,slug:string,title:string,summary:string,body:string[]):ForumStarterTopic=>({sectionSlug,category,categorySlug:slugifyForumCategory(category),slug,title,summary,body,author:'Sky Bozum Yönetim',publishedAt:'2026-08-13'});

// Başlangıç içerikleri build-time yönetim yayınlarıdır; ziyaretçi veya müşteri kimliği taklit edilmez.
export const forumStarterTopics:ForumStarterTopic[]=[
starter('mobil-odeme-operatorler','Mobil Ödeme Genel','mobil-odeme-bozum-islemi-nasil-ilerler','Mobil ödeme bozum işlemi nasıl ilerler?','İşlem öncesi kontrol, yazılı teyit ve tamamlanma adımları.',[
'Mobil ödeme ile yapılacak bir işlemde önce hangi hizmetin kullanılacağı, tutar ve güncel koşullar netleştirilmelidir. Operatör hattının açık olması tek başına işlem yapılabileceği anlamına gelmez; limit, fatura durumu ve kullanılan uygulamanın kendi kuralları sonucu etkileyebilir. Ekrandaki oran veya süre bilgisini karar vermeden önce güncel haliyle kontrol etmek daha sağlıklıdır.',
'İşlem boyunca yalnızca gerekli bilgileri paylaşın ve yapılan yönlendirmeyi yazılı olarak saklayın. Hesap şifresi, SMS doğrulama kodu veya kart güvenlik bilgisi isteniyorsa işlemi durdurun. Beklenmeyen bir hata oluştuğunda operatörünüzün ya da ilgili uygulamanın resmî destek kanalıyla durumu teyit etmek, sonradan yaşanabilecek karışıklıkları azaltır.'
]),
starter('mobil-odeme-operatorler','Turkcell','turkcell-mobil-odeme-kullanirken-nelere-dikkat-edilmeli','Turkcell mobil ödeme kullanırken nelere dikkat edilmeli?','Turkcell hattı üzerinden işlemden önce bakılması gereken temel noktalar.',[
'Turkcell mobil ödeme kullanılırken hat sahibi bilgisi, hattın kullanım durumu ve o dönemde tanımlı limitler önem taşır. Limitler paket, fatura geçmişi, hat yaşı veya kurumun risk değerlendirmesi gibi nedenlerle değişebilir. Bu nedenle geçmişte çalışan bir işlemin her zaman aynı biçimde çalışacağını varsaymamak gerekir.',
'Ödeme ekranında görünen tutarı ve işlem açıklamasını dikkatle okuyun. Tanımadığınız bir uygulama, içerik servisi veya bağlantı üzerinden işlem başlatmayın. Şüpheli bir ücretlendirme fark ederseniz ekran görüntüsünü saklayın; öncelikle Turkcell’in resmî kanallarından ilgili hizmeti doğrulayın. Şifre ve SMS kodu, destek görevlisi olduğunu söyleyen biriyle dahi paylaşılmamalıdır.'
]),
starter('mobil-odeme-operatorler','Vodafone','vodafone-mobil-odeme-limiti-ve-bozum-sureci','Vodafone mobil ödeme limiti ve bozum süreci','Vodafone mobil ödeme limiti ile işlem koşullarını ayırt etmeye yardımcı kısa rehber.',[
'Vodafone mobil ödeme limiti, hattınızın kullanıma açık olduğu her anda sabit bir tutar olarak düşünülmemelidir. Operatörün güncel politikaları, faturaya yansıtılan işlemler ve hattın geçmişi limiti etkileyebilir. Bir işlem planlamadan önce kendi hesabınızdaki güncel limiti ve varsa bekleyen tahsilatları kontrol etmek gerekir.',
'Bozum veya dijital hizmet sürecinde işlem türü, toplam tutar ve teslim yöntemi yazılı biçimde anlaşılmalıdır. Resmî olmayan kanallardan gelen “limit artırma” ya da “hemen onay” teklifleri risk işaretidir. Vodafone adına iletişim kurduğunu söyleyen bir hesabın doğruluğunu yalnızca resmî uygulama, web sitesi veya doğrulanmış müşteri hizmetleri üzerinden kontrol edin.'
]),
starter('mobil-odeme-operatorler','Türk Telekom','turk-telekom-mobil-odeme-hakkinda-temel-bilgiler','Türk Telekom mobil ödeme hakkında temel bilgiler','Türk Telekom mobil ödeme kullanımı için kavramları ve güvenlik sınırlarını açıklayan not.',[
'Türk Telekom mobil ödeme, uygun hizmetlerde bedelin telefon faturası veya hat bakiyesi üzerinden tahsil edilmesine imkân veren bir ödeme yöntemidir. Hangi hizmetlerin uygun olduğu, limitlerin nasıl belirlendiği ve tahsilatın ne zaman yansıyacağı dönemsel olarak değişebilir. Bu nedenle işlem öncesinde Türk Telekom hesabınız ve hizmetin kendi ödeme ekranı birlikte incelenmelidir.',
'İşleme geçmeden önce uygulama veya web adresinin resmî olup olmadığını kontrol edin. İptal, iade veya hata halinde saklanacak kayıtlar; işlem numarası, tarih, tutar ve ekran görüntüsüdür. Destek için size yazan kişi şifre ya da doğrulama kodu isterse bu normal bir kontrol değildir. Resmî destek kanalından yeni bir kayıt açmak daha güvenli yoldur.'
]),
starter('mobil-odeme-operatorler','Mobil Ödeme Limit & Sorunları','mobil-odeme-islemi-neden-reddedilebilir','Mobil ödeme işlemi neden reddedilebilir?','Reddedilen mobil ödeme işlemlerinde rastgele tekrar denemeden önce yapılacak kontroller.',[
'Mobil ödeme işlemleri limit yetersizliği, hat veya fatura durumu, hizmet sağlayıcının kuralları ya da anlık teknik kontroller nedeniyle reddedilebilir. Ret ekranı tek başına hesabınızda kalıcı bir sorun olduğu anlamına gelmez. Aynı işlemi peş peşe denemek yerine hata mesajını, zamanı ve kullanılan hizmeti not etmek daha yararlıdır.',
'Önce operatör hesabınızda açık bir kısıtlama, ödenmemiş borç veya limit durumu olup olmadığını kontrol edin. Ardından ilgili uygulamanın resmî destek kaydına bakın. Herhangi bir kişi “reddi kaldırmak” için SMS kodu, şifre veya uzaktan erişim isterse işlem yapmayın. Sorunu çözmek için resmî kanallar dışında hesap bilgisi vermek güvenlik riskini büyütebilir.'
]),
starter('dijital-kod-hediye-kartlari','Razer Gold TL','razer-gold-tl-bozum-islemi-nasil-yapilir','Razer Gold TL bozum işlemi nasıl yapılır?','Razer Gold TL kodlarında değer, geçerlilik ve işlem öncesi kontrol noktaları.',[
'Razer Gold TL kodu ile işlem düşünülüyorsa kodun para birimi, yüz değeri ve henüz kullanılmamış olması temel şartlardır. Kod görselini veya PIN bilgisini paylaşmadan önce işlem koşullarını yazılı olarak netleştirmek gerekir. Aynı isimli fakat farklı para birimli ürünler birbirinin yerine geçmeyebilir; ürün sayfasındaki bölge ve değer bilgisini dikkatle kontrol edin.',
'Kod teslim edildiğinde geri alınması her zaman mümkün olmayabilir. Bu nedenle yalnızca gerekli kanal üzerinden ilerleyin ve kodu üçüncü kişilerle paylaşmayın. “Önce kodu gönder, sonra bakalım” gibi belirsiz yönlendirmelerden kaçının. Kodla ilgili geçersizlik bildirimi varsa satın alma kaydı, seri bilgisi ve varsa hata ekranı saklanmalı; ilk kontrol kodu veren resmî satıcı veya platformla yapılmalıdır.'
]),
starter('dijital-kod-hediye-kartlari','Razer Gold USD','razer-gold-usd-ile-tl-kodlari-arasindaki-farklar','Razer Gold USD ile TL kodları arasındaki farklar','Para birimi ve bölge uyumu nedeniyle oluşabilecek sorunları önceden görmeye yardımcı açıklama.',[
'Razer Gold USD ve TL kodları yalnızca üzerlerinde yazan tutar bakımından değil, kullanılabildikleri hesap veya bölge koşulları bakımından da farklı olabilir. Bir kodun USD olması, TL hesabında aynı değerle kullanılacağı ya da dönüştürülebileceği anlamına gelmez. Satın alma öncesi ürün açıklamasındaki para birimi, bölge ve kullanım şartları mutlaka okunmalıdır.',
'Kod kullanılmadan önce hesap ayarlarını ve ürünün geçerli olduğu platformu kontrol edin. Kur farkı, bölge kısıtı veya satıcı politikasından kaynaklanan ihtilaflarda tek başına kod ekranı yeterli olmayabilir; sipariş belgesi ve ürün açıklaması da önem taşır. Kodun tam metnini sosyal medya veya mesaj gruplarında paylaşmak, kullanılma riskini doğurur.'
]),
starter('dijital-kod-hediye-kartlari','Apple / iTunes','apple-hediye-karti-bozum-oncesi-kontrol-listesi','Apple hediye kartı bozum öncesi kontrol listesi','Apple hediye kartlarında bakiye, bölge ve teslim güvenliği için kısa liste.',[
'Apple hediye kartı ile ilgili herhangi bir işlemden önce kartın hangi ülke veya bölge için düzenlendiğini kontrol edin. Apple hesabının mağaza ülkesi ile kartın bölgesi uyumsuzsa kod kullanılmayabilir. Kartın fiziksel ya da dijital oluşu, satın alma kaydı ve üzerinde görünen değer de uyuşmazlık halinde gerekli olabilir.',
'Apple hiçbir koşulda hediye kartı kodunun telefonla, e-postayla veya mesajla paylaşılmasını istemez. Özellikle “borç”, “ceza” ya da “hesabı kurtarma” bahanesiyle kod istenmesi dolandırıcılık işaretidir. Kodda sorun yaşarsanız kartı satan yetkili kanalın belgesini ve hata ekranını saklayın; Apple hesabınızın şifresini veya iki aşamalı doğrulama kodunu paylaşmayın.'
]),
starter('dijital-kod-hediye-kartlari','Steam','steam-kodlarinda-bolge-ve-para-birimi-neden-onemlidir','Steam kodlarında bölge ve para birimi neden önemlidir?','Steam cüzdan kodu seçerken hesabın ülkesini ve ürünün kullanım koşullarını birlikte değerlendirin.',[
'Steam cüzdan kodlarında bölge ve para birimi hesabın mağaza ayarlarıyla ilişkilidir. Bir ülkede satılan veya belirli para birimiyle düzenlenmiş kod, başka bir bölgedeki hesapta kabul edilmeyebilir. Kod satın alınmadan önce ürün başlığındaki bölge bilgisi ile Steam hesabının mağaza ülkesini karşılaştırmak gerekir.',
'Kodun üzerindeki değeri farklı bir para birimine çevireceğini varsayarak işlem yapmayın. Kullanılmamış kodların dahi uyumsuzluk nedeniyle kabul edilmemesi mümkündür. Sorun yaşanırsa kodu tekrar tekrar denemek yerine hata mesajını kaydedin ve satın aldığınız kanalın iade/yardım koşullarına bakın. Kodun PIN bilgisini destek talebi açarken dahi herkese açık bir yere yazmayın.'
]),
starter('dijital-kod-hediye-kartlari','Kod Sorunları','gecersiz-veya-daha-once-kullanilmis-kod-durumunda-ne-yapilmali','Geçersiz veya daha önce kullanılmış kod durumunda ne yapılmalı?','Dijital kod hatasında delilleri koruyup doğru sırayla destek almak için temel adımlar.',[
'Bir kod “geçersiz” veya “daha önce kullanılmış” görünüyorsa önce kodu nereden ve ne zaman aldığınızı, sipariş numarasını ve hata ekranını kaydedin. Kodu birçok farklı cihazda denemek veya herkese göndermek, olayı açıklığa kavuşturmaz; tersine güvenlik ve iade sürecini zorlaştırabilir. Kodun para birimi ve bölgesi de kontrol edilmelidir.',
'İlk başvuru kodu satan yetkili kanal üzerinden, mümkünse yazılı olarak yapılmalıdır. Sipariş belgesi, ürün açıklaması ve hata ekranı çoğu zaman yeterli başlangıç kaydı sağlar. Sosyal medya aracılığıyla yardım teklif eden bilinmeyen hesaplara kodu veya hesap giriş bilgilerini göndermeyin. Hesap şifresi ve SMS doğrulama kodu bu tür bir sorunu çözmek için gerekli değildir.'
]),
starter('dijital-cuzdanlar','Paycell','paycell-bozum-sureci-ve-bilinmesi-gerekenler','Paycell bozum süreci ve bilinmesi gerekenler','Paycell bakiyesiyle ilgili işlem öncesi hesap, limit ve kayıt kontrolü.',[
'Paycell ile ilgili bir işlem planlarken bakiyenin kaynağını, güncel kullanım koşullarını ve hesabın doğrulama durumunu dikkate alın. Dijital cüzdanlarda görünen bakiye, her işlem için serbestçe kullanılabilir olmayabilir. Limit, güvenlik incelemesi veya hizmetin kuralları işlemin gerçekleşmesini etkileyebilir.',
'İşlem türü ve tahmini tutar yazılı şekilde anlaşılmadan bakiye veya kod paylaşmayın. Paycell hesabına erişim için şifre, tek kullanımlık SMS kodu ya da cihaz onayı isteyen kişilere bilgi vermeyin. Bekleyen veya reddedilen bir işlemde önce uygulama içindeki kayıtları inceleyin; ardından Paycell’in resmî destek kanalıyla işlem numarası üzerinden iletişim kurun.'
]),
starter('dijital-cuzdanlar','Pokus','pokus-bakiyesi-nasil-degerlendirilir','Pokus bakiyesi nasıl değerlendirilir?','Pokus bakiyesini kullanmadan önce uygulama içi koşulları ve güvenlik adımlarını inceleyin.',[
'Pokus bakiyesi, hesabınızdaki görünür tutardan ibaret değildir; kullanım alanları, para transferi veya harcama kuralları güncel ürün şartlarına bağlıdır. Uygulama içindeki limitleri ve sözleşme özetini kontrol etmek, yanlış beklenti oluşmasını önler. Özellikle üçüncü tarafların sunduğu hızlı işlem vaatleri, cüzdanın resmî kurallarından bağımsız olabilir.',
'Hesap güvenliği için giriş bilgilerinizi paylaşmayın ve uygulama dışından gelen bağlantılarla oturum açmayın. Bir işlem beklemede kalırsa tutar, tarih ve işlem açıklamasını not edin. Aynı talimatı tekrar tekrar vermeden önce uygulama bildirimlerini ve resmî destek kanallarını kontrol edin. Bu yaklaşım hem hata takibini hem de varsa itiraz sürecini kolaylaştırır.'
]),
starter('dijital-cuzdanlar','Vodafone Pay','vodafone-pay-ile-mobil-odeme-arasindaki-fark-nedir','Vodafone Pay ile mobil ödeme arasındaki fark nedir?','Dijital cüzdan bakiyesi ile telefon faturası üzerinden ödeme arasındaki temel ayrım.',[
'Vodafone Pay ve mobil ödeme benzer görünse de ödeme kaynağı ve işlem akışı bakımından farklıdır. Vodafone Pay, dijital cüzdan mantığıyla uygulama içi bakiye ve hizmetleri kapsarken; mobil ödeme, uygun harcamaların telefon faturası veya hat bakiyesi üzerinden tahsil edilmesine dayanır. Hangi yöntemin kullanılabildiği işlem yapılan hizmete ve hesabın durumuna göre değişir.',
'Karar vermeden önce ödeme ekranında hangi yöntemin seçildiğini, ücretin nereye yansıyacağını ve varsa limiti kontrol edin. Cüzdan hesabı ile hat hesabı için destek süreçleri de farklı olabilir. Tanımadığınız bir kişi bu yöntemlerden biri için parola, SMS kodu veya uzaktan erişim isterse işlem yapmayın; yalnızca resmî uygulama içinden yardım kaydı oluşturun.'
]),
starter('dijital-cuzdanlar','Dijital Cüzdan Limitleri','dijital-cuzdanlarda-gunluk-ve-aylik-limit-mantigi','Dijital cüzdanlarda günlük ve aylık limit mantığı','Limitlerin neden kişiden kişiye veya dönemden döneme değişebildiğini açıklayan kısa not.',[
'Dijital cüzdanlardaki günlük ve aylık limitler yalnızca bakiye büyüklüğüne göre belirlenmez. Hesap doğrulama seviyesi, işlem türü, mevzuat kaynaklı kontroller ve hizmet sağlayıcının risk politikası limitleri etkileyebilir. Bu nedenle başka bir kullanıcının gördüğü limitin sizin hesabınız için de geçerli olacağını varsaymak doğru değildir.',
'Limit kontrolü için uygulama içindeki resmî ekranları ve güncel sözleşme bilgisini esas alın. “Limit açma” veya “sınırsız hesap” adı altında yapılan üçüncü taraf teklifleri güvenilir bir kaynak sayılmaz. Limit nedeniyle işlem gerçekleşmiyorsa bunu aşmak için şifre, SMS kodu veya kimlik görseli paylaşmayın; doğrulama ve hesap desteği yalnızca hizmetin kendi resmî akışından yürütülmelidir.'
]),
starter('dijital-cuzdanlar','Dijital Cüzdan Sorunları','dijital-cuzdan-islemi-beklemede-kaldiginda-ne-kontrol-edilmeli','Dijital cüzdan işlemi beklemede kaldığında ne kontrol edilmeli?','Bekleyen dijital cüzdan işlemlerinde güvenli ve düzenli kontrol adımları.',[
'Dijital cüzdan işlemi beklemede kaldığında önce işlem geçmişindeki kayıt, saat ve tutar incelenmelidir. Bekleme; sistem yoğunluğu, güvenlik kontrolü, karşı tarafın onayı veya bağlantı hatası gibi farklı nedenlerden oluşabilir. Uygulama açıkken aynı işlemi yeniden başlatmak, çift kayıt veya kafa karışıklığı riskini artırabilir.',
'İşlem numarasını, ekran görüntüsünü ve varsa bildirim metnini saklayın. Daha sonra uygulamanın resmî yardım merkezinden bekleyen işlem için yönlendirme olup olmadığını kontrol edin. Destek adıyla ulaşan bir kişi hesabınıza giriş kodu isterse paylaşmayın. Gerçek destek süreci, sizden parolanızı veya tek kullanımlık doğrulama kodunuzu talep etmez.'
]),
starter('bozum-oranlar','Güncel Oranlar','bozum-oranlari-neden-degisebilir','Bozum oranları neden değişebilir?','Oran değişikliklerinin tek bir sebebe bağlanmaması gerektiğini açıklayan başlangıç notu.',[
'Bozum oranları hizmet türü, tutar, ürünün kullanılabilirliği, doğrulama gereksinimi ve piyasa koşulları gibi etkenlere göre değişebilir. Aynı gün içinde bile farklı ürünler için farklı oran görülmesi tek başına olağan dışı değildir. Geçmişte verilen bir teklifin sonraki işlem için otomatik olarak geçerli olduğunu düşünmemek gerekir.',
'Oranı değerlendirirken net elinize geçecek tutarı, varsa kesinti bilgisini ve işlem koşullarını aynı anda sorun. Yalnızca yüksek görünen yüzdeye odaklanmak, sonradan ek şartlarla karşılaşmanıza yol açabilir. Belirsiz veya aşırı yüksek bir teklif aldığınızda yazılı teyit isteyin; işlemden önce kod, şifre veya doğrulama bilgisi paylaşmayın.'
]),
starter('bozum-oranlar','Oran Hesaplama','1000-tl-bakiyeden-elime-ne-kadar-gecer','1.000 TL bakiyeden elime ne kadar geçer?','Oran hesaplanırken brüt tutar, net tutar ve olası kesintileri ayırma rehberi.',[
'Bir bakiyenin size ne kadar ödeme olarak döneceğini hesaplarken başlangıç tutarı ile net ödeme tutarını ayırmak gerekir. Yüzde oranı tek başına yeterli değildir; işlem türü, olası komisyonlar ve özel koşullar net sonucu değiştirebilir. Bu nedenle 1.000 TL için hesap yaparken “oran kaç?” yerine “net ödeme ne olur?” sorusunu sormak daha anlaşılırdır.',
'Hesaplama aracındaki sonuç tahmini bir karşılaştırma olarak görülmelidir. Kesin işlem öncesinde tutar, şartlar ve varsa kesintiler yazılı biçimde teyit edilmelidir. Aynı değer iki kez görünüyorsa bu, sabit oranla oluşan tek net tahmini ifade eder; aralık sunan ürünlerde ise alt ve üst değer ayrı ayrı değerlendirilmelidir.'
]),
starter('bozum-oranlar','Komisyonlar','bozum-orani-ile-komisyon-arasindaki-fark-nedir','Bozum oranı ile komisyon arasındaki fark nedir?','Yüzde oranı ve işlem kesintisini aynı kavram sanmamak için açıklama.',[
'Bozum oranı genellikle toplam değerin ne kadarının ödeme olarak hesaplandığını ifade eder. Komisyon ise işlem sırasında ayrıca uygulanan hizmet, transfer veya benzeri kesintiyi anlatabilir. Bazı hizmetlerde ikisi birlikte açıkça yazılırken, bazılarında net tutar doğrudan verilir. Bu nedenle farklı teklifleri karşılaştırırken hangi rakamın neyi anlattığını görmek önemlidir.',
'İşlem öncesinde net ödemenin, varsa transfer masrafının ve olası ek şartların yazılı olarak belirtilmesini isteyin. “Komisyonsuz” ifadesi net ödeme yüksek olacak demek değildir; oran da ayrıca değerlendirilmelidir. Karşı taraf yalnızca sözlü bilgi veriyor veya tutarı netleştirmeden kod istiyorsa ilerlemeyin. Kayıtlı bir açıklama olası anlaşmazlıkta daha sağlıklı bir başlangıç sağlar.'
]),
starter('bozum-oranlar','Ödeme Süresi','bozum-sonrasi-odeme-ne-kadar-surede-gelir','Bozum sonrası ödeme ne kadar sürede gelir?','Ödeme süresini garanti gibi görmeden etkileyen faktörleri kontrol etmeye yardımcı rehber.',[
'Bozum sonrası ödeme süresi işlem türüne, inceleme ihtiyacına, bankacılık saatlerine ve kullanılan ödeme kanalına göre değişebilir. “Anında” veya belirli bir dakika ifadesi, her kullanıcı ve her işlem için koşulsuz bir taahhüt olarak değerlendirilmemelidir. Özellikle yüksek tutar, yeni hesap veya ek doğrulama gerektiren işlemlerde süre uzayabilir.',
'İşlem başlamadan önce tahmini süreyi, hangi aşamada bilgilendirme yapılacağını ve gecikme durumunda hangi kanaldan destek alınacağını öğrenin. Ödeme beklenenden uzun sürerse işlem numarasıyla yazılı destek kaydı açın. Süreç hızlansın diye hesabınızın şifresini, SMS kodunu veya banka giriş bilgisini paylaşmak güvenli değildir.'
]),
starter('bozum-oranlar','Yüksek Oran Uyarıları','gercekci-olmayan-yuksek-oran-tekliflerine-neden-dikkat-edilmeli','Gerçekçi olmayan yüksek oran tekliflerine neden dikkat edilmeli?','Gerçekçi olmayan vaatleri risk işareti olarak değerlendirmek için kısa kontrol listesi.',[
'Piyasa koşullarından belirgin biçimde ayrılan yüksek oran teklifleri, özellikle hızlı karar vermeniz isteniyorsa dikkatle incelenmelidir. Teklifin neden diğerlerinden farklı olduğu açıkça anlatılmıyor, net ödeme yazılı teyit edilmiyor veya yalnızca mesaj uygulaması üzerinden ilerleniyorsa risk artar. Yüksek görünen yüzde, güvenli işlem anlamına gelmez.',
'Karar vermeden önce hizmetin resmî iletişim bilgisini, işlem koşullarını ve varsa şikâyet/itiraz yolunu kontrol edin. Kodun veya hesabın kontrolünü geri dönüşü olmayan biçimde vermeyin. Parola, SMS doğrulama kodu, banka kartı bilgisi veya uzaktan erişim talebi normal değildir. Şüphede kalındığında işlemi ertelemek, geri dönülmesi zor bir kayıptan daha güvenlidir.'
]),
starter('guvenlik-dolandiricilik','Güvenli İşlem','bozum-isleminde-hangi-bilgiler-paylasilabilir','Bozum işleminde hangi bilgiler paylaşılabilir?','Gerekli işlem bilgisini hesap güvenliğinden ayırmaya yardımcı temel prensipler.',[
'Bozum işleminde paylaşılabilecek bilgiler işlem türü, yaklaşık tutar ve hizmete göre değişebilir; ancak hesap erişimi sağlayan bilgiler bu kapsamda değildir. Bir işlem için ihtiyaç duyulan bilgiyi, hesabın kontrolünü tamamen devretmekten ayırmak gerekir. Ödeme veya teslimat koşulları net değilse kişisel veri paylaşımını asgari düzeyde tutun.',
'Parola, tek kullanımlık SMS kodu, uygulama onayı, kart güvenlik kodu ve internet bankacılığı giriş bilgileri paylaşılmamalıdır. Kimlik belgesi istenen istisnai bir işlemde dahi bunun neden gerekli olduğunu resmî kanal üzerinden doğrulayın. Yazılı süreç kaydı, işlem numarası ve açık iletişim bilgisi; güvenli ilerlemenin şifre paylaşmaktan çok daha doğru yollarıdır.'
]),
starter('guvenlik-dolandiricilik','Paylaşılmaması Gereken Bilgiler','sms-kodu-ve-hesap-sifresi-neden-paylasilmamali','SMS kodu ve hesap şifresi neden paylaşılmamalı?','Tek kullanımlık kodların ve parolaların neden destek sürecinin parçası olamayacağını açıklama.',[
'SMS ile gelen tek kullanımlık kodlar ve hesap şifreleri, hesabınıza giriş veya işlem onayı vermek için kullanılır. Bu bilgileri paylaşan kişi, fark etmeden başka birinin hesabı üzerinde işlem yapmasına imkân tanıyabilir. Destek görevlisi, arkadaş veya işlem aracısı olduğunu söyleyen biri dahi bu kodları istememelidir.',
'Bir kodu yanlışlıkla paylaştıysanız hemen ilgili hesabın parolasını değiştirin, aktif oturumları kontrol edin ve resmî destek kanalından güvenlik kaydı oluşturun. Size ulaşan numara veya profil gerçek görünse bile yalnızca o kişinin iddiasına güvenmeyin. Resmî uygulama içinden başlatılan destek talebi, mesajla gelen yönlendirmeden daha güvenilir bir doğrulama yoludur.'
]),
starter('guvenlik-dolandiricilik','Sahte Siteler','sahte-bozum-sitelerini-anlamanin-temel-yollari','Sahte bozum sitelerini anlamanın temel yolları','Alan adı, iletişim ve yönlendirme davranışları üzerinden temel sahte site kontrolü.',[
'Sahte bozum siteleri çoğu zaman tanıdık bir markanın adını, renklerini veya logosunu taklit eder. Alan adındaki küçük yazım farkları, yalnızca sosyal medya hesabına yönlendiren iletişim bilgileri, acele ettiren geri sayımlar ve olağan dışı oranlar dikkat edilmesi gereken işaretlerdir. Site görünümü tek başına güven kanıtı değildir.',
'İşlemden önce adres çubuğundaki alan adını, sitenin yayımladığı resmî iletişim kanallarını ve güvenlik uyarılarını karşılaştırın. Arama reklamı ya da mesajdaki bağlantı yerine adresi kendiniz yazarak ulaşmayı tercih edin. Site şifre, SMS kodu veya banka erişimi talep ediyorsa sayfayı kapatın. Şüpheli ekranları saklamak, gerektiğinde bildirim yapmayı kolaylaştırır.'
]),
starter('guvenlik-dolandiricilik','WhatsApp Güvenliği','dogru-sky-bozum-whatsapp-hesabi-nasil-kontrol-edilir','Doğru Sky Bozum WhatsApp hesabı nasıl kontrol edilir?','WhatsApp üzerinden gelen yönlendirmeleri resmî iletişim bilgisiyle çapraz kontrol etme rehberi.',[
'WhatsApp üzerinden gelen bir hesabın profil fotoğrafı veya adı tek başına doğrulama sağlamaz. Doğru iletişim kanalını kontrol etmek için Sky Bozum sitesinde yayımlanan resmî bağlantı ve numarayı esas alın. Mesaj içindeki linke tıklamak yerine, siteye kendiniz girip iletişim alanından karşılaştırma yapmak daha güvenlidir.',
'Resmî görünen hesaplar da sizden şifre, SMS kodu, uygulama onayı veya banka girişi istememelidir. Acele ettiren, yüksek kazanç vaat eden veya sohbeti başka bir numaraya taşıyan mesajları dikkatle değerlendirin. Şüpheli mesajı silmeden önce ekran görüntüsü alın; ardından resmî kanaldan konuyu teyit edin. Böylece yanlış kişiye bilgi verme riski azalır.'
]),
starter('guvenlik-dolandiricilik','Şüpheli İşlem Bildirimleri','supheli-bir-teklif-veya-mesaj-aldiginizda-ne-yapmalisiniz','Şüpheli bir teklif veya mesaj aldığınızda ne yapmalısınız?','Şüpheli iletişimde ilk yapılacaklar ve kaçınılacak davranışlar.',[
'Şüpheli bir teklif veya mesaj aldığınızda ilk adım bağlantıya tıklamamak, kod paylaşmamak ve karşı tarafın istediği acil işlemi yapmamaktır. Mesajın ekran görüntüsünü, gönderici bilgisini ve varsa bağlantı adresini saklayın. Bu kayıtlar hem resmi destek hem de gerektiğinde ilgili platform bildirimi için yararlı olur.',
'Teklifin doğruluğunu mesajdaki numaradan değil, resmî web sitesinde yayımlanan iletişim kanalından kontrol edin. Hesabınızla ilgili bir risk olduğundan şüpheleniyorsanız parolanızı değiştirin ve oturumları gözden geçirin. Maddi kayıp veya hesap ele geçirme şüphesi oluştuysa zaman kaybetmeden ilgili hizmet sağlayıcısına ve gerekli resmî başvuru kanallarına kayıt bırakın.'
]),
starter('sky-bozum-destek-topluluk','Duyurular','sky-bozum-topluluk-alani-kullanim-rehberi','Sky Bozum topluluk alanı kullanım rehberi','Toplulukta doğru kategori seçimi, saygılı iletişim ve güvenli paylaşım için başlangıç rehberi.',[
'Sky Bozum topluluk alanı; mobil ödeme, dijital kod, dijital cüzdan, oran ve güvenlik konularında deneyim ve soru paylaşımı için düzenlenmiştir. Yeni konu açarken ilgili ana bölüm ve alt kategoriyi seçmek, başlığın kısa ve açık olmasına dikkat etmek diğer kullanıcıların içeriği daha kolay bulmasını sağlar. Konu içinde işlem türü ve yaşanan durum yazılabilir.',
'Kişisel veri, kod, hesap şifresi, SMS doğrulama bilgisi veya başkasına ait belge paylaşılmamalıdır. Bir sorun bildirirken tarih, hata metni ve işlem numarasının güvenli kısmı gibi doğrulanabilir bilgiler yeterli olur. Hakaret, hedef gösterme, kanıtsız suçlama veya başka kullanıcıları acele işlem yapmaya yönlendiren içerikler topluluk amacına uygun değildir.'
]),
starter('sky-bozum-destek-topluluk','Nasıl İşlem Yapılır?','ilk-kez-bozum-yapacaklar-icin-baslangic-rehberi','İlk kez bozum yapacaklar için başlangıç rehberi','İlk işlemden önce koşulları anlama ve güvenli iletişim için temel sıralama.',[
'İlk kez bozum yapacak kişiler için en sağlıklı başlangıç, hangi hizmetin kullanılacağını ve yaklaşık tutarı netleştirmektir. Ardından resmî site üzerinden güncel oran, iletişim kanalı ve gerekli adımlar kontrol edilmelidir. İşlem süresini ya da net ödemeyi yalnızca sosyal medya mesajına göre varsaymak yerine yazılı teyit almak gerekir.',
'Süreçte yalnızca gerekli bilgileri verin; parola, SMS kodu, banka giriş bilgisi veya uzaktan erişim talebi kabul edilmemelidir. Kod veya bakiye gibi geri alınması zor bilgileri paylaşmadan önce tüm koşulları okuyun. Bir noktada belirsizlik varsa işlemi durdurup resmî destek kaydı açmak, hızlı davranmaktan daha güvenli bir seçimdir.'
]),
starter('sky-bozum-destek-topluluk','Sık Sorulanlar','yeni-musterilerden-en-sik-gelen-10-soru','Yeni müşterilerden en sık gelen 10 soru','Yeni kullanıcıların karar vermeden önce en çok kontrol ettiği başlıkları bir araya getiren özet.',[
'Yeni kullanıcıların sık sorduğu konular; işlem için uygun hizmetler, güncel oran, net ödeme, olası komisyon, işlem süresi, limitler, kod geçerliliği, güvenli iletişim, bekleyen işlemler ve destek kaydıdır. Bu soruların tek bir cevabı yoktur; hizmet türü ve hesabın durumu sonucu değiştirebilir. Bu nedenle herkes için geçerli kesin sözler vermek doğru değildir.',
'En pratik yaklaşım; işlemden önce güncel koşulları kontrol etmek, net tutarı yazılı teyit etmek ve resmî kanalı kullanmaktır. Hata veya gecikme yaşanırsa işlem numarası, tarih ve ekran görüntüsüyle destek kaydı açın. Şifre, SMS doğrulama kodu ve banka giriş bilgisinin bu soruların hiçbirini çözmek için paylaşılmaması gerektiğini unutmayın.'
]),
starter('sky-bozum-destek-topluluk','Öneri & Geri Bildirim','sky-bozumda-gormek-istediginiz-ozellikleri-paylasin','Sky Bozum’da görmek istediğiniz özellikleri paylaşın','Öneri ve geri bildirim konularının daha uygulanabilir yazılması için kısa yönlendirme.',[
'Sky Bozum hakkında öneri paylaşırken hangi sayfada veya hangi adımda ihtiyaç oluştuğunu yazmak, geri bildirimi daha faydalı hale getirir. Örneğin yalnızca “siteyi geliştirin” demek yerine, hangi bilginin eksik kaldığını, hangi butonun anlaşılmadığını veya hangi işlem adımının zorlayıcı olduğunu belirtmek daha somut bir değerlendirme sağlar.',
'Geri bildirim içinde kişisel veri, işlem kodu veya başka kullanıcıların bilgisi bulunmamalıdır. Bir güvenlik sorunu ya da şüpheli iletişim söz konusuysa bunu herkese açık konu yerine resmî destek kanalına iletmek daha doğrudur. Uygulanabilir öneriler zamanla değerlendirilir; her önerinin hemen yayına alınacağı garanti edilmez.'
]),
starter('sky-bozum-destek-topluluk','Genel Sohbet','mobil-odeme-ve-dijital-bakiye-dunyasi-hakkinda-genel-sohbet','Mobil ödeme ve dijital bakiye dünyası hakkında genel sohbet','Konu dışına taşmadan deneyim ve genel sorular için topluluk alanı.',[
'Genel Sohbet alanı; mobil ödeme, dijital kodlar ve dijital cüzdanlarla ilgili genel deneyimlerin, soruların ve gündem notlarının konuşulması içindir. Belirli bir işlem hatası veya güvenlik olayı varsa ilgili alt kategori seçilmelidir; böylece konu daha kolay bulunur ve doğru bağlamda yanıtlanabilir.',
'Sohbette kişisel bilgi, kullanılabilir kod, hesap ekranı veya başka kişilerin özel verileri paylaşılmamalıdır. Kesin sonuç vaat eden, kullanıcıları acele karar vermeye zorlayan veya kanıtsız suçlama içeren mesajlar yerine, kendi deneyiminizi açık ve sakin biçimde anlatın. Bu alan destek kaydının yerine geçmez; işlemle ilgili acil veya hassas durumlarda resmî iletişim kanalı kullanılmalıdır.'
]),
];

export const publicForumKeys=forumStarterTopics.map(topic=>`${topic.sectionSlug}/${topic.categorySlug}`);
export const getForumStarterTopic=(sectionSlug:string,categorySlug:string,topicSlug?:string)=>forumStarterTopics.find(topic=>topic.sectionSlug===sectionSlug&&topic.categorySlug===categorySlug&&(!topicSlug||topic.slug===topicSlug));
export const findForumSection=(slug:string)=>forumSections.find(section=>section.slug===slug);
export const findForumCategory=(sectionSlug:string,categorySlug:string)=>{const section=findForumSection(sectionSlug);const title=section?.categories.find(category=>slugifyForumCategory(category)===categorySlug);return section&&title?{section,title,slug:categorySlug}:null};
