export type ForumSection={slug:string;title:string;icon:string;description:string;categories:string[]};
// Önceki geniş forum mimarisi veri kaybı olmadan burada tutulur. Bu liste public
// rotalarda kullanılmaz; yalnızca yönetim arşivi için kaynak olarak kalır.
export const archivedForumSections:ForumSection[]=[
{slug:'sky-bozum-duyurular',title:'Sky Bozum ve Duyurular',icon:'✦',description:'Topluluk kuralları, platform yenilikleri ve resmî bilgilendirmeler.',categories:['Forum kuralları','Sky Bozum duyuruları','Yeni özellikler','Kampanyalar ve fırsatlar','Öneri ve geri bildirim']},
{slug:'yeni-baslayanlar',title:'Yeni Başlayanlar',icon:'◎',description:'Forumu, dijital hizmetleri ve temel internet araçlarını yeni kullananlar için başlangıç alanı.',categories:['Foruma başlangıç','Temel internet bilgileri','İlk web sitesi','İlk online satış','Sık sorulan sorular']},
{slug:'mobil-odeme',title:'Mobil Ödeme',icon:'▣',description:'Operatör limitleri, faturaya yansıtma, hata ve güvenlik konuları.',categories:['Vodafone mobil ödeme','Turkcell mobil ödeme','Türk Telekom mobil ödeme','Limit ve fatura işlemleri','Hata ve çözüm yolları','Güvenli kullanım']},
{slug:'dijital-kodlar',title:'Dijital Kodlar ve Gift Card',icon:'◇',description:'Oyun kodları, hediye kartları, bölge uyumu ve güvenli teslim süreçleri.',categories:['Apple Gift Card','Google Play kodları','Steam cüzdan kodları','Razer Gold','Oyun ve E-PIN kodları','Kod güvenliği']},
{slug:'sikayet-ve-cozum',title:'Şikâyet ve Çözüm',icon:'!',description:'Sorunların belgeli biçimde paylaşılması ve çözüm durumunun takip edilmesi.',categories:['Bozum işlemi şikâyetleri','Operatör sorunları','Dijital kod sorunları','Online alışveriş şikâyetleri','Çözülen şikâyetler','Yanıt bekleyenler']},
{slug:'dijital-guvenlik',title:'Dijital Güvenlik',icon:'⌾',description:'Hesap güvenliği, dolandırıcılık belirtileri, kimlik avı ve veri koruma.',categories:['Hesap güvenliği','Dolandırıcılık uyarıları','Kimlik avı ve sahte bağlantılar','Şifre ve iki aşamalı doğrulama','Kişisel veri güvenliği','Güvenlik haberleri']},
{slug:'webmaster-genel',title:'Webmaster Genel',icon:'⌘',description:'Site sahiplerinin genel soruları, deneyimleri ve proje değerlendirmeleri.',categories:['Webmaster gündemi','Site değerlendirme','Proje fikirleri','Araç ve kaynak önerileri','Sorun ve çözümler','Webmaster dayanışması']},
{slug:'web-gelistirme',title:'Web Geliştirme',icon:'</>',description:'Ön yüz, arka uç, performans, erişilebilirlik ve web standartları.',categories:['HTML ve CSS','JavaScript ve TypeScript','React ve Next.js','Sunucu tarafı geliştirme','Web performansı','Erişilebilirlik']},
{slug:'cms-ve-wordpress',title:'CMS ve WordPress',icon:'W',description:'İçerik yönetim sistemlerinin kurulumu, bakımı, tema ve eklentileri.',categories:['WordPress başlangıç','Tema geliştirme','Eklenti seçimi','Güvenlik ve yedekleme','Hızlandırma','Diğer içerik sistemleri']},
{slug:'seo-ve-arama',title:'SEO ve Arama Motorları',icon:'↗',description:'Teknik SEO, içerik kalitesi, ölçüm ve arama görünürlüğü.',categories:['SEO başlangıç','Teknik SEO','İçerik ve arama niyeti','Search Console','Yerel SEO','SEO sorunları ve analiz']},
{slug:'yapay-zeka',title:'Yapay Zekâ Araçları',icon:'✧',description:'Yapay zekâ araçlarının üretken, güvenli ve şeffaf kullanım biçimleri.',categories:['Yapay zekâ başlangıç','Metin ve araştırma araçları','Görsel üretim','Kodlama yardımcıları','Otomasyon fikirleri','Doğruluk ve etik']},
{slug:'grafik-ve-tasarim',title:'Grafik ve Tasarım',icon:'◈',description:'Görsel tasarım, kullanıcı deneyimi, marka dili ve üretim araçları.',categories:['Grafik tasarım temelleri','UI ve UX tasarımı','Logo ve kurumsal kimlik','Adobe araçları','Canva ve pratik araçlar','Tasarım geri bildirimi']},
{slug:'sosyal-medya',title:'Sosyal Medya',icon:'#',description:'Platform güvenliği, içerik planlama, ölçüm ve topluluk yönetimi.',categories:['Instagram','YouTube','TikTok','Facebook','X ve Threads','Sosyal medya güvenliği']},
{slug:'e-ticaret',title:'E-Ticaret',icon:'₺',description:'Mağaza kurulumu, ürün, ödeme, teslimat ve tüketici deneyimi.',categories:['E-ticarete başlangıç','Mağaza altyapıları','Ürün ve stok yönetimi','Ödeme yöntemleri','Kargo ve teslimat','İade ve tüketici hakları']},
{slug:'pazaryerleri',title:'Pazaryerleri',icon:'▤',description:'Pazaryeri mağazalarının operasyonu, komisyonları ve müşteri süreçleri.',categories:['Trendyol','Hepsiburada','Amazon Türkiye','N11','Etsy ve global pazarlar','Pazaryeri operasyonu']},
{slug:'dijital-pazarlama',title:'Dijital Pazarlama',icon:'◉',description:'Reklam ölçümü, hedef kitle, dönüşüm ve sürdürülebilir büyüme.',categories:['Google Ads','Meta reklamları','İçerik pazarlaması','E-posta pazarlaması','Dönüşüm ölçümü','Bütçe ve performans']},
{slug:'icerik-uretimi',title:'İçerik Üretimi',icon:'¶',description:'Makaleler, video, görsel ve yayın planlarında kalite odaklı üretim.',categories:['Makale hazırlama','Editörlük ve doğrulama','Video içerik','İçerik takvimi','Kaynak kullanımı','Telif ve lisans']},
{slug:'domain-ve-hosting',title:'Domain ve Hosting',icon:'◎',description:'Alan adı, barındırma, DNS, SSL ve sunucu seçimi hakkında teknik bilgi.',categories:['Alan adı seçimi','Domain transferi','Hosting seçimi','DNS ve SSL','Sunucu yönetimi','Kesinti ve teknik sorunlar']},
{slug:'yazilim-ve-programlama',title:'Yazılım ve Programlama',icon:'{ }',description:'Programlama dilleri, uygulama geliştirme ve yazılım pratiği.',categories:['Programlamaya başlangıç','Python','PHP','Mobil uygulamalar','Veritabanları','Git ve proje yönetimi']},
{slug:'teknoloji-gundemi',title:'Teknoloji Gündemi',icon:'⚡',description:'Yeni ürünler, platform değişiklikleri ve doğrulanmış teknoloji gelişmeleri.',categories:['Teknoloji haberleri','Mobil cihazlar','Uygulamalar ve servisler','İşletim sistemleri','İnternet teknolojileri','Yeni ürün değerlendirmeleri']},
{slug:'donanim-ve-teknik-destek',title:'Donanım ve Teknik Destek',icon:'⚙',description:'Bilgisayar, telefon, ağ ve çevre birimi sorunları için yardımlaşma.',categories:['Bilgisayar donanımı','Telefon ve tablet','Ağ ve modem','Çevre birimleri','Arıza ve teknik destek','Hangisini almalıyım']},
{slug:'girisimcilik',title:'Girişimcilik ve İş Fikirleri',icon:'▲',description:'Fikir doğrulama, küçük işletme, maliyet ve büyüme deneyimleri.',categories:['İş fikri değerlendirme','Girişime başlangıç','Maliyet ve bütçe','Müşteri bulma','Markalaşma','Başarısızlık ve dersler']},
{slug:'freelance-ve-hizmetler',title:'Freelance ve Hizmetler',icon:'◆',description:'Freelance çalışma, hizmet kapsamı, teklif ve güvenli iş ilişkileri.',categories:['Freelance başlangıç','Teklif hazırlama','Müşteri iletişimi','Sözleşme ve teslim','Portföy geliştirme','Hizmet deneyimleri']},
{slug:'sohbet',title:'Sohbet ve Topluluk',icon:'☵',description:'Üyelerin kendini tanıttığı, gündemi ve günlük ilgi alanlarını konuştuğu bölüm.',categories:['Tanışma alanı','Güncel konular','Oyun ve eğlence','Film, dizi ve müzik','Öneriler','Serbest sohbet']},
{slug:'forum-destek',title:'Forum Destek',icon:'?',description:'Üyelik, içerik bildirimi, teknik sorun ve forum kullanım desteği.',categories:['Üyelik ve hesap sorunları','Forum kullanım rehberi','İçerik şikâyeti','Teknik sorun bildirimi','Öneri ve geri bildirim']}
];

export const forumSections:ForumSection[]=[
{slug:'mobil-odeme-operatorler',title:'Mobil Ödeme & Operatörler',icon:'▣',description:'Mobil ödeme sistemleri, operatörler, limitler ve işlem süreçleri hakkında bilgi ve destek.',categories:['Mobil Ödeme Genel','Turkcell','Vodafone','Türk Telekom','Mobil Ödeme Limit & Sorunları']},
{slug:'dijital-kod-hediye-kartlari',title:'Dijital Kod & Hediye Kartları',icon:'◇',description:'Razer Gold, Apple, Steam ve diğer dijital kodlar hakkında kullanım ve bozum bilgileri.',categories:['Razer Gold TL','Razer Gold USD','Apple / iTunes','Steam','Kod Sorunları']},
{slug:'dijital-cuzdanlar',title:'Dijital Cüzdanlar',icon:'◉',description:'Paycell, Pokus, Vodafone Pay ve dijital cüzdan işlemleri hakkında rehber ve destek.',categories:['Paycell','Pokus','Vodafone Pay','Dijital Cüzdan Limitleri','Dijital Cüzdan Sorunları']},
{slug:'bozum-oranlar',title:'Bozum & Oranlar',icon:'₺',description:'Bozum oranları, hesaplama, komisyonlar ve ödeme süreci hakkında bilgiler.',categories:['Güncel Oranlar','Oran Hesaplama','Komisyonlar','Ödeme Süresi','Yüksek Oran Uyarıları']},
{slug:'guvenlik-dolandiricilik',title:'Güvenlik & Dolandırıcılık',icon:'⌁',description:'Güvenli işlem, kişisel bilgi paylaşımı, sahte siteler ve dolandırıcılıktan korunma rehberleri.',categories:['Güvenli İşlem','Paylaşılmaması Gereken Bilgiler','Sahte Siteler','WhatsApp Güvenliği','Şüpheli İşlem Bildirimleri']},
{slug:'sky-bozum-destek-topluluk',title:'Sky Bozum Destek & Topluluk',icon:'✦',description:'Sky Bozum kullanımı, duyurular, öneriler ve topluluk konuşmaları.',categories:['Duyurular','Nasıl İşlem Yapılır?','Sık Sorulanlar','Öneri & Geri Bildirim','Genel Sohbet']},
];

export const slugifyForumCategory=(value:string)=>value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

export type ForumStarterTopic={slug:string;sectionSlug:string;category:string;categorySlug:string;title:string;summary:string;body:string[];author:'Sky Bozum';publishedAt:string};
const starter=(sectionSlug:string,category:string,slug:string,title:string,summary:string,body:string[]):ForumStarterTopic=>({sectionSlug,category,categorySlug:slugifyForumCategory(category),slug,title,summary,body,author:'Sky Bozum',publishedAt:'2026-08-13'});

// Başlangıç içerikleri build-time yönetim yayınlarıdır; ziyaretçi veya müşteri kimliği taklit edilmez.
const forumInitialTopics:ForumStarterTopic[]=[
starter('mobil-odeme-operatorler','Mobil Ödeme Genel','mobil-odeme-bozum-islemi-nasil-ilerler','Mobil ödeme bozum işlemi nasıl ilerler?','İşlem öncesi kontrol, yazılı teyit ve tamamlanma adımları.',[
'Mobil ödeme ile yapılacak bir işlemde önce hangi hizmetin kullanılacağı, tutar ve güncel koşullar netleştirilmelidir. Operatör hattının açık olması tek başına işlem yapılabileceği anlamına gelmez; limit, fatura durumu ve kullanılan uygulamanın kendi kuralları sonucu etkileyebilir. Ekrandaki oran veya süre bilgisini karar vermeden önce güncel haliyle kontrol etmek daha sağlıklıdır.',
'İşlem boyunca yalnızca gerekli bilgileri paylaşın ve yapılan yönlendirmeyi yazılı olarak saklayın. Hesap şifresi, SMS doğrulama kodu veya kart güvenlik bilgisi isteniyorsa işlemi durdurun. Beklenmeyen bir hata oluştuğunda operatörünüzün ya da ilgili uygulamanın resmî destek kanalıyla durumu teyit etmek, sonradan yaşanabilecek karışıklıkları azaltır.'
]),
starter('mobil-odeme-operatorler','Turkcell','turkcell-mobil-odeme-kullanirken-nelere-dikkat-edilmeli','Turkcell mobil ödeme kullanırken nelere dikkat edilmeli?','Turkcell hattı üzerinden işlemden önce bakılması gereken temel noktalar.',[
'Turkcell mobil ödeme kullanılırken hat sahibi bilgisi, hattın kullanım durumu ve o dönemde tanımlı limitler önem taşır. Limitler paket, fatura geçmişi, hat yaşı veya kurumun risk değerlendirmesi gibi nedenlerle değişebilir. Bu nedenle geçmişte çalışan bir işlemin her zaman aynı biçimde çalışacağını varsaymamak gerekir.',
'Ödeme ekranında görünen tutarı ve işlem açıklamasını dikkatle okuyun. Tanımadığınız bir uygulama, içerik servisi veya bağlantı üzerinden işlem başlatmayın. Şüpheli bir ücretlendirme fark ederseniz ekran görüntüsünü saklayın; öncelikle Turkcell’in resmî kanallarından ilgili hizmeti doğrulayın. Şifre ve SMS kodu, destek görevlisi olduğunu söyleyen biriyle dahi paylaşılmamalıdır.'
]),
starter('mobil-odeme-operatorler','Vodafone','vodafone-ile-dijital-urun-satin-alma-rehberi','Vodafone ile dijital ürün satın alma rehberi','Vodafone mobil ödeme limiti ile dijital ürün satın alma koşullarını ayırt etmeye yardımcı kısa rehber.',[
'Vodafone mobil ödeme limiti, hattınızın kullanıma açık olduğu her anda sabit bir tutar olarak düşünülmemelidir. Operatörün güncel politikaları, faturaya yansıtılan işlemler ve hattın geçmişi limiti etkileyebilir. Bir işlem planlamadan önce kendi hesabınızdaki güncel limiti ve varsa bekleyen tahsilatları kontrol etmek gerekir.',
'Dijital ürün satın alma sürecinde ürün türü, toplam tutar, mağaza ve teslim yöntemi açık biçimde görülmelidir. Resmî olmayan kanallardan gelen “limit artırma” ya da “hemen onay” teklifleri risk işaretidir. Vodafone adına iletişim kurduğunu söyleyen bir hesabın doğruluğunu yalnızca resmî uygulama, web sitesi veya doğrulanmış müşteri hizmetleri üzerinden kontrol edin.'
]),
starter('mobil-odeme-operatorler','Türk Telekom','turk-telekom-mobil-odeme-hakkinda-temel-bilgiler','Türk Telekom mobil ödeme hakkında temel bilgiler','Türk Telekom mobil ödeme kullanımı için kavramları ve güvenlik sınırlarını açıklayan not.',[
'Türk Telekom mobil ödeme, uygun hizmetlerde bedelin telefon faturası veya hat bakiyesi üzerinden tahsil edilmesine imkân veren bir ödeme yöntemidir. Hangi hizmetlerin uygun olduğu, limitlerin nasıl belirlendiği ve tahsilatın ne zaman yansıyacağı dönemsel olarak değişebilir. Bu nedenle işlem öncesinde Türk Telekom hesabınız ve hizmetin kendi ödeme ekranı birlikte incelenmelidir.',
'İşleme geçmeden önce uygulama veya web adresinin resmî olup olmadığını kontrol edin. İptal, iade veya hata halinde saklanacak kayıtlar; işlem numarası, tarih, tutar ve ekran görüntüsüdür. Destek için size yazan kişi şifre ya da doğrulama kodu isterse bu normal bir kontrol değildir. Resmî destek kanalından yeni bir kayıt açmak daha güvenli yoldur.'
]),
starter('mobil-odeme-operatorler','Mobil Ödeme Limit & Sorunları','mobil-odeme-islemi-neden-reddedilebilir','Mobil ödeme işlemi neden reddedilebilir?','Reddedilen mobil ödeme işlemlerinde rastgele tekrar denemeden önce yapılacak kontroller.',[
'Mobil ödeme işlemleri limit yetersizliği, hat veya fatura durumu, hizmet sağlayıcının kuralları ya da anlık teknik kontroller nedeniyle reddedilebilir. Ret ekranı tek başına hesabınızda kalıcı bir sorun olduğu anlamına gelmez. Aynı işlemi peş peşe denemek yerine hata mesajını, zamanı ve kullanılan hizmeti not etmek daha yararlıdır.',
'Önce operatör hesabınızda açık bir kısıtlama, ödenmemiş borç veya limit durumu olup olmadığını kontrol edin. Ardından ilgili uygulamanın resmî destek kaydına bakın. Herhangi bir kişi “reddi kaldırmak” için SMS kodu, şifre veya uzaktan erişim isterse işlem yapmayın. Sorunu çözmek için resmî kanallar dışında hesap bilgisi vermek güvenlik riskini büyütebilir.'
]),
starter('dijital-kod-hediye-kartlari','Razer Gold TL','razer-gold-tl-bozum-islemi-nasil-yapilir','Razer Gold TL bozum işlemi nasıl yapılır?','Razer Gold TL kodlarında değer, geçerlilik ve işlem öncesi kontrol noktaları.',[
'Razer Gold TL kodu ile işlem düşünülüyorsa kodun para birimi, yüz değeri ve henüz kullanılmamış olması temel şartlardır. Kod görselini veya PIN bilgisini paylaşmadan önce işlem koşullarını yazılı olarak netleştirmek gerekir. Aynı isimli fakat farklı para birimli ürünler birbirinin yerine geçmeyebilir; ürün sayfasındaki bölge ve değer bilgisini dikkatle kontrol edin.',
'Kod teslim edildiğinde geri alınması her zaman mümkün olmayabilir. Bu nedenle yalnızca gerekli kanal üzerinden ilerleyin ve kodu üçüncü kişilerle paylaşmayın. “Önce kodu gönder, sonra bakalım” gibi belirsiz yönlendirmelerden kaçının. Kodla ilgili geçersizlik bildirimi varsa satın alma kaydı, seri bilgisi ve varsa hata ekranı saklanmalı; ilk kontrol kodu veren resmî satıcı veya platformla yapılmalıdır.'
]),
starter('dijital-kod-hediye-kartlari','Razer Gold USD','razer-gold-usd-ile-tl-kodlari-arasindaki-farklar','Razer Gold USD ile TL kodları arasındaki farklar','Para birimi ve bölge uyumu nedeniyle oluşabilecek sorunları önceden görmeye yardımcı açıklama.',[
'Razer Gold USD ve TL kodları yalnızca üzerlerinde yazan tutar bakımından değil, kullanılabildikleri hesap veya bölge koşulları bakımından da farklı olabilir. Bir kodun USD olması, TL hesabında aynı değerle kullanılacağı ya da dönüştürülebileceği anlamına gelmez. Satın alma öncesi ürün açıklamasındaki para birimi, bölge ve kullanım şartları mutlaka okunmalıdır.',
'Kod kullanılmadan önce hesap ayarlarını ve ürünün geçerli olduğu platformu kontrol edin. Kur farkı, bölge kısıtı veya satıcı politikasından kaynaklanan ihtilaflarda tek başına kod ekranı yeterli olmayabilir; sipariş belgesi ve ürün açıklaması da önem taşır. Kodun tam metnini sosyal medya veya mesaj gruplarında paylaşmak, kullanılma riskini doğurur.'
]),
starter('dijital-kod-hediye-kartlari','Apple / iTunes','apple-hediye-karti-bozum-oncesi-kontrol-listesi','Apple hediye kartı bozum öncesi kontrol listesi','Apple hediye kartlarında bakiye, bölge ve teslim güvenliği için kısa liste.',[
'Apple hediye kartı ile ilgili herhangi bir işlemden önce kartın hangi ülke veya bölge için düzenlendiğini kontrol edin. Apple hesabının mağaza ülkesi ile kartın bölgesi uyumsuzsa kod kullanılmayabilir. Kartın fiziksel ya da dijital oluşu, satın alma kaydı ve üzerinde görünen değer de uyuşmazlık halinde gerekli olabilir.',
'Apple hiçbir koşulda hediye kartı kodunun telefonla, e-postayla veya mesajla paylaşılmasını istemez. Özellikle “borç”, “ceza” ya da “hesabı kurtarma” bahanesiyle kod istenmesi dolandırıcılık işaretidir. Kodda sorun yaşarsanız kartı satan yetkili kanalın belgesini ve hata ekranını saklayın; Apple hesabınızın şifresini veya iki aşamalı doğrulama kodunu paylaşmayın.'
]),
starter('dijital-kod-hediye-kartlari','Steam','steam-kodlarinda-bolge-ve-para-birimi-neden-onemlidir','Steam kodlarında bölge ve para birimi neden önemlidir?','Steam cüzdan kodu seçerken hesabın ülkesini ve ürünün kullanım koşullarını birlikte değerlendirin.',[
'Steam cüzdan kodlarında bölge ve para birimi hesabın mağaza ayarlarıyla ilişkilidir. Bir ülkede satılan veya belirli para birimiyle düzenlenmiş kod, başka bir bölgedeki hesapta kabul edilmeyebilir. Kod satın alınmadan önce ürün başlığındaki bölge bilgisi ile Steam hesabının mağaza ülkesini karşılaştırmak gerekir.',
'Kodun üzerindeki değeri farklı bir para birimine çevireceğini varsayarak işlem yapmayın. Kullanılmamış kodların dahi uyumsuzluk nedeniyle kabul edilmemesi mümkündür. Sorun yaşanırsa kodu tekrar tekrar denemek yerine hata mesajını kaydedin ve satın aldığınız kanalın iade/yardım koşullarına bakın. Kodun PIN bilgisini destek talebi açarken dahi herkese açık bir yere yazmayın.'
]),
starter('dijital-kod-hediye-kartlari','Kod Sorunları','gecersiz-veya-daha-once-kullanilmis-kod-durumunda-ne-yapilmali','Geçersiz veya daha önce kullanılmış kod durumunda ne yapılmalı?','Dijital kod hatasında delilleri koruyup doğru sırayla destek almak için temel adımlar.',[
'Bir kod “geçersiz” veya “daha önce kullanılmış” görünüyorsa önce kodu nereden ve ne zaman aldığınızı, sipariş numarasını ve hata ekranını kaydedin. Kodu birçok farklı cihazda denemek veya herkese göndermek, olayı açıklığa kavuşturmaz; tersine güvenlik ve iade sürecini zorlaştırabilir. Kodun para birimi ve bölgesi de kontrol edilmelidir.',
'İlk başvuru kodu satan yetkili kanal üzerinden, mümkünse yazılı olarak yapılmalıdır. Sipariş belgesi, ürün açıklaması ve hata ekranı çoğu zaman yeterli başlangıç kaydı sağlar. Sosyal medya aracılığıyla yardım teklif eden bilinmeyen hesaplara kodu veya hesap giriş bilgilerini göndermeyin. Hesap şifresi ve SMS doğrulama kodu bu tür bir sorunu çözmek için gerekli değildir.'
]),
starter('dijital-cuzdanlar','Paycell','paycell-ile-dijital-urun-satin-alma-rehberi','Paycell ile dijital ürün satın alma rehberi','Paycell kartla alışveriş öncesinde hesap, limit, mağaza ve kayıt kontrolü.',[
'Paycell ile ilgili bir işlem planlarken bakiyenin kaynağını, güncel kullanım koşullarını ve hesabın doğrulama durumunu dikkate alın. Dijital cüzdanlarda görünen bakiye, her işlem için serbestçe kullanılabilir olmayabilir. Limit, güvenlik incelemesi veya hizmetin kuralları işlemin gerçekleşmesini etkileyebilir.',
'İşlem türü ve tahmini tutar yazılı şekilde anlaşılmadan bakiye veya kod paylaşmayın. Paycell hesabına erişim için şifre, tek kullanımlık SMS kodu ya da cihaz onayı isteyen kişilere bilgi vermeyin. Bekleyen veya reddedilen bir işlemde önce uygulama içindeki kayıtları inceleyin; ardından Paycell’in resmî destek kanalıyla işlem numarası üzerinden iletişim kurun.'
]),
starter('dijital-cuzdanlar','Pokus','pokus-bakiyesi-nasil-degerlendirilir','Pokus bakiyesi nasıl değerlendirilir?','Pokus bakiyesini kullanmadan önce uygulama içi koşulları ve güvenlik adımlarını inceleyin.',[
'Pokus bakiyesi, hesabınızdaki görünür tutardan ibaret değildir; kullanım alanları, para transferi veya harcama kuralları güncel ürün şartlarına bağlıdır. Uygulama içindeki limitleri ve sözleşme özetini kontrol etmek, yanlış beklenti oluşmasını önler. Özellikle üçüncü tarafların sunduğu hızlı işlem vaatleri, cüzdanın resmî kurallarından bağımsız olabilir.',
'Hesap güvenliği için giriş bilgilerinizi paylaşmayın ve uygulama dışından gelen bağlantılarla oturum açmayın. Bir işlem beklemede kalırsa tutar, tarih ve işlem açıklamasını not edin. Aynı talimatı tekrar tekrar vermeden önce uygulama bildirimlerini ve resmî destek kanallarını kontrol edin. Bu yaklaşım hem hata takibini hem de varsa itiraz sürecini kolaylaştırır.'
]),
starter('dijital-cuzdanlar','Vodafone Pay','vodafone-pay-ile-mobil-odeme-arasindaki-fark-nedir','Vodafone Pay ile mobil ödeme arasındaki fark nedir?','Dijital cüzdan bakiyesi ile telefon faturası üzerinden ödeme arasındaki temel ayrım.',[
'Vodafone Pay ve mobil ödeme benzer görünse de ödeme kaynağı ve işlem akışı bakımından farklıdır. Vodafone Pay, dijital cüzdan mantığıyla uygulama içi bakiye ve hizmetleri kapsarken; mobil ödeme, uygun harcamaların telefon faturası veya hat bakiyesi üzerinden tahsil edilmesine dayanır. Hangi yöntemin kullanılabildiği işlem yapılan hizmete ve hesabın durumuna göre değişir.',
'Karar vermeden önce ödeme ekranında hangi yöntemin seçildiğini, ücretin nereye yansıyacağını ve varsa limiti kontrol edin. Cüzdan hesabı ile hat hesabı için destek süreçleri de farklı olabilir. Tanımadığınız bir kişi bu yöntemlerden biri için parola, SMS kodu veya uzaktan erişim isterse işlem yapmayın; yalnızca resmî uygulama içinden yardım kaydı oluşturun.'
]),
starter('dijital-cuzdanlar','Dijital Cüzdan Limitleri','dijital-cuzdanlarda-gunluk-ve-aylik-limit-mantigi','Dijital cüzdanlarda günlük ve aylık limit mantığı','Limitlerin neden kişiden kişiye veya dönemden döneme değişebildiğini açıklayan kısa not.',[
'Dijital cüzdanlardaki günlük ve aylık limitler yalnızca bakiye büyüklüğüne göre belirlenmez. Hesap doğrulama seviyesi, işlem türü, mevzuat kaynaklı kontroller ve hizmet sağlayıcının risk politikası limitleri etkileyebilir. Bu nedenle başka bir kullanıcının gördüğü limitin sizin hesabınız için de geçerli olacağını varsaymak doğru değildir.',
'Limit kontrolü için uygulama içindeki resmî ekranları ve güncel sözleşme bilgisini esas alın. “Limit açma” veya “sınırsız hesap” adı altında yapılan üçüncü taraf teklifleri güvenilir bir kaynak sayılmaz. Limit nedeniyle işlem gerçekleşmiyorsa bunu aşmak için şifre, SMS kodu veya kimlik görseli paylaşmayın; doğrulama ve hesap desteği yalnızca hizmetin kendi resmî akışından yürütülmelidir.'
]),
starter('dijital-cuzdanlar','Dijital Cüzdan Sorunları','dijital-cuzdan-islemi-beklemede-kaldiginda-ne-kontrol-edilmeli','Dijital cüzdan işlemi beklemede kaldığında ne kontrol edilmeli?','Bekleyen dijital cüzdan işlemlerinde güvenli ve düzenli kontrol adımları.',[
'Dijital cüzdan işlemi beklemede kaldığında önce işlem geçmişindeki kayıt, saat ve tutar incelenmelidir. Bekleme; sistem yoğunluğu, güvenlik kontrolü, karşı tarafın onayı veya bağlantı hatası gibi farklı nedenlerden oluşabilir. Uygulama açıkken aynı işlemi yeniden başlatmak, çift kayıt veya kafa karışıklığı riskini artırabilir.',
'İşlem numarasını, ekran görüntüsünü ve varsa bildirim metnini saklayın. Daha sonra uygulamanın resmî yardım merkezinden bekleyen işlem için yönlendirme olup olmadığını kontrol edin. Destek adıyla ulaşan bir kişi hesabınıza giriş kodu isterse paylaşmayın. Gerçek destek süreci, sizden parolanızı veya tek kullanımlık doğrulama kodunuzu talep etmez.'
]),
starter('bozum-oranlar','Güncel Oranlar','bozum-oranlari-neden-degisebilir','Bozum oranları neden değişebilir?','Oran değişikliklerinin tek bir sebebe bağlanmaması gerektiğini açıklayan başlangıç notu.',[
'Bozum oranları hizmet türü, tutar, ürünün kullanılabilirliği, doğrulama gereksinimi ve piyasa koşulları gibi etkenlere göre değişebilir. Aynı gün içinde bile farklı ürünler için farklı oran görülmesi tek başına olağan dışı değildir. Geçmişte verilen bir teklifin sonraki işlem için otomatik olarak geçerli olduğunu düşünmemek gerekir.',
'Oranı değerlendirirken net elinize geçecek tutarı, varsa kesinti bilgisini ve işlem koşullarını aynı anda sorun. Yalnızca yüksek görünen yüzdeye odaklanmak, sonradan ek şartlarla karşılaşmanıza yol açabilir. Belirsiz veya aşırı yüksek bir teklif aldığınızda yazılı teyit isteyin; işlemden önce kod, şifre veya doğrulama bilgisi paylaşmayın.'
]),
starter('bozum-oranlar','Oran Hesaplama','1000-tl-bakiyeden-elime-ne-kadar-gecer','1.000 TL bakiyeden elime ne kadar geçer?','Oran hesaplanırken brüt tutar, net tutar ve olası kesintileri ayırma rehberi.',[
'Bir bakiyenin size ne kadar ödeme olarak döneceğini hesaplarken başlangıç tutarı ile net ödeme tutarını ayırmak gerekir. Yüzde oranı tek başına yeterli değildir; işlem türü, olası komisyonlar ve özel koşullar net sonucu değiştirebilir. Bu nedenle 1.000 TL için hesap yaparken “oran kaç?” yerine “net ödeme ne olur?” sorusunu sormak daha anlaşılırdır.',
'Hesaplama aracındaki sonuç tahmini bir karşılaştırma olarak görülmelidir. Kesin işlem öncesinde tutar, şartlar ve varsa kesintiler yazılı biçimde teyit edilmelidir. Aynı değer iki kez görünüyorsa bu, sabit oranla oluşan tek net tahmini ifade eder; aralık sunan ürünlerde ise alt ve üst değer ayrı ayrı değerlendirilmelidir.'
]),
starter('bozum-oranlar','Komisyonlar','bozum-orani-ile-komisyon-arasindaki-fark-nedir','Bozum oranı ile komisyon arasındaki fark nedir?','Yüzde oranı ve işlem kesintisini aynı kavram sanmamak için açıklama.',[
'Bozum oranı genellikle toplam değerin ne kadarının ödeme olarak hesaplandığını ifade eder. Komisyon ise işlem sırasında ayrıca uygulanan hizmet, transfer veya benzeri kesintiyi anlatabilir. Bazı hizmetlerde ikisi birlikte açıkça yazılırken, bazılarında net tutar doğrudan verilir. Bu nedenle farklı teklifleri karşılaştırırken hangi rakamın neyi anlattığını görmek önemlidir.',
'İşlem öncesinde net ödemenin, varsa transfer masrafının ve olası ek şartların yazılı olarak belirtilmesini isteyin. “Komisyonsuz” ifadesi net ödeme yüksek olacak demek değildir; oran da ayrıca değerlendirilmelidir. Karşı taraf yalnızca sözlü bilgi veriyor veya tutarı netleştirmeden kod istiyorsa ilerlemeyin. Kayıtlı bir açıklama olası anlaşmazlıkta daha sağlıklı bir başlangıç sağlar.'
]),
starter('bozum-oranlar','Ödeme Süresi','bozum-sonrasi-odeme-ne-kadar-surede-gelir','Bozum sonrası ödeme ne kadar sürede gelir?','Ödeme süresini garanti gibi görmeden etkileyen faktörleri kontrol etmeye yardımcı rehber.',[
'Bozum sonrası ödeme süresi işlem türüne, inceleme ihtiyacına, bankacılık saatlerine ve kullanılan ödeme kanalına göre değişebilir. “Anında” veya belirli bir dakika ifadesi, her kullanıcı ve her işlem için koşulsuz bir taahhüt olarak değerlendirilmemelidir. Özellikle yüksek tutar, yeni hesap veya ek doğrulama gerektiren işlemlerde süre uzayabilir.',
'İşlem başlamadan önce tahmini süreyi, hangi aşamada bilgilendirme yapılacağını ve gecikme durumunda hangi kanaldan destek alınacağını öğrenin. Ödeme beklenenden uzun sürerse işlem numarasıyla yazılı destek kaydı açın. Süreç hızlansın diye hesabınızın şifresini, SMS kodunu veya banka giriş bilgisini paylaşmak güvenli değildir.'
]),
starter('bozum-oranlar','Yüksek Oran Uyarıları','gercekci-olmayan-yuksek-oran-tekliflerine-neden-dikkat-edilmeli','Gerçekçi olmayan yüksek oran tekliflerine neden dikkat edilmeli?','Gerçekçi olmayan vaatleri risk işareti olarak değerlendirmek için kısa kontrol listesi.',[
'Piyasa koşullarından belirgin biçimde ayrılan yüksek oran teklifleri, özellikle hızlı karar vermeniz isteniyorsa dikkatle incelenmelidir. Teklifin neden diğerlerinden farklı olduğu açıkça anlatılmıyor, net ödeme yazılı teyit edilmiyor veya yalnızca mesaj uygulaması üzerinden ilerleniyorsa risk artar. Yüksek görünen yüzde, güvenli işlem anlamına gelmez.',
'Karar vermeden önce hizmetin resmî iletişim bilgisini, işlem koşullarını ve varsa şikâyet/itiraz yolunu kontrol edin. Kodun veya hesabın kontrolünü geri dönüşü olmayan biçimde vermeyin. Parola, SMS doğrulama kodu, banka kartı bilgisi veya uzaktan erişim talebi normal değildir. Şüphede kalındığında işlemi ertelemek, geri dönülmesi zor bir kayıptan daha güvenlidir.'
]),
starter('guvenlik-dolandiricilik','Güvenli İşlem','bozum-isleminde-hangi-bilgiler-paylasilabilir','Bozum işleminde hangi bilgiler paylaşılabilir?','Gerekli işlem bilgisini hesap güvenliğinden ayırmaya yardımcı temel prensipler.',[
'Bozum işleminde paylaşılabilecek bilgiler işlem türü, yaklaşık tutar ve hizmete göre değişebilir; ancak hesap erişimi sağlayan bilgiler bu kapsamda değildir. Bir işlem için ihtiyaç duyulan bilgiyi, hesabın kontrolünü tamamen devretmekten ayırmak gerekir. Ödeme veya teslimat koşulları net değilse kişisel veri paylaşımını asgari düzeyde tutun.',
'Parola, tek kullanımlık SMS kodu, uygulama onayı, kart güvenlik kodu ve internet bankacılığı giriş bilgileri paylaşılmamalıdır. Kimlik belgesi istenen istisnai bir işlemde dahi bunun neden gerekli olduğunu resmî kanal üzerinden doğrulayın. Yazılı süreç kaydı, işlem numarası ve açık iletişim bilgisi; güvenli ilerlemenin şifre paylaşmaktan çok daha doğru yollarıdır.'
]),
starter('guvenlik-dolandiricilik','Paylaşılmaması Gereken Bilgiler','sms-kodu-ve-hesap-sifresi-neden-paylasilmamali','SMS kodu ve hesap şifresi neden paylaşılmamalı?','Tek kullanımlık kodların ve parolaların neden destek sürecinin parçası olamayacağını açıklama.',[
'SMS ile gelen tek kullanımlık kodlar ve hesap şifreleri, hesabınıza giriş veya işlem onayı vermek için kullanılır. Bu bilgileri paylaşan kişi, fark etmeden başka birinin hesabı üzerinde işlem yapmasına imkân tanıyabilir. Destek görevlisi, arkadaş veya işlem aracısı olduğunu söyleyen biri dahi bu kodları istememelidir.',
'Bir kodu yanlışlıkla paylaştıysanız hemen ilgili hesabın parolasını değiştirin, aktif oturumları kontrol edin ve resmî destek kanalından güvenlik kaydı oluşturun. Size ulaşan numara veya profil gerçek görünse bile yalnızca o kişinin iddiasına güvenmeyin. Resmî uygulama içinden başlatılan destek talebi, mesajla gelen yönlendirmeden daha güvenilir bir doğrulama yoludur.'
]),
starter('guvenlik-dolandiricilik','Sahte Siteler','sahte-bozum-sitelerini-anlamanin-temel-yollari','Sahte bozum sitelerini anlamanın temel yolları','Alan adı, iletişim ve yönlendirme davranışları üzerinden temel sahte site kontrolü.',[
'Sahte bozum siteleri çoğu zaman tanıdık bir markanın adını, renklerini veya logosunu taklit eder. Alan adındaki küçük yazım farkları, yalnızca sosyal medya hesabına yönlendiren iletişim bilgileri, acele ettiren geri sayımlar ve olağan dışı oranlar dikkat edilmesi gereken işaretlerdir. Site görünümü tek başına güven kanıtı değildir.',
'İşlemden önce adres çubuğundaki alan adını, sitenin yayımladığı resmî iletişim kanallarını ve güvenlik uyarılarını karşılaştırın. Arama reklamı ya da mesajdaki bağlantı yerine adresi kendiniz yazarak ulaşmayı tercih edin. Site şifre, SMS kodu veya banka erişimi talep ediyorsa sayfayı kapatın. Şüpheli ekranları saklamak, gerektiğinde bildirim yapmayı kolaylaştırır.'
]),
starter('guvenlik-dolandiricilik','WhatsApp Güvenliği','dogru-sky-bozum-whatsapp-hesabi-nasil-kontrol-edilir','Doğru Sky Bozum WhatsApp hesabı nasıl kontrol edilir?','WhatsApp üzerinden gelen yönlendirmeleri resmî iletişim bilgisiyle çapraz kontrol etme rehberi.',[
'WhatsApp üzerinden gelen bir hesabın profil fotoğrafı veya adı tek başına doğrulama sağlamaz. Doğru iletişim kanalını kontrol etmek için Sky Bozum sitesinde yayımlanan resmî bağlantı ve numarayı esas alın. Mesaj içindeki linke tıklamak yerine, siteye kendiniz girip iletişim alanından karşılaştırma yapmak daha güvenlidir.',
'Resmî görünen hesaplar da sizden şifre, SMS kodu, uygulama onayı veya banka girişi istememelidir. Acele ettiren, yüksek kazanç vaat eden veya sohbeti başka bir numaraya taşıyan mesajları dikkatle değerlendirin. Şüpheli mesajı silmeden önce ekran görüntüsü alın; ardından resmî kanaldan konuyu teyit edin. Böylece yanlış kişiye bilgi verme riski azalır.'
]),
starter('guvenlik-dolandiricilik','Şüpheli İşlem Bildirimleri','supheli-bir-teklif-veya-mesaj-aldiginizda-ne-yapmalisiniz','Şüpheli bir teklif veya mesaj aldığınızda ne yapmalısınız?','Şüpheli iletişimde ilk yapılacaklar ve kaçınılacak davranışlar.',[
'Şüpheli bir teklif veya mesaj aldığınızda ilk adım bağlantıya tıklamamak, kod paylaşmamak ve karşı tarafın istediği acil işlemi yapmamaktır. Mesajın ekran görüntüsünü, gönderici bilgisini ve varsa bağlantı adresini saklayın. Bu kayıtlar hem resmi destek hem de gerektiğinde ilgili platform bildirimi için yararlı olur.',
'Teklifin doğruluğunu mesajdaki numaradan değil, resmî web sitesinde yayımlanan iletişim kanalından kontrol edin. Hesabınızla ilgili bir risk olduğundan şüpheleniyorsanız parolanızı değiştirin ve oturumları gözden geçirin. Maddi kayıp veya hesap ele geçirme şüphesi oluştuysa zaman kaybetmeden ilgili hizmet sağlayıcısına ve gerekli resmî başvuru kanallarına kayıt bırakın.'
]),
starter('sky-bozum-destek-topluluk','Duyurular','sky-bozum-topluluk-alani-kullanim-rehberi','Sky Bozum topluluk alanı kullanım rehberi','Toplulukta doğru kategori seçimi, saygılı iletişim ve güvenli paylaşım için başlangıç rehberi.',[
'Sky Bozum topluluk alanı; mobil ödeme, dijital kod, dijital cüzdan, oran ve güvenlik konularında deneyim ve soru paylaşımı için düzenlenmiştir. Yeni konu açarken ilgili ana bölüm ve alt kategoriyi seçmek, başlığın kısa ve açık olmasına dikkat etmek diğer kullanıcıların içeriği daha kolay bulmasını sağlar. Konu içinde işlem türü ve yaşanan durum yazılabilir.',
'Kişisel veri, kod, hesap şifresi, SMS doğrulama bilgisi veya başkasına ait belge paylaşılmamalıdır. Bir sorun bildirirken tarih, hata metni ve işlem numarasının güvenli kısmı gibi doğrulanabilir bilgiler yeterli olur. Hakaret, hedef gösterme, kanıtsız suçlama veya başka kullanıcıları acele işlem yapmaya yönlendiren içerikler topluluk amacına uygun değildir.'
]),
starter('sky-bozum-destek-topluluk','Nasıl İşlem Yapılır?','ilk-kez-bozum-yapacaklar-icin-baslangic-rehberi','İlk kez bozum yapacaklar için başlangıç rehberi','İlk işlemden önce koşulları anlama ve güvenli iletişim için temel sıralama.',[
'İlk kez bozum yapacak kişiler için en sağlıklı başlangıç, hangi hizmetin kullanılacağını ve yaklaşık tutarı netleştirmektir. Ardından resmî site üzerinden güncel oran, iletişim kanalı ve gerekli adımlar kontrol edilmelidir. İşlem süresini ya da net ödemeyi yalnızca sosyal medya mesajına göre varsaymak yerine yazılı teyit almak gerekir.',
'Süreçte yalnızca gerekli bilgileri verin; parola, SMS kodu, banka giriş bilgisi veya uzaktan erişim talebi kabul edilmemelidir. Kod veya bakiye gibi geri alınması zor bilgileri paylaşmadan önce tüm koşulları okuyun. Bir noktada belirsizlik varsa işlemi durdurup resmî destek kaydı açmak, hızlı davranmaktan daha güvenli bir seçimdir.'
]),
starter('sky-bozum-destek-topluluk','Sık Sorulanlar','yeni-musterilerden-en-sik-gelen-10-soru','Yeni müşterilerden en sık gelen 10 soru','Yeni kullanıcıların karar vermeden önce en çok kontrol ettiği başlıkları bir araya getiren özet.',[
'Yeni kullanıcıların sık sorduğu konular; işlem için uygun hizmetler, güncel oran, net ödeme, olası komisyon, işlem süresi, limitler, kod geçerliliği, güvenli iletişim, bekleyen işlemler ve destek kaydıdır. Bu soruların tek bir cevabı yoktur; hizmet türü ve hesabın durumu sonucu değiştirebilir. Bu nedenle herkes için geçerli kesin sözler vermek doğru değildir.',
'En pratik yaklaşım; işlemden önce güncel koşulları kontrol etmek, net tutarı yazılı teyit etmek ve resmî kanalı kullanmaktır. Hata veya gecikme yaşanırsa işlem numarası, tarih ve ekran görüntüsüyle destek kaydı açın. Şifre, SMS doğrulama kodu ve banka giriş bilgisinin bu soruların hiçbirini çözmek için paylaşılmaması gerektiğini unutmayın.'
]),
starter('sky-bozum-destek-topluluk','Öneri & Geri Bildirim','sky-bozumda-gormek-istediginiz-ozellikleri-paylasin','Sky Bozum’da görmek istediğiniz özellikleri paylaşın','Öneri ve geri bildirim konularının daha uygulanabilir yazılması için kısa yönlendirme.',[
'Sky Bozum hakkında öneri paylaşırken hangi sayfada veya hangi adımda ihtiyaç oluştuğunu yazmak, geri bildirimi daha faydalı hale getirir. Örneğin yalnızca “siteyi geliştirin” demek yerine, hangi bilginin eksik kaldığını, hangi butonun anlaşılmadığını veya hangi işlem adımının zorlayıcı olduğunu belirtmek daha somut bir değerlendirme sağlar.',
'Geri bildirim içinde kişisel veri, işlem kodu veya başka kullanıcıların bilgisi bulunmamalıdır. Bir güvenlik sorunu ya da şüpheli iletişim söz konusuysa bunu herkese açık konu yerine resmî destek kanalına iletmek daha doğrudur. Uygulanabilir öneriler zamanla değerlendirilir; her önerinin hemen yayına alınacağı garanti edilmez.'
]),
starter('sky-bozum-destek-topluluk','Genel Sohbet','mobil-odeme-ve-dijital-bakiye-dunyasi-hakkinda-genel-sohbet','Mobil ödeme ve dijital bakiye dünyası hakkında genel sohbet','Konu dışına taşmadan deneyim ve genel sorular için topluluk alanı.',[
'Genel Sohbet alanı; mobil ödeme, dijital kodlar ve dijital cüzdanlarla ilgili genel deneyimlerin, soruların ve gündem notlarının konuşulması içindir. Belirli bir işlem hatası veya güvenlik olayı varsa ilgili alt kategori seçilmelidir; böylece konu daha kolay bulunur ve doğru bağlamda yanıtlanabilir.',
'Sohbette kişisel bilgi, kullanılabilir kod, hesap ekranı veya başka kişilerin özel verileri paylaşılmamalıdır. Kesin sonuç vaat eden, kullanıcıları acele karar vermeye zorlayan veya kanıtsız suçlama içeren mesajlar yerine, kendi deneyiminizi açık ve sakin biçimde anlatın. Bu alan destek kaydının yerine geçmez; işlemle ilgili acil veya hassas durumlarda resmî iletişim kanalı kullanılmalıdır.'
]),
];

type SecondTopicSeed={sectionSlug:string;category:string;slug:string;title:string;summary:string;scope:string;firstCheck:string;comparison:string;commonMistake:string;nextStep:string};
const secondTopic=(seed:SecondTopicSeed):ForumStarterTopic=>starter(seed.sectionSlug,seed.category,seed.slug,seed.title,seed.summary,[
`${seed.title} sorusu genellikle tek bir düğmeye basıldığında cevaplanacakmış gibi görünür; oysa doğru sonuç işlem türüne, kullanılan hesaba ve güncel koşullara bağlıdır. Bu başlık, karar vermeden önce hangi bilgilerin gerçekten önemli olduğunu ayırmak için hazırlandı. Amaç herkese aynı sonucu vaat etmek değil, yanlış varsayımlar nedeniyle oluşabilecek zaman kaybını ve güvenlik riskini azaltmaktır.`,
`${seed.scope} Bu nedenle ekranda görülen bir açıklamayı, sosyal medya mesajını veya daha önce yapılmış bir işlemi tek başına yeterli kanıt saymamak gerekir. Kullanıcı açısından en sağlıklı yol; hizmetin resmî ekranındaki bilgiyi, işlemde kullanılan ürünün kendi koşullarını ve yazılı olarak bildirilen detayları birlikte değerlendirmektir.`,
`İlk kontrol noktası şudur: ${seed.firstCheck} Bu bilgi net değilken kod, hesap bilgisi veya onay paylaşmak yerine süreci durdurmak daha doğrudur. Özellikle ürünün bölgesi, para birimi, hattın ya da cüzdanın durumu ve ekranda görünen toplam tutar birbirinden bağımsız değişkenlerdir. Her birini ayrı ayrı kontrol etmek, sonradan “böyle olduğunu bilmiyordum” denilen sorunları azaltır.`,
`${seed.comparison} Karşılaştırma yaparken yalnızca öne çıkan yüzdeye, kampanya ifadesine veya hızlı sonuç vaadine bakmayın. Aynı başlık altında görünen iki seçeneğin teslim yöntemi, doğrulama ihtiyacı veya kullanılabilirlik şartı farklı olabilir. Net olmayan bir koşul varsa bunu işlem başlamadan önce yazılı biçimde sormak, kullanıcı açısından en iyi korumadır.`,
`Sık yapılan hata ise ${seed.commonMistake} Bu yaklaşım hem hesap güvenliğini hem de sonradan destek alabilme imkanını zayıflatır. Parola, SMS ile gelen tek kullanımlık kod, uygulama onayı, kart güvenlik bilgisi ve uzaktan erişim talebi normal bir destek adımı değildir. Böyle bir istek geldiğinde resmî uygulama veya web sitesi üzerinden yeni bir destek kaydı açın.`,
`Konu içinde yardım istenirken tarih, kullanılan ürün türü, hata metni ve işlem numarasının kişisel veri içermeyen kısmı paylaşılabilir. Tam kodu, hesap ekranını, kimlik belgesini veya başka bir kişiye ait bilgiyi herkese açık alana koymayın. Bu hem konunun doğru yanıtlanmasını kolaylaştırır hem de aynı sorunu yaşayan kişilerin güvenli bir örnek görmesini sağlar.`,
`Bu konuda ilerlerken önerilen sonraki adım: ${seed.nextStep} Toplulukta yeni bir soru açacaksanız başlığı bu ayrımı yansıtacak şekilde kurun; örneğin “neden olmadı?” demek yerine hangi hizmette, hangi aşamada ve hangi hata metniyle karşılaştığınızı yazın. Böylece konu hem kullanıcılar için bulunabilir olur hem de aynı aramayı yapan kişiye gerçek bir cevap sunar.`,
`Özetle, ${seed.title.toLocaleLowerCase('tr-TR')} için en değerli bilgi hızlı bir vaat değil; koşulları doğrulayabildiğiniz, güvenlik sınırlarını koruduğunuz ve yazılı kayıtla ilerleyebildiğiniz bilgidir. Bu sayfadaki ilgili rehberler, konuyu tek bir cümleye sıkıştırmak yerine farklı ihtimalleri adım adım değerlendirmenize yardımcı olur.`
]);

const forumSecondTopicSeeds:SecondTopicSeed[]=[
{sectionSlug:'mobil-odeme-operatorler',category:'Mobil Ödeme Genel',slug:'mobil-odeme-ile-dijital-kod-almadan-once-kontrol-listesi',title:'Mobil ödeme ile dijital kod almadan önce kontrol listesi',summary:'Mobil ödeme ekranına geçmeden önce kontrol edilmesi gereken hizmet, tutar, limit ve güvenlik adımları.',scope:'Mobil ödeme, uygun harcamaların telefon faturası veya hat bakiyesi üzerinden tahsil edilmesine dayanır; her ürün ve her hesap için aynı şekilde çalışmaz.',firstCheck:'Kullanacağınız mağazanın, ürünün ve tahsilat yönteminin açıkça yazdığından emin olun.',comparison:'Telefon hattı üzerinden tahsilat ile dijital cüzdan bakiyesi üzerinden ödeme aynı kaynak değildir; hangi kaynaktan çekim yapılacağını ödeme ekranında görün.',commonMistake:'sadece mesajla gelen bağlantıya güvenip ürün koşullarını ve toplam tutarı okumadan ilerlemektir.',nextStep:'Mobil ödeme rehberinden genel akışı, ardından kullandığınız operatörün ilgili sayfasını inceleyin.'},
{sectionSlug:'mobil-odeme-operatorler',category:'Turkcell',slug:'turkcell-mobil-odeme-limiti-ve-dijital-kod-secimi',title:'Turkcell mobil ödeme limiti ve dijital kod seçimi',summary:'Turkcell hattıyla dijital ürün seçerken limit, ürün koşulu ve güvenlik kontrolünü birlikte değerlendirme rehberi.',scope:'Turkcell mobil ödeme limiti, hat kullanımı ve güncel hizmet koşullarına göre değişebileceği için geçmişte çalışan bir işlem bugün aynı sonucu vermeyebilir.',firstCheck:'Limit ekranını ve faturaya yansıyabilecek harcama bilgisini kendi Turkcell hesabınızdan kontrol edin.',comparison:'Razer Gold, Apple Gift Card veya başka dijital ürünler aynı satın alma akışına sahip değildir; ürünün bölge ve kullanım koşulunu ayrıca okuyun.',commonMistake:'başka bir kullanıcının limitini kendi hattı için garanti kabul etmektir.',nextStep:'Turkcell rehberinden temel koşulları, Paycell kullanıyorsanız cüzdan rehberini de karşılaştırın.'},
{sectionSlug:'mobil-odeme-operatorler',category:'Vodafone',slug:'vodafone-mobil-odeme-ile-razer-gold-ve-apple-kodu-alma',title:'Vodafone mobil ödeme ile Razer Gold ve Apple kodu alma',summary:'Vodafone mobil ödeme ile dijital ürün seçerken dikkat edilmesi gereken ürün, tutar ve resmî kanal kontrolleri.',scope:'Vodafone mobil ödeme, uygun dijital alışverişlerde tahsilat aracıdır; her kod türünün bölge, stok ve teslim koşulu farklı olabilir.',firstCheck:'Ödeme sayfasındaki ürün adını, toplam tutarı ve faturaya yansıma bilgisini aynı anda kontrol edin.',comparison:'Razer Gold kodu ile Apple hediye kartı farklı hesap ve bölge şartlarına bağlıdır; biri için uygun olan bilgi diğerine taşınamaz.',commonMistake:'“limit yükseltme” vaadiyle gelen resmî olmayan yönlendirmeleri gerçek destek sanmaktır.',nextStep:'Vodafone dijital ürün rehberini okuyun; seçtiğiniz kod türü için Razer Gold veya Apple rehberine geçin.'},
{sectionSlug:'mobil-odeme-operatorler',category:'Türk Telekom',slug:'turk-telekom-mobil-odeme-hatasi-oldugunda-ne-kontrol-edilir',title:'Türk Telekom mobil ödeme hatası olduğunda ne kontrol edilir?',summary:'Türk Telekom mobil ödeme hatasında rastgele tekrar denemek yerine izlenebilecek düzenli kontrol sırası.',scope:'Türk Telekom mobil ödemede görülen hata; limit, fatura durumu, hizmet sağlayıcı koşulu veya geçici teknik kontrollerden kaynaklanabilir.',firstCheck:'Hata metnini, zamanı ve işlem yapılan hizmeti not ederek kendi hesap ekranınızdaki limit ve kısıtları inceleyin.',comparison:'Hat kaynaklı bir kısıtlama ile ürünün bölge veya stok sorunu farklı destek kanallarında çözülür; ikisini aynı hata sanmayın.',commonMistake:'aynı işlemi arka arkaya deneyerek çift kayıt veya daha fazla karışıklık oluşturmaktır.',nextStep:'Türk Telekom rehberini ve hata devam ediyorsa sorun çözme merkezindeki ilgili kontrol listesini kullanın.'},
{sectionSlug:'mobil-odeme-operatorler',category:'Mobil Ödeme Limit & Sorunları',slug:'mobil-odeme-limiti-varken-islem-neden-reddedilir',title:'Mobil ödeme limiti varken işlem neden reddedilir?',summary:'Limit görünmesine rağmen mobil ödemenin reddedilmesine yol açabilen temel kontrol noktaları.',scope:'Görünen limit, her işlem türünde kullanılabilecek kesin bir izin değildir; ödeme sağlayıcısının ve ilgili mağazanın ek kontrolleri olabilir.',firstCheck:'Hatanın hangi adımda çıktığını ayırın: ödeme seçimi, operatör onayı, ürün teslimi veya uygulama doğrulaması.',comparison:'Limit sorunu ile ödenmemiş fatura, hat kısıtı veya ürünün kendi bölge koşulu farklı nedenlerdir ve farklı kayıtlarla doğrulanır.',commonMistake:'ret mesajını görür görmez üçüncü taraflardan “engel kaldırma” desteği aramaktır.',nextStep:'Mobil ödeme temel rehberini okuyup kendi operatörünüzün hata ve limit sayfasına geçin.'},
{sectionSlug:'dijital-kod-hediye-kartlari',category:'Razer Gold TL',slug:'razer-gold-tl-kodu-alirken-bolge-ve-kullanilmis-kod-kontrolu',title:'Razer Gold TL kodu alırken bölge ve kullanılmış kod kontrolü',summary:'Razer Gold TL kodu seçerken değer, bölge, kullanılmamış olma ve kayıt saklama adımları.',scope:'Razer Gold TL kodu, yalnızca üzerindeki tutarla değil, kullanım koşulu ve kodun daha önce kullanılıp kullanılmadığıyla da değerlendirilir.',firstCheck:'Kodun TL olduğundan, ürün sayfasındaki açıklamayla eşleştiğinden ve satın alma belgesinin saklandığından emin olun.',comparison:'TL ve USD kodları veya farklı bölgelere yönelik kartlar aynı ürün değildir; tutar benzer olsa bile kullanım sonucu değişebilir.',commonMistake:'kodu teslim etmeden önce ürünün hesabında kullanılabilir olup olmadığını kontrol etmemektir.',nextStep:'Razer Gold nedir rehberinden temel kavramları, ardından Razer Gold kodu rehberinden teslim öncesi adımları inceleyin.'},
{sectionSlug:'dijital-kod-hediye-kartlari',category:'Razer Gold USD',slug:'razer-gold-usd-kodu-hangi-hesaplarda-kullanilabilir',title:'Razer Gold USD kodu hangi hesaplarda kullanılabilir?',summary:'Razer Gold USD kodlarında para birimi, bölge ve hesap uyumunu anlamaya yardımcı rehber.',scope:'USD ibaresi yalnızca fiyat biçimini değil, bazı durumlarda hesabın bölgesine veya ürünün tanımlandığı mağazaya ilişkin koşulları da gösterir.',firstCheck:'Kullanacağınız hesabın ülke ayarını ve kodun satıldığı ürün sayfasındaki bölge bilgisini karşılaştırın.',comparison:'TL kodunu USD koda dönüştürmek veya iki kodu aynı kullanım alanına sahip saymak doğru değildir; her biri kendi açıklamasına göre değerlendirilir.',commonMistake:'kod adında Razer Gold geçtiği için tüm hesaplarda çalışacağını varsaymaktır.',nextStep:'Razer Gold TL/USD farkları konusunu ve dijital kod rehberindeki bölge kontrol bölümünü birlikte okuyun.'},
{sectionSlug:'dijital-kod-hediye-kartlari',category:'Apple / iTunes',slug:'apple-hediye-karti-alirken-ulke-ve-hesap-bolgesi-kontrolu',title:'Apple hediye kartı alırken ülke ve hesap bölgesi kontrolü',summary:'Apple Gift Card seçerken ülke, hesap bölgesi ve teslim sonrası kontrolün neden önemli olduğu.',scope:'Apple hediye kartlarında ürünün satıldığı ülke ile Apple hesabının bölgesi arasındaki uyum, kod tutarından önce kontrol edilmesi gereken bir konudur.',firstCheck:'Apple hesabınızın ülke/bölge ayarını ve satın alınacak kartın açıkça yazan kullanım bölgesini kontrol edin.',comparison:'App Store bakiyesi, hediye kartı ve farklı ülkelere yönelik Apple kodları aynı kullanım koşullarına sahip değildir.',commonMistake:'kart görselindeki Apple logosunu uyumluluk kanıtı sayıp ülke bilgisini atlamaktır.',nextStep:'Apple Gift Card rehberindeki bölge ve kullanım bölümlerini inceleyin; hatada resmî Apple destek kaydıyla ilerleyin.'},
{sectionSlug:'dijital-kod-hediye-kartlari',category:'Steam',slug:'steam-cuzdan-kodu-alirken-ulke-ayari-nasil-kontrol-edilir',title:'Steam cüzdan kodu alırken ülke ayarı nasıl kontrol edilir?',summary:'Steam cüzdan kodu için ülke ayarı, para birimi ve ürün açıklaması kontrolünün önemi.',scope:'Steam cüzdan kodları hesabın mağaza ülkesi ve para birimiyle bağlantılı olabileceği için, kod adı tek başına kullanım garantisi vermez.',firstCheck:'Steam hesabınızdaki mağaza ülkesini ve ürün sayfasındaki para birimi/bölge notunu karşılaştırın.',comparison:'Steam Wallet ile oyun anahtarı aynı tür dijital ürün değildir; teslim ve kullanım koşulları ayrıca değerlendirilir.',commonMistake:'hesabın geçmişteki bir satın almasına bakarak mevcut ülke ayarını doğrulamadan kod almaktır.',nextStep:'Dijital kod rehberini ve Steam kodu kullanılmıyor sorun çözme sayfasını inceleyin.'},
{sectionSlug:'dijital-kod-hediye-kartlari',category:'Kod Sorunları',slug:'dijital-kod-hatasi-icin-saticiya-hangi-bilgiler-verilmeli',title:'Dijital kod hatası için satıcıya hangi bilgiler verilmeli?',summary:'Geçersiz veya kullanılmış görünen dijital kodda güvenli destek kaydı oluşturma rehberi.',scope:'Dijital kod hatasında doğru kayıt; kodu herkese açık biçimde paylaşmak değil, ürün türü ve hata bilgisini güvenli biçimde belgelemektir.',firstCheck:'Satın alma belgesi, hata metni, işlem tarihi ve kodun yalnızca gerekli son karakterleri gibi güvenli kayıtları hazırlayın.',comparison:'Geçersiz kod, daha önce kullanılmış kod ve bölge uyuşmazlığı aynı hata gibi görünse de çözüm yolu farklı olabilir.',commonMistake:'çözüm ararken kullanılabilir kodun tamamını toplulukta veya tanımadığınız kişilere göndermektir.',nextStep:'Kod sorunları rehberini okuyun; ürüne göre Razer, Apple veya Steam sorun çözme sayfasına geçin.'},
{sectionSlug:'dijital-cuzdanlar',category:'Paycell',slug:'paycell-ile-dijital-urun-alirken-limit-ve-kart-kontrolu',title:'Paycell ile dijital ürün alırken limit ve kart kontrolü',summary:'Paycell üzerinden dijital ürün seçerken kart, limit, mağaza ve güvenlik kontrolünün temel adımları.',scope:'Paycell hesabındaki bakiye, kart durumu ve online alışveriş ayarları her işlemin otomatik olarak gerçekleşeceği anlamına gelmez.',firstCheck:'Paycell uygulamasında kartın online kullanıma açık olup olmadığını, limiti ve işlem geçmişini kontrol edin.',comparison:'Paycell kartı ile Turkcell mobil ödeme farklı tahsilat yöntemleridir; birinde çalışan işlem diğerinde aynı şekilde çalışmayabilir.',commonMistake:'uygulama dışından gelen ödeme bağlantısında hesap bilgisi girmektir.',nextStep:'Paycell rehberini, Turkcell kullanıyorsanız Turkcell mobil ödeme sayfasını ve cüzdan güvenliği rehberini inceleyin.'},
{sectionSlug:'dijital-cuzdanlar',category:'Pokus',slug:'pokus-karti-ile-dijital-urun-almadan-once-neye-bakilir',title:'Pokus kartı ile dijital ürün almadan önce neye bakılır?',summary:'Pokus kartla dijital ürün seçerken bakiye, limit, mağaza ve işlem kaydı kontrolü.',scope:'Pokus ile yapılan bir dijital alışverişte uygulama içi kart ayarları, yeterli bakiye ve ürünün kendi ödeme koşulu birlikte etkili olur.',firstCheck:'Kartın aktifliğini, online alışveriş ayarını, güncel bakiyeyi ve mağazanın kabul ettiği ödeme türünü kontrol edin.',comparison:'Pokus bakiyesi ile Türk Telekom hattına yansıyan mobil ödeme farklı kaynaklardır; destek ve itiraz akışları da ayrıdır.',commonMistake:'bekleyen işlem varken aynı ürünü yeniden satın almaya çalışmaktır.',nextStep:'Pokus rehberini okuyun; Türk Telekom ile ilgili bir ödeme varsa operatör rehberinden koşulları ayrıca kontrol edin.'},
{sectionSlug:'dijital-cuzdanlar',category:'Vodafone Pay',slug:'vodafone-pay-ve-mobil-odeme-arasinda-dogru-secim-nasil-yapilir',title:'Vodafone Pay ve mobil ödeme arasında doğru seçim nasıl yapılır?',summary:'Vodafone Pay ile mobil ödeme arasındaki ödeme kaynağı ve destek süreci farklarını anlamaya yardımcı konu.',scope:'Vodafone Pay cüzdan işlemleri ile Vodafone hattına yansıyan mobil ödeme, aynı markanın adı geçse bile farklı hesap ve tahsilat yapılarıdır.',firstCheck:'Ödeme ekranında tutarın Vodafone Pay bakiyesinden mi yoksa telefon faturası/hat bakiyesinden mi çekileceğini kontrol edin.',comparison:'Cüzdan işlemindeki bekleme veya iade kaydı, mobil ödeme itiraz süreciyle aynı kanaldan takip edilmeyebilir.',commonMistake:'iki yöntemi birbirinin limitiyle veya aynı destek kaydıyla çözülecek sanmaktır.',nextStep:'Vodafone Pay farkları rehberini ve Vodafone dijital ürün rehberini karşılaştırarak ilerleyin.'},
{sectionSlug:'dijital-cuzdanlar',category:'Dijital Cüzdan Limitleri',slug:'dijital-cuzdan-limitleri-neden-herkeste-farkli-gorunur',title:'Dijital cüzdan limitleri neden herkeste farklı görünür?',summary:'Dijital cüzdan limitlerini etkileyen doğrulama, işlem türü ve dönemsel kontrol mantığı.',scope:'Dijital cüzdan limitleri yalnızca kullanıcı bakiyesine göre değil, doğrulama seviyesi, işlem tipi ve hizmet sağlayıcının güncel risk kurallarına göre şekillenir.',firstCheck:'Uygulamanın kendi limit ekranındaki güncel tanımı ve hesap doğrulama durumunu kontrol edin.',comparison:'Başka bir kullanıcının ekran görüntüsü, sizin hesabınız için geçerli limit veya izin anlamına gelmez.',commonMistake:'limit görünen bir hesapta her ürünün ve her tutarın onaylanacağını varsaymaktır.',nextStep:'Dijital cüzdan rehberini inceleyin; işlem hatası varsa ilgili Paycell veya Pokus sorun çözme sayfasına geçin.'},
{sectionSlug:'dijital-cuzdanlar',category:'Dijital Cüzdan Sorunları',slug:'dijital-cuzdan-bekleyen-islemde-para-iki-kez-cekilir-mi',title:'Dijital cüzdan bekleyen işlemde para iki kez çekilir mi?',summary:'Bekleyen dijital cüzdan işleminde tekrar denemeden önce yapılması gereken güvenli kontroller.',scope:'Bekleyen işlem kaydı, paranın kesin olarak iki kez çekildiği veya işlemin başarısız olduğu anlamına gelmez; uygulama ve karşı taraf kayıtları birlikte incelenmelidir.',firstCheck:'İşlem geçmişindeki saat, tutar, durum etiketi ve varsa işlem numarasını not edin.',comparison:'Kart provizyonu, tamamlanmış ödeme ve bekleyen cüzdan kaydı farklı durum etiketleridir; aynı satır gibi yorumlanmamalıdır.',commonMistake:'ekranda sonuç görünmediği için aynı ödemeyi birkaç kez tekrar etmektir.',nextStep:'İlgili cüzdanın resmî yardım kanalını kullanın; Paycell veya Pokus hata rehberinden durum etiketlerini kontrol edin.'},
{sectionSlug:'bozum-oranlar',category:'Güncel Oranlar',slug:'guncel-bozum-orani-nasil-karsilastirilir',title:'Güncel bozum oranı nasıl karşılaştırılır?',summary:'Oran karşılaştırırken net tutar, koşul ve güncellik bilgisini birlikte okuma rehberi.',scope:'Güncel oran; hizmet türü, ürün değeri, kullanılabilirlik ve kontrol ihtiyacına göre değişebilen bir karşılaştırma bilgisidir.',firstCheck:'Yüzdenin yanında net ödeme, varsa kesinti ve teklifin hangi ürün için geçerli olduğunun yazılı olmasını isteyin.',comparison:'Aynı yüzde iki farklı ürün için aynı net sonucu doğurmayabilir; para birimi, tutar ve ek şartlar sonucu değiştirir.',commonMistake:'oranı tek başına “en iyi teklif” olarak kabul edip net sonucu sormamaktır.',nextStep:'Güncel oran rehberini ve oran hesaplama konusunu birlikte inceleyin.'},
{sectionSlug:'bozum-oranlar',category:'Oran Hesaplama',slug:'net-odeme-hesaplarken-hangi-kesintiler-kontrol-edilir',title:'Net ödeme hesaplarken hangi kesintiler kontrol edilir?',summary:'Brüt tutar, oran, komisyon ve net sonuç arasındaki farkı sade biçimde açıklayan konu.',scope:'Bir oran hesabında başlangıç tutarı ile elinize geçmesi beklenen net tutarı ayırmak gerekir; aynı kelimeler farklı ekranlarda farklı anlamda kullanılabilir.',firstCheck:'Hesaba girdiğiniz tutarın ürün değeri mi, bakiye mi, yoksa tahmini ödeme mi olduğunu kontrol edin.',comparison:'Oran ve komisyon birbirinin yerine kullanılmamalıdır; bazı süreçlerde net sonuç doğrudan belirtilirken bazı süreçlerde ayrıca kesinti olabilir.',commonMistake:'hesap makinesi sonucunu kesin teklif veya ödeme taahhüdü sanmaktır.',nextStep:'Oran hesaplama aracını bilgi amaçlı kullanın; işlem öncesinde güncel net sonucu yazılı olarak teyit edin.'},
{sectionSlug:'bozum-oranlar',category:'Komisyonlar',slug:'komisyonsuz-ifadesi-net-odeme-icin-ne-anlama-gelir',title:'Komisyonsuz ifadesi net ödeme için ne anlama gelir?',summary:'Komisyon, oran ve net ödeme kavramlarını karşılaştırırken dikkat edilmesi gereken noktalar.',scope:'“Komisyonsuz” ifadesi tek başına en yüksek net ödeme anlamına gelmez; oran, ürün koşulu ve olası transfer masrafı birlikte değerlendirilir.',firstCheck:'Teklifteki toplam ürün değeri, oran ve size aktarılacak net tutarın ayrı ayrı yazıldığını kontrol edin.',comparison:'Komisyonun olmaması ile oran farkının olmaması aynı şey değildir; net ödeme bu iki bilginin yanında işlem şartlarından da etkilenebilir.',commonMistake:'yalnızca tek bir pazarlama ifadesine bakarak farklı teklifleri karşılaştırmaktır.',nextStep:'Komisyon ve oran farkı konusunu, ardından güncel oran rehberini okuyun.'},
{sectionSlug:'bozum-oranlar',category:'Ödeme Süresi',slug:'odeme-suresi-uzarsa-hangi-kayitlar-saklanmali',title:'Ödeme süresi uzarsa hangi kayıtlar saklanmalı?',summary:'Beklenen sürenin aşılması halinde güvenli destek kaydı için tutulması gereken bilgiler.',scope:'Ödeme süresi; ürün kontrolü, işlem yoğunluğu, bankacılık saatleri ve doğrulama ihtiyacı gibi değişkenlerden etkilenebilir.',firstCheck:'İşlem numarası, yazılı olarak bildirilen süre, tarih-saat ve net tutar bilgisini aynı yerde saklayın.',comparison:'Tahmini süre ile garanti edilen süre aynı ifade değildir; hangi aşamada bilgilendirme yapılacağı önceden net olmalıdır.',commonMistake:'süre uzadığında güvenlik için yasak olan kod veya şifre bilgisini hızlandırma amacıyla paylaşmaktır.',nextStep:'Ödeme süresi konusunu inceleyin; gerektiğinde resmî iletişim kanalından işlem numarasıyla kayıt açın.'},
{sectionSlug:'bozum-oranlar',category:'Yüksek Oran Uyarıları',slug:'cok-yuksek-oran-teklifinde-hangi-sorular-sorulmali',title:'Çok yüksek oran teklifinde hangi sorular sorulmalı?',summary:'Olağan dışı yüksek oran teklifini güvenlik ve net koşul açısından değerlendirme rehberi.',scope:'Yüksek oran teklifi bazen ürün, tutar veya dönemsel koşulla açıklanabilir; ancak açıklanmayan fark, tek başına risk işareti sayılmalıdır.',firstCheck:'Teklifin hangi ürün için geçerli olduğunu, net ödeme tutarını, kesintiyi ve doğrulama koşulunu yazılı olarak sorun.',comparison:'Görünen en yüksek yüzde ile gerçekte en iyi net sonuç aynı olmayabilir; ödeme süresi ve ek şartlar karşılaştırmaya dahildir.',commonMistake:'acele ettiren mesajın etkisiyle resmî kanalı kontrol etmeden kod paylaşmaktır.',nextStep:'Güvenilir site seçimi rehberini ve şüpheli tekliflerde yapılacaklar konusunu okuyun.'},
{sectionSlug:'guvenlik-dolandiricilik',category:'Güvenli İşlem',slug:'guvenli-islem-icin-yazili-teyit-neden-onemlidir',title:'Güvenli işlem için yazılı teyit neden önemlidir?',summary:'İşlem türü, net tutar ve koşulların yazılı teyit edilmesinin kullanıcıya sağladığı koruma.',scope:'Yazılı teyit, belirsiz bir konuşmayı kayıt altına alınmış bir işleme dönüştürür; ancak hesap erişimi verecek bilgi paylaşımı anlamına gelmez.',firstCheck:'Ürün türü, toplam tutar, net sonuç, koşul ve resmî iletişim bilgisinin aynı yazışmada yer aldığını kontrol edin.',comparison:'Yazılı bilgi, şifre veya SMS kodu talebinden tamamen farklıdır; ilki şeffaflık sağlar, ikincisi hesap güvenliğini riske atar.',commonMistake:'yalnızca telefon veya sohbet üzerinden söylenen söze güvenip koşulları saklamamaktır.',nextStep:'Güvenli işlem rehberini ve güvenilir mobil bozum sitesi seçimi yazısını inceleyin.'},
{sectionSlug:'guvenlik-dolandiricilik',category:'Paylaşılmaması Gereken Bilgiler',slug:'tek-kullanimlik-kod-paylasildiysa-ilk-ne-yapilmali',title:'Tek kullanımlık kod paylaşıldıysa ilk ne yapılmalı?',summary:'SMS doğrulama kodu veya parola paylaşıldığında zaman kaybetmeden uygulanacak hesap güvenliği adımları.',scope:'Tek kullanımlık kod, hesaba giriş veya işlem onayı için kullanılabilir; bu nedenle paylaşılması durumunda hızlı fakat kontrollü davranmak gerekir.',firstCheck:'İlgili hesabın parolasını resmî uygulama veya site üzerinden değiştirin ve açık oturumları kontrol edin.',comparison:'SMS kodu, müşteri numarası veya işlem açıklaması gibi genel bilgi değildir; hesabın kontrolünü etkileyebilecek bir güvenlik aracıdır.',commonMistake:'kodu alan kişi “destek” olduğunu söylediği için hiçbir işlem yapmadan beklemektir.',nextStep:'SMS kodu güvenliği konusunu, ardından şüpheli işlem bildirimi rehberini okuyun.'},
{sectionSlug:'guvenlik-dolandiricilik',category:'Sahte Siteler',slug:'sahte-site-adresi-nasil-karsilastirilir',title:'Sahte site adresi nasıl karşılaştırılır?',summary:'Benzer alan adı, kopya logo ve mesaj bağlantılarına karşı adres çubuğu üzerinden doğrulama rehberi.',scope:'Sahte sayfalar tanıdık renkler ve logolar kullanabilir; görünüm değil, alan adı ve resmî kanaldan doğrulama güvenlik için belirleyicidir.',firstCheck:'Adres çubuğundaki alan adını karakter karakter kontrol edin ve siteye mesajdaki bağlantıdan değil, kendi yazdığınız adresle ulaşın.',comparison:'Sosyal medya profil adı, ekran görüntüsü veya reklam bağlantısı bir alan adının gerçekliğini tek başına doğrulamaz.',commonMistake:'site tasarımı tanıdık göründüğü için iletişim bilgisini ve yönlendirilen adresi kontrol etmemektir.',nextStep:'Sahte site rehberini ve resmî WhatsApp hesabını doğrulama konusunu birlikte inceleyin.'},
{sectionSlug:'guvenlik-dolandiricilik',category:'WhatsApp Güvenliği',slug:'whatsapp-uzerinden-gelen-islem-teklifi-nasil-dogrulanir',title:'WhatsApp üzerinden gelen işlem teklifi nasıl doğrulanır?',summary:'WhatsApp mesajındaki teklif, profil ve bağlantıyı resmî kanal üzerinden karşılaştırma rehberi.',scope:'WhatsApp profil fotoğrafı, işletme adı veya mavi benzeri işaretler tek başına yeterli doğrulama yöntemi değildir.',firstCheck:'Numarayı site üzerindeki resmî iletişim bilgisiyle karşılaştırın ve mesajdaki bağlantıyı açmadan önce alan adını kontrol edin.',comparison:'Sohbetteki hızlı yanıt ile resmî bir işlem kaydı aynı değildir; kritik bilgiler yazılı koşul ve resmî kanalla teyit edilmelidir.',commonMistake:'profil adını markayla aynı gördüğü için parola veya SMS kodu paylaşmaktır.',nextStep:'WhatsApp güvenliği konusunu ve şüpheli mesaj bildirimi rehberini okuyun.'},
{sectionSlug:'guvenlik-dolandiricilik',category:'Şüpheli İşlem Bildirimleri',slug:'supheli-mesajda-ekran-goruntusu-ve-kayit-nasil-tutulur',title:'Şüpheli mesajda ekran görüntüsü ve kayıt nasıl tutulur?',summary:'Şüpheli teklif veya bağlantıda güvenli biçimde kanıt saklama ve doğru kanala bildirim yapma rehberi.',scope:'Şüpheli mesajlarda ilk hedef tartışmayı kazanmak değil, hesabı ve kanıtları koruyarak doğru destek kanalına ulaşmaktır.',firstCheck:'Gönderici numarası, tarih-saat, bağlantı adresi ve mesaj metninin ekran görüntüsünü kaydedin; linke tıklamayın.',comparison:'Kanıt saklamak, hassas veriyi yaymak değildir; kod, parola veya kimlik bilgisini ekran görüntüsünde görünür bırakmayın.',commonMistake:'mesajı hemen silip sonradan hangi hesabın ne istediğini hatırlamaya çalışmaktır.',nextStep:'Şüpheli işlem rehberini okuyun; hesap erişimi riski varsa ilgili hizmetin resmî destek kaydını açın.'},
{sectionSlug:'sky-bozum-destek-topluluk',category:'Duyurular',slug:'forum-duyurularini-takip-ederken-nasil-dogrulama-yapilir',title:'Forum duyurularını takip ederken nasıl doğrulama yapılır?',summary:'Topluluk duyurularında güncellik, resmî kaynak ve yorum ayrımını koruma rehberi.',scope:'Duyuru içerikleri bilgi vermek içindir; yorumlarda yer alan bireysel deneyimler veya eski ekran görüntüleri güncel resmî koşulların yerine geçmez.',firstCheck:'Duyurunun tarihini, yayımlayan hesabı ve yönlendirdiği resmî sayfayı birlikte kontrol edin.',comparison:'Forum mesajı ile yönetim tarafından yayımlanan güncel açıklama aynı ağırlıkta değildir; eski başlıklar yeni koşulu yansıtmayabilir.',commonMistake:'güncelleme tarihini görmeden eski bir duyuruyu geçerli kural olarak paylaşmaktır.',nextStep:'Topluluk kullanım rehberini inceleyin; işlem koşulu için ilgili hizmet veya bilgi merkezi sayfasına geçin.'},
{sectionSlug:'sky-bozum-destek-topluluk',category:'Nasıl İşlem Yapılır?',slug:'ilk-kez-dijital-kod-alacaklar-icin-guvenli-baslangic',title:'İlk kez dijital kod alacaklar için güvenli başlangıç',summary:'İlk dijital kod alışverişinde ürün seçimi, bölge kontrolü ve güvenli kayıt tutma adımları.',scope:'İlk kez dijital kod alırken en önemli konu hızlı karar vermek değil, ürünün nerede ve hangi hesapta kullanılacağını anlamaktır.',firstCheck:'Kod türünü, para birimini, bölge bilgisini ve hesabınızın ayarını ödeme ekranından önce kontrol edin.',comparison:'Mobil ödeme, dijital cüzdan ve kart ile satın alma farklı tahsilat yollarıdır; seçtiğiniz ürünün teslim koşulu bunlardan bağımsız olabilir.',commonMistake:'kodu kullanmadan önce ürün sayfasını ve satın alma kaydını saklamamaktır.',nextStep:'Dijital kod rehberinden başlayın; seçtiğiniz ürün için Razer Gold, Apple veya Steam sayfasına geçin.'},
{sectionSlug:'sky-bozum-destek-topluluk',category:'Sık Sorulanlar',slug:'islem-oncesi-en-cok-sorulan-5-kontrol-sorusu',title:'İşlem öncesi en çok sorulan 5 kontrol sorusu',summary:'Kullanıcıların işlemden önce sorması gereken tutar, koşul, süre, güvenlik ve destek sorularını bir araya getiren konu.',scope:'Bir sorunun cevabı ürün ve hesap durumuna göre değişse de doğru sorular sorulduğunda yanlış yönlendirme riski ciddi biçimde azalır.',firstCheck:'Önce ürün türünü, kullanım bölgesini, toplam tutarı, net sonucu ve geçerli koşulu aynı yazışmada netleştirin.',comparison:'Hız, oran ve uygunluk birbirinden farklı kriterlerdir; biri iyi görünüyor diye diğerlerini doğrulamayı atlamayın.',commonMistake:'yalnız “kaç dakika sürer?” sorusuna odaklanıp ürün ve güvenlik koşullarını sormamaktır.',nextStep:'Sık sorulanlar sayfasını, oran rehberini ve güvenli işlem kontrol listesini birlikte kullanın.'},
{sectionSlug:'sky-bozum-destek-topluluk',category:'Öneri & Geri Bildirim',slug:'forumda-uygulanabilir-geri-bildirim-nasil-yazilir',title:'Forumda uygulanabilir geri bildirim nasıl yazılır?',summary:'Site ve süreç geliştirmeye yardımcı olan, somut ve güvenli geri bildirim yazma rehberi.',scope:'İyi geri bildirim yalnızca memnuniyet veya memnuniyetsizlik belirtmez; hangi sayfada, hangi adımda ve hangi bilginin eksik kaldığını gösterir.',firstCheck:'Sorunu tekrar edebilecek kişinin anlayacağı şekilde sayfa adı, işlem adımı ve görünen hata metnini kişisel veri olmadan yazın.',comparison:'Öneri konusu ile acil güvenlik/hesap sorunu farklıdır; hassas vakalar herkese açık alanda değil resmî destek kanalında bildirilmelidir.',commonMistake:'tam kod, telefon, kimlik veya başka kullanıcı bilgisi paylaşarak geri bildirim vermeye çalışmaktır.',nextStep:'Topluluk kullanım rehberini okuyun ve önerinizi doğru kategori ile kısa, açıklayıcı başlıkla yayınlayın.'},
{sectionSlug:'sky-bozum-destek-topluluk',category:'Genel Sohbet',slug:'dijital-kod-ve-mobil-odeme-deneyimi-paylasirken-kurallar',title:'Dijital kod ve mobil ödeme deneyimi paylaşırken kurallar',summary:'Genel sohbette deneyim paylaşırken doğrulanabilir bilgi, güvenlik ve saygılı iletişim ilkeleri.',scope:'Genel sohbet, bilgi alışverişi için yararlıdır; ancak kişisel deneyim bir hizmetin herkes için aynı sonucu vereceği anlamına gelmez.',firstCheck:'Paylaşımınızda kullandığınız ürün türünü, genel koşulu ve varsa hata mesajını kişisel bilgi içermeden belirtin.',comparison:'Genel deneyim ile kesin teknik veya finansal öneri farklıdır; kanıtlayamadığınız iddiaları kesin bilgi gibi sunmayın.',commonMistake:'kendi yaşadığı tek olayı tüm kullanıcılar için değişmez kural olarak anlatmaktır.',nextStep:'Belirli bir hata varsa ilgili mobil ödeme, dijital kod veya cüzdan kategorisinde ayrı konu açın.'}
];

export const forumSecondTopics=forumSecondTopicSeeds.map(secondTopic);
export const forumStarterTopics:ForumStarterTopic[]=[...forumInitialTopics,...forumSecondTopics];

export const publicForumKeys=forumStarterTopics.map(topic=>`${topic.sectionSlug}/${topic.categorySlug}`);
export const getForumStarterTopic=(sectionSlug:string,categorySlug:string,topicSlug?:string)=>forumStarterTopics.find(topic=>topic.sectionSlug===sectionSlug&&topic.categorySlug===categorySlug&&(!topicSlug||topic.slug===topicSlug));
export const getForumTopics=(sectionSlug:string,categorySlug:string)=>forumStarterTopics.filter(topic=>topic.sectionSlug===sectionSlug&&topic.categorySlug===categorySlug);
export const findForumSection=(slug:string)=>forumSections.find(section=>section.slug===slug);
export const findForumCategory=(sectionSlug:string,categorySlug:string)=>{const section=findForumSection(sectionSlug);const title=section?.categories.find(category=>slugifyForumCategory(category)===categorySlug);return section&&title?{section,title,slug:categorySlug}:null};
