export type ForumSection={slug:string;title:string;icon:string;description:string;categories:string[]};
export const forumSections:ForumSection[]=[
{slug:'sky-bozum-duyurular',title:'Sky Bozum ve Duyurular',icon:'✦',description:'Topluluk kuralları, platform yenilikleri ve resmî bilgilendirmeler.',categories:['Forum kuralları','Sky Bozum duyuruları','Yeni özellikler','Kampanyalar ve fırsatlar','Öneri ve geri bildirim']},
{slug:'yeni-baslayanlar',title:'Yeni Başlayanlar',icon:'◎',description:'Forumu, dijital hizmetleri ve temel internet araçlarını yeni kullananlar için başlangıç alanı.',categories:['Foruma başlangıç','Temel internet bilgileri','İlk web sitesi','İlk online satış','Sık sorulan sorular']},
{slug:'mobil-odeme',title:'Mobil Ödeme',icon:'▣',description:'Operatör limitleri, faturaya yansıtma, hata ve güvenlik konuları.',categories:['Vodafone mobil ödeme','Turkcell mobil ödeme','Türk Telekom mobil ödeme','Limit ve fatura işlemleri','Hata ve çözüm yolları','Güvenli kullanım']},
{slug:'dijital-kodlar',title:'Dijital Kodlar ve Gift Card',icon:'◇',description:'Oyun kodları, hediye kartları, bölge uyumu ve güvenli teslim süreçleri.',categories:['Apple Gift Card','Google Play kodları','Steam cüzdan kodları','Razer Gold','Oyun ve E-PIN kodları','Kod güvenliği']},
{slug:'sikayet-ve-cozum',title:'Şikâyet ve Çözüm',icon:'!',description:'Sorunların belgeli biçimde paylaşılması ve çözüm durumunun takip edilmesi.',categories:['Bozum işlemi şikâyetleri','Operatör sorunları','Dijital kod sorunları','Online alışveriş şikâyetleri','Çözülen şikâyetler','Yanıt bekleyenler']},
{slug:'dijital-guvenlik',title:'Dijital Güvenlik',icon:'⌾',description:'Hesap güvenliği, dolandırıcılık belirtileri, kimlik avı ve veri koruma.',categories:['Hesap güvenliği','Dolandırıcılık uyarıları','Kimlik avı ve sahte bağlantılar','Şifre ve iki aşamalı doğrulama','Kişisel veri güvenliği','Güvenlik haberleri']},
{slug:'webmaster-genel',title:'Webmaster Genel',icon:'⌘',description:'Site sahiplerinin genel soruları, deneyimleri ve proje değerlendirmeleri.',categories:['Webmaster gündemi','Site değerlendirme','Proje fikirleri','Araç ve kaynak önerileri','Sorun ve çözümler','Webmaster dayanışması']},
{slug:'web-gelistirme',title:'Web Geliştirme',icon:'</>',description:'Ön yüz, arka uç, performans, erişilebilirlik ve web standartları.',categories:['HTML ve CSS','JavaScript ve TypeScript','React ve Next.js','Sunucu tarafı geliştirme','Web performansı','Erişilebilirlik']},
{slug:'cms-ve-wordpress',title:'CMS ve WordPress',icon:'W',description:'İçerik yönetim sistemlerinin kurulumu, bakımı, tema ve eklentileri.',categories:['WordPress başlangıç','Tema geliştirme','Eklenti seçimi','Güvenlik ve yedekleme','Hızlandırma','Diğer içerik sistemleri']},
{slug:'seo-ve-arama',title:'SEO ve Arama Motorları',icon:'↗',description:'Teknik SEO, içerik kalitesi, ölçüm ve arama görünürlüğü.',categories:['SEO başlangıç','Teknik SEO','İçerik ve arama niyeti','Search Console','Yerel SEO','SEO sorunları ve analiz']},
{slug:'yapay-zeka',title:'Yapay Zekâ Araçları',icon:'✧',description:'Yapay zekâ araçlarının üretken, güvenli ve şeffaf kullanım biçimleri.',categories:['Yapay zekâ başlangıç','Metin ve araştırma araçları','Görsel üretim','Kodlama yardımcıları','Otomasyon fikirleri','Doğruluk ve etik']},
{slug:'grafik-ve-tasarim',title:'Grafik ve Tasarım',icon:'◈',description:'Görsel tasarım, kullanıcı deneyimi, marka dili ve üretim araçları.',categories:['Grafik tasarım temelleri','UI ve UX tasarımı','Logo ve kurumsal kimlik','Adobe araçları','Canva ve pratik araçlar','Tasarım geri bildirimi']},
{slug:'sosyal-medya',title:'Sosyal Medya',icon:'#',description:'Platform güvenliği, içerik planlama, ölçüm ve topluluk yönetimi.',categories:['Instagram','YouTube','TikTok','Facebook','X ve Threads','Sosyal medya güvenliği']},
{slug:'e-ticaret',title:'E-Ticaret',icon:'₺',description:'Mağaza kurulumu, ürün, ödeme, teslimat ve tüketici deneyimi.',categories:['E-ticarete başlangıç','Mağaza altyapıları','Ürün ve stok yönetimi','Ödeme yöntemleri','Kargo ve teslimat','İade ve tüketici hakları']},
{slug:'pazaryerleri',title:'Pazaryerleri',icon:'▤',description:'Pazaryeri mağazalarının operasyonu, komisyonları ve müşteri süreçleri.',categories:['Trendyol','Hepsiburada','Amazon Türkiye','N11','Etsy ve global pazarlar','Pazaryeri operasyonu']},
{slug:'dijital-pazarlama',title:'Dijital Pazarlama',icon:'◉',description:'Reklam ölçümü, hedef kitle, dönüşüm ve sürdürülebilir büyüme.',categories:['Google Ads','Meta reklamları','İçerik pazarlaması','E-posta pazarlaması','Dönüşüm ölçümü','Bütçe ve performans']},
{slug:'icerik-uretimi',title:'İçerik Üretimi',icon:'¶',description:'Makaleler, video, görsel ve yayın planlarında kalite odaklı üretim.',categories:['Makale hazırlama','Editörlük ve doğrulama','Video içerik','İçerik takvimi','Kaynak kullanımı','Telif ve lisans']},
{slug:'domain-ve-hosting',title:'Domain ve Hosting',icon:'◎',description:'Alan adı, barındırma, DNS, SSL ve sunucu seçimi hakkında teknik bilgi.',categories:['Alan adı seçimi','Domain transferi','Hosting seçimi','DNS ve SSL','Sunucu yönetimi','Kesinti ve teknik sorunlar']},
{slug:'yazilim-ve-programlama',title:'Yazılım ve Programlama',icon:'{ }',description:'Programlama dilleri, uygulama geliştirme ve yazılım pratiği.',categories:['Programlamaya başlangıç','Python','PHP','Mobil uygulamalar','Veritabanları','Git ve proje yönetimi']},
{slug:'teknoloji-gundemi',title:'Teknoloji Gündemi',icon:'⚡',description:'Yeni ürünler, platform değişiklikleri ve doğrulanmış teknoloji gelişmeleri.',categories:['Teknoloji haberleri','Mobil cihazlar','Uygulamalar ve servisler','İşletim sistemleri','İnternet teknolojileri','Yeni ürün değerlendirmeleri']},
{slug:'donanim-ve-teknik-destek',title:'Donanım ve Teknik Destek',icon:'⚙',description:'Bilgisayar, telefon, ağ ve çevre birimi sorunları için yardımlaşma.',categories:['Bilgisayar donanımı','Telefon ve tablet','Ağ ve modem','Çevre birimleri','Arıza ve teknik destek','Hangisini almalıyım']},
{slug:'girisimcilik',title:'Girişimcilik ve İş Fikirleri',icon:'▲',description:'Fikir doğrulama, küçük işletme, maliyet ve büyüme deneyimleri.',categories:['İş fikri değerlendirme','Girişime başlangıç','Maliyet ve bütçe','Müşteri bulma','Markalaşma','Başarısızlık ve dersler']},
{slug:'freelance-ve-hizmetler',title:'Freelance ve Hizmetler',icon:'◆',description:'Freelance çalışma, hizmet kapsamı, teklif ve güvenli iş ilişkileri.',categories:['Freelance başlangıç','Teklif hazırlama','Müşteri iletişimi','Sözleşme ve teslim','Portföy geliştirme','Hizmet deneyimleri']},
{slug:'sohbet',title:'Sohbet ve Topluluk',icon:'☵',description:'Üyelerin kendini tanıttığı, gündemi ve günlük ilgi alanlarını konuştuğu bölüm.',categories:['Tanışma alanı','Güncel konular','Oyun ve eğlence','Film, dizi ve müzik','Öneriler','Serbest sohbet']},
{slug:'forum-destek',title:'Forum Destek',icon:'?',description:'Üyelik, içerik bildirimi, teknik sorun ve forum kullanım desteği.',categories:['Üyelik ve hesap sorunları','Forum kullanım rehberi','İçerik şikâyeti','Teknik sorun bildirimi','Öneri ve geri bildirim']}
];
export const findForumSection=(slug:string)=>forumSections.find(section=>section.slug===slug);
