export type ProductTone = 'pubg' | 'mlbb' | 'valorant' | 'lol' | 'rise' | 'knight' | 'metin2' | 'razer' | 'steam' | 'apple';

export type ProductPack = {
  id: string;
  label: string;
  description: string;
};

export type ProductItem = {
  slug: string;
  name: string;
  shortName: string;
  category: string;
  eyebrow: string;
  description: string;
  intro: string;
  tone: ProductTone;
  coverImage: string;
  brandLogo?: string;
  brandIntegrated?: boolean;
  coverVideo?: string;
  coverPosition?: string;
  coverLabel: string;
  coverNote: string;
  packs: ProductPack[];
  guide: { title: string; text: string; sourceLabel: string; sourceUrl: string };
  details: { title: string; text: string }[];
  howTo: { title: string; text: string }[];
  faq: { question: string; answer: string }[];
  related: string[];
};

const stockNotice = 'Güncel stok ve satış fiyatı ürün sayfasındaki paket kartlarında anlık gösterilir. Stok yoksa satın alma butonu otomatik olarak kapalı kalır.';

export const products: ProductItem[] = [
  {
    slug: 'pubg-mobile-uc',
    name: 'PUBG Mobile UC',
    shortName: 'PUBG Mobile UC',
    category: 'Oyun bakiyesi',
    eyebrow: 'UC ürünleri',
    description: 'UC paketlerini bölge ve teslim koşuluna göre karşılaştırın.',
    intro: 'Paket seçmeden önce hesabınızın bölgesini, oyuncu kimliğini ve teslim koşullarını kontrol edin. UC, oyun içi içeriklerde kullanılan bir bakiyedir; nakit para yerine geçmez.',
    tone: 'pubg',
    coverImage: '/products/pubg-mobile-uc-vatan-cover.jpeg',
    coverVideo: '/products/videos/pubg-mobile-uc.mp4',
    coverPosition: '50% 46%',
    coverLabel: 'PUBG',
    coverNote: 'MOBILE UC',
    guide: {
      title: 'PUBG Mobile UC rehberi',
      text: 'UC, PUBG Mobile içindeki premium oyun bakiyesidir. Paket seçerken doğru oyuncu ID’si, hesap bölgesi ve teslim yöntemini birlikte kontrol edin. UC hesabınıza yansımadıysa aynı paketi yeniden almadan önce satın alma kaydını, oyun içi bakiyeyi ve ödeme hareketini kontrol edin; hesap şifresi veya doğrulama kodunu hiçbir destek hesabıyla paylaşmayın.',
      sourceLabel: 'PUBG Mobile yardım merkezinde UC bilgisini aç',
      sourceUrl: 'https://pubgmobile.helpshift.com/hc/en/3-pubg-mobile/faq/35-what-is-uc-in-pubg-mobile/?contact=1',
    },
    details: [
      { title: 'UC nedir, ne için kullanılır?', text: 'Unknown Cash (UC), PUBG Mobile mağazasında Royale Pass, sandık, kozmetik ve dönemsel oyun içi içeriklerde kullanılan premium bakiyedir. Nakit para değildir; paket kapsamı ve kullanılabilir içerikler oyunun güncel mağazasına göre değişir.' },
      { title: 'Teslimat hangi bilgiyle yapılır?', text: 'Doğrudan yüklemede oyuncu ID’si ve desteklenen hesap bölgesi hedefi belirler. Kod teslimi sunulan ürünlerde ise kod kullanıcı tarafından etkinleştirilir. Sipariş ekranında hangi yöntemin kullanıldığını görmeden işlem tamamlanmamalıdır.' },
      { title: 'Satın almadan önce kontrol listesi', text: 'Paket miktarını, toplam tutarı, hesap bölgesini ve teslim yöntemini birlikte doğrulayın. Bakiye görünmezse ikinci kez satın almayın; sipariş kaydını saklayın. Hesap şifresi, SMS kodu ve cihaz onayı hiçbir yükleme adımında paylaşılmamalıdır.' },
    ],
    packs: ['60', '325', '660', '1.800', '3.850', '8.100'].map((label) => ({ id: label, label: `${label} UC`, description: `PUBG Mobile ${label} UC paketi` })),
    howTo: [
      { title: 'Oyuncu ID’sini doğrulayın', text: 'Oyundaki profil ekranından ID ve kullanıcı adını birlikte kontrol edin; yalnızca kullanıcı adına güvenmeyin.' },
      { title: 'Bölge ve paketi eşleştirin', text: 'Hesap bölgesi, UC paketi ve teslim yönteminin aynı koşullara bağlı olduğundan emin olun.' },
      { title: 'İşlem öncesi toplamı okuyun', text: 'Paket tutarı, varsa hizmet bedeli ve teslim notunu onaylamadan ilerlemeyin.' },
      { title: 'Bakiyeyi tek kez kontrol edin', text: 'Teslim sonrası oyun içi bakiye ve işlem geçmişini kontrol edin; görünmüyorsa tekrar satın alma yapmayın.' },
      { title: 'Hesabı koruyun', text: 'Şifre, SMS kodu, cihaz onayı veya uzaktan erişim isteyen kişilere itibar etmeyin.' },
    ],
    faq: [
      { question: 'UC nedir, nerede kullanılır?', answer: 'UC, PUBG Mobile içindeki desteklenen oyun içi içeriklerde kullanılan premium bakiyedir; nakit para veya banka bakiyesi değildir.' },
      { question: 'UC yüklemek için oyuncu ID’si neden önemlidir?', answer: 'Yükleme hedef hesabın oyuncu ID’siyle eşleşir. Yanlış ID, doğru hesabın dışında bir teslim veya inceleme gerektiren durum oluşturabilir.' },
      { question: 'UC paketi hesabıma gelmediyse ne yapmalıyım?', answer: 'Önce oyun içi bakiyeyi, satın alma geçmişini ve ödeme hareketini kontrol edin. Aynı paketi tekrar almadan önce işlem kaydıyla PUBG Mobile’ın resmî desteğine başvurun.' },
      { question: 'PUBG Mobile UC her bölgede çalışır mı?', answer: 'Paket ve teslim yöntemi hesap bölgesine göre değişebilir. İşlem öncesinde hesap bölgesi ile ürün koşulunun eşleştiğini kontrol edin.' },
      { question: 'UC iade edilebilir mi?', answer: 'İade ve itiraz koşulları ödeme kanalı ile PUBG Mobile kurallarına göre değerlendirilir; satın almadan önce paketi ve hesabı doğrulayın.' },
      { question: 'PUBG Mobile UC bozum için hesap şifresi gerekir mi?', answer: 'Hayır. Şifre, SMS kodu veya cihaz erişimi isteyen kişilerle işlem yapmayın.' },
      { question: 'PUBG Mobile UC stokta mı?', answer: stockNotice },
    ],
    related: ['mobile-legends-diamond', 'valorant-vp', 'league-of-legends-rp'],
  },
  {
    slug: 'mobile-legends-diamond',
    name: 'Mobile Legends Elmas',
    shortName: 'Mobile Legends Elmas',
    category: 'Oyun bakiyesi',
    eyebrow: 'Elmas ürünleri',
    description: 'Elmas ve Weekly Diamonds seçeneklerini bölgenize göre inceleyin.',
    intro: 'Mobile Legends yüklemelerinde oyuncu ID’si, sunucu ID’si, hesap bölgesi ve seçilen elmas paketi birlikte doğrulanmalıdır. Hatalı hesaba yapılan doğrudan yükleme geri alınamayabilir.',
    tone: 'mlbb',
    coverImage: '/products/mobile-legends-bang-bang-cover.webp',
    coverVideo: '/products/videos/mobile-legends-bang-bang.mp4',
    coverPosition: '50% 44%',
    coverLabel: 'MOBILE LEGENDS',
    coverNote: 'ELMAS · WEEKLY DIAMONDS',
    guide: {
      title: 'Mobile Legends Elmas rehberi',
      text: 'Elmas, Mobile Legends: Bang Bang içindeki desteklenen içeriklerde kullanılan premium oyun bakiyesidir. Doğrudan yükleme yapılırken oyuncu ID’si ile sunucu ID’si ayrı alanlardır; ikisini de profil ekranından kontrol edin. Weekly Diamonds ve ilk yükleme paketlerinin süre veya adet sınırı olabilir. Şifre, SMS kodu ya da hesap erişimi istemeyen, yalnız doğrulanabilir oyuncu bilgileriyle ilerleyen yöntemi tercih edin.',
      sourceLabel: 'Mobile Legends resmî sitesini aç',
      sourceUrl: 'https://www.mobilelegends.com/',
    },
    details: [
      { title: 'Elmas ve Weekly Diamonds farkı', text: 'Elmas, Mobile Legends mağazasındaki desteklenen içeriklerde kullanılan premium bakiyedir. Weekly Diamonds ise belirli süreye ve teslim planına bağlı ayrı bir üründür; tek seferlik elmas paketiyle aynı kapsamda değerlendirilmemelidir.' },
      { title: 'Oyuncu ID’si neden tek başına yetmez?', text: 'Doğrudan yüklemelerde oyuncu ID’si ile parantez içinde görülen sunucu veya zone ID’si birlikte kullanılır. Bu iki değer farklı hesapları ayırt eder; kullanıcı adı tek başına güvenilir teslim bilgisi değildir.' },
      { title: 'Etkinlik ve bonuslarda dikkat', text: 'İlk yükleme bonusu, Weekly Diamonds ve etkinlik ödülleri dönemsel koşullara bağlı olabilir. Satın alma öncesinde oyun içindeki güncel kapsamı kontrol edin. Yükleme için şifre, doğrulama kodu veya cihaz erişimi paylaşmayın.' },
    ],
    packs: ['Weekly Diamonds', '16 Elmas', '24 Elmas', '44 Elmas', '88 Elmas', '133 Elmas', '221 Elmas', '354 Elmas', '562 Elmas', '715 Elmas', '1.041 Elmas', '1.535 Elmas'].map((label) => ({ id: label.toLowerCase().replace(/\s|\./g, '-'), label, description: `Mobile Legends ${label} paketi` })),
    howTo: [
      { title: 'Oyuncu ve sunucu ID’sini alın', text: 'Profil ekranındaki oyuncu ID’si ile parantez içindeki sunucu ID’sini ayrı ayrı doğrulayın.' },
      { title: 'Hesap bölgesini eşleştirin', text: 'TR, global veya ülkeye özel paket koşulunu hesabınızın bölgesiyle karşılaştırın.' },
      { title: 'Paket sınırını okuyun', text: 'Weekly Diamonds ve ilk yükleme ürünlerinde dönemsel veya tek seferlik satın alma sınırı bulunabilir.' },
      { title: 'Teslimi tek hesapta kontrol edin', text: 'Elmas bakiyesi görünmüyorsa aynı paketi yeniden almadan önce oyuncu bilgilerini ve işlem kaydını inceleyin.' },
      { title: 'Hesap erişimini paylaşmayın', text: 'Yükleme için hesap şifresi, SMS kodu veya cihaz erişimi gerekmez.' },
    ],
    faq: [
      { question: 'Mobile Legends Elmas nedir?', answer: 'Elmas, Mobile Legends mağazasındaki desteklenen kostüm, etkinlik ve diğer dijital içeriklerde kullanılan premium oyun bakiyesidir.' },
      { question: 'Oyuncu ID’si ile sunucu ID’si aynı mı?', answer: 'Hayır. Profil ekranında ayrı gösterilirler ve doğrudan yükleme için ikisinin de doğru girilmesi gerekir.' },
      { question: 'Weekly Diamonds normal elmas paketi mi?', answer: 'Weekly Diamonds belirli süre boyunca avantaj sağlayan ayrı bir üründür; normal tek seferlik elmas paketiyle aynı kabul edilmemelidir.' },
      { question: 'Elmas yanlış hesaba giderse geri alınır mı?', answer: 'Doğrudan yüklemeler çoğunlukla hedef hesaba işlendiği için geri alma mümkün olmayabilir. Onaydan önce ID ve sunucu bilgisini kontrol edin.' },
      { question: 'Yükleme görünmüyorsa ne yapmalıyım?', answer: 'Oyunu yeniden açın, doğru hesaba giriş yaptığınızı ve siparişteki oyuncu bilgilerini kontrol edin; yeni sipariş oluşturmadan destek kaydı açın.' },
      { question: 'Hesap şifresi gerekir mi?', answer: 'Hayır. Oyuncu ve sunucu ID’si dışında şifre, SMS kodu veya uzaktan erişim paylaşmayın.' },
      { question: 'Mobile Legends ürünleri stokta mı?', answer: stockNotice },
    ],
    related: ['pubg-mobile-uc', 'valorant-vp', 'league-of-legends-rp'],
  },
  {
    slug: 'valorant-vp',
    name: 'Valorant VP',
    shortName: 'Valorant VP',
    category: 'Oyun bakiyesi',
    eyebrow: 'VP ürünleri',
    description: 'VP paketlerini bölge ve hesap uyumuyla karşılaştırın.',
    intro: 'VP, Valorant mağazasında kullanılan oyun içi para birimidir. Paket seçerken Riot hesabının bölgesini, tutarı ve teslim biçimini kontrol etmek önemlidir.',
    tone: 'valorant',
    coverImage: '/products/valorant-vatan-cover.webp',
    coverVideo: '/products/videos/valorant-vp.mp4',
    coverPosition: '50% 42%',
    coverLabel: 'VALORANT',
    coverNote: 'POINTS',
    guide: {
      title: 'Valorant VP rehberi',
      text: 'VP, Riot hesabında Valorant mağazasında kullanılan premium para birimidir. Ön ödemeli kodlarda bölge ve para birimi kilidi bulunabildiği için kodu kullanacağınız hesabın bölgesini işlemden önce doğrulayın. Kod kullanıldıktan sonra doğru hesaba giriş yapıldığından emin olun; hata alırsanız kodu herkese açık biçimde paylaşmadan makbuz ve hata ekranıyla resmî desteğe başvurun.',
      sourceLabel: 'Riot kod kullanma sayfasını aç',
      sourceUrl: 'https://shop.riotgames.com/redeem',
    },
    details: [
      { title: 'VP ile Radianite aynı değildir', text: 'Valorant Points (VP), mağazadaki görünüm, paket ve Battle Pass gibi desteklenen içeriklerde kullanılan premium para birimidir. Radianite Points ayrı bir oyun içi kaynaktır. VP satın almak rekabetçi bir oyun avantajı sağlamaz.' },
      { title: 'Bölge ve para birimi neden önemlidir?', text: 'Ön ödemeli Riot kodları satın alındıkları bölge veya para birimiyle sınırlı olabilir. Kodun bölgesi ile Riot hesabının kayıtlı bölgesi eşleşmediğinde etkinleştirme reddedilebilir; bu nedenle yalnız tutarı değil bölge bilgisini de kontrol edin.' },
      { title: 'Kodu güvenli biçimde kullanın', text: 'Kod tek kullanımlıdır ve etkinleştirme sırasında açık olan Riot hesabına uygulanır. Onaydan önce hesap adını kontrol edin; tam kodu mesajlarda paylaşmayın. Riot hesabı şifresi ve iki aşamalı doğrulama kodu satış veya destek için istenmemelidir.' },
    ],
    packs: ['375', '825', '1.700', '2.925', '4.325', '8.900'].map((label) => ({ id: label, label: `${label} VP`, description: `Valorant ${label} VP paketi` })),
    howTo: [
      { title: 'Riot hesabı ve bölgeyi kontrol edin', text: 'Kodun para birimi ile Valorant hesabının bölgesinin uyumlu olduğundan emin olun.' },
      { title: 'VP tutarını ve teslim biçimini okuyun', text: 'Kod mu, doğrudan yükleme mi sunulduğunu ve paketin toplam tutarını işlem öncesinde netleştirin.' },
      { title: 'Kodu doğru hesapta kullanın', text: 'Riot kod ekranında giriş yaptığınız hesabı ve ekrana gelen ürün bilgisini onaylamadan kodu tamamlamayın.' },
      { title: 'Kullanım sonucunu kontrol edin', text: 'VP bakiyesini oyun istemcisinde kontrol edin; görünmüyorsa tekrar denemek yerine işlem kaydını saklayın.' },
      { title: 'Kodu gizli tutun', text: 'Kodu, hesap şifresini veya iki aşamalı doğrulama bilgisini destek adı kullanan kişilerle paylaşmayın.' },
    ],
    faq: [
      { question: 'VP nedir?', answer: 'VP, Valorant mağazasında kostüm, silah görünümü ve benzeri desteklenen içeriklerde kullanılan Riot oyun içi para birimidir.' },
      { question: 'VP kodu hangi hesaba yüklenir?', answer: 'Kod, Riot kod ekranında o anda giriş yapılmış hesaba uygulanır. Onaydan önce kullanıcı adını ve bölgeyi mutlaka kontrol edin.' },
      { question: 'Valorant kodu neden bölgemde çalışmıyor?', answer: 'Ön ödemeli nakit kodları satın alındığı bölge veya para birimiyle sınırlı olabilir. Hesap bölgesi ile kod koşulunu karşılaştırın.' },
      { question: 'Kod kullanılmış veya geçersiz görünürse ne yapmalıyım?', answer: 'Kodu tekrar tekrar denemeyin ve tam kodu herkese açık alanda paylaşmayın. Sipariş belgesi, hata ekranı ve kod bilgisiyle Riot desteğine başvurun.' },
      { question: 'VP yüklemesi gecikirse tekrar kod almalı mıyım?', answer: 'Hayır. Önce istemciyi, hesap geçmişini ve Riot tarafındaki işlem durumunu kontrol edin; ikinci bir kod yeni bir sorunu çözmez.' },
      { question: 'VP kodu iki hesaba bölünebilir mi?', answer: 'Ön ödemeli nakit kodları tek kullanımda bir hesaba uygulanır; kodu kullanmadan önce doğru hesapta olduğunuzu doğrulayın.' },
      { question: 'Valorant VP stokta mı?', answer: stockNotice },
    ],
    related: ['pubg-mobile-uc', 'league-of-legends-rp'],
  },
  {
    slug: 'league-of-legends-rp',
    name: 'League of Legends RP',
    shortName: 'League of Legends RP',
    category: 'Oyun bakiyesi',
    eyebrow: 'RP ürünleri',
    description: 'RP paketlerini hesap bölgesi ve teslim koşuluyla inceleyin.',
    intro: 'RP, League of Legends mağazasında kullanılan oyun içi para birimidir. Ürün seçerken sunucu ve hesap bölgesi uyumluluğunu kontrol etmek, yanlış ürün alımını önler.',
    tone: 'lol',
    coverImage: '/products/league-of-legends-vatan-cover.webp',
    coverVideo: '/products/videos/league-of-legends-rp.mp4',
    coverPosition: '50% 42%',
    coverLabel: 'LEAGUE',
    coverNote: 'OF LEGENDS · RP',
    guide: {
      title: 'League of Legends RP rehberi',
      text: 'RP, League of Legends mağazasında kullanılan premium para birimidir. Ön ödemeli kodlarda bölge kilidi ve tek kullanım kuralı önemlidir; kodu doğru Riot hesabında ve doğru istemci bölgesinde kullanın. Kod kullanıldıktan sonra işlem geri alınamayabileceği için onay ekranındaki hesap ve içerik bilgisini kontrol edin, sorun yaşarsanız satın alma kanıtını saklayın.',
      sourceLabel: 'Riot kod kullanma sayfasını aç',
      sourceUrl: 'https://shop.riotgames.com/redeem',
    },
    details: [
      { title: 'RP ile Mavi Öz aynı değildir', text: 'Riot Points (RP), League of Legends mağazasında kostüm, etkinlik kartı ve desteklenen diğer dijital içeriklerde kullanılan premium para birimidir. Mavi Öz oyun içinde kazanılan ayrı bir kaynaktır; RP oyun gücü satın almaz.' },
      { title: 'Sunucu ve hesap bölgesi eşleşmesi', text: 'Ön ödemeli RP kodlarında bölge ve para birimi kısıtı bulunabilir. Kodun satıldığı ülke ile Riot hesabının bölgesi farklıysa kullanım reddedilebilir. İşlemden önce hesabın aktif sunucusunu ve kod koşulunu birlikte doğrulayın.' },
      { title: 'Etkinleştirme ve kayıt güvenliği', text: 'Kod, giriş yapılan Riot hesabına tek seferde uygulanır ve iki hesaba bölünemez. Kodun tamamını, hesap şifresini veya doğrulama bilgisini kimseyle paylaşmayın; hata durumunda satın alma belgesini saklayarak resmî desteğe başvurun.' },
    ],
    packs: ['460', '1.005', '2.105', '3.625', '5.295', '10.875'].map((label) => ({ id: label, label: `${label} RP`, description: `League of Legends ${label} RP paketi` })),
    howTo: [
      { title: 'Riot ID ve bölgeyi doğrulayın', text: 'RP kodunun para birimi ile hesabınızın bölge koşulunu işlem öncesinde eşleştirin.' },
      { title: 'RP paketini seçin', text: 'Paket miktarını, teslim yöntemini ve varsa kampanya koşulunu birlikte okuyun.' },
      { title: 'Doğru hesapta kullanın', text: 'Kod ekranındaki kullanıcı ve içerik bilgisini onaylamadan uygulamayı tamamlamayın.' },
      { title: 'RP bakiyesini kontrol edin', text: 'Kod sonrası mağaza bakiyesini ve işlem geçmişini kontrol edin; gecikmede yeni kod kullanmayın.' },
      { title: 'Makbuzu saklayın', text: 'Hata veya itiraz gerekirse satın alma belgesi ve ekran görüntüsü destek incelemesini kolaylaştırır.' },
    ],
    faq: [
      { question: 'RP nedir?', answer: 'RP, League of Legends mağazasında kostüm ve diğer desteklenen dijital içerikleri almak için kullanılan premium para birimidir.' },
      { question: 'RP kodu hangi hesaba gider?', answer: 'Kod, Riot kod sayfasında giriş yaptığınız hesaba uygulanır. Kullanımdan önce hesap adını ve bölgeyi kontrol edin.' },
      { question: 'RP kodu başka bölgedeki hesapta çalışır mı?', answer: 'Ön ödemeli nakit kodlarında bölge ve para birimi kısıtı bulunabilir. Kodun satın alındığı bölge ile hesap bölgesini karşılaştırın.' },
      { question: 'RP kodu iki hesaba bölünebilir mi?', answer: 'Hayır. Ön ödemeli kodlar tek kullanımda bir oyuna ve hesaba uygulanır; tam kodu kullanmadan önce hesabı doğrulayın.' },
      { question: 'RP kodu kullanıldı ama bakiye görünmüyor?', answer: 'İstemciyi yenileyip işlem geçmişini kontrol edin. Kod bilgisini herkese açık paylaşmadan satın alma belgesiyle Riot desteğine başvurun.' },
      { question: 'RP kodlarının süresi var mı?', answer: 'Riot’un ön ödemeli nakit kodları için genel bilgi kodların süresiz olduğunu belirtir; yine de ürün veya satıcı koşulunu satın alma öncesi kontrol edin.' },
      { question: 'League of Legends RP stokta mı?', answer: stockNotice },
    ],
    related: ['valorant-vp', 'rise-online-cash-premium', 'metin2-ejder-parasi'],
  },
  {
    slug: 'rise-online-cash-premium',
    name: 'Rise Online Cash & Premium',
    shortName: 'Rise Online Cash & Premium',
    category: 'Oyun bakiyesi',
    eyebrow: 'Cash & Premium',
    description: 'Rise Online Cash ve Premium seçeneklerini inceleyin.',
    intro: 'Bu sayfada yalnız Rise Online World PC Cash ve Premium ürünleri bulunur. Gold Bar, item, karakter, NFT ve mobil sürüm ürünleri kataloğa dahil değildir.',
    tone: 'rise',
    coverImage: '/products/rise-online-cover.webp',
    coverVideo: '/products/videos/rise-online.mp4',
    coverPosition: '50% 43%',
    coverLabel: 'RISE ONLINE',
    coverNote: 'WORLD CASH · PREMIUM',
    guide: {
      title: 'Rise Online Cash ve Premium rehberi',
      text: 'Rise Online World Cash oyun içi mağazada kullanılan dijital bakiyedir; Premium ise seçilen türe göre belirli oyun avantajlarını etkinleştiren ayrı bir üründür. PC ürünleri mobil sürümde kullanılamaz. Cash kodunu veya Premium seçimini onaylamadan önce hesabın PC sürümüne ait olduğunu, ürün adını ve teslim yöntemini kontrol edin. Bu katalog item, Gold Bar ve karakter satışını kapsamaz.',
      sourceLabel: 'Rise Online World resmî sitesini aç',
      sourceUrl: 'https://www.riseonlineworld.com/',
    },
    details: [
      { title: 'Cash ve Premium aynı ürün değildir', text: 'Cash, Rise Online World mağazasında kullanılan dijital bakiyedir. Premium ise seçilen türe ve süreye göre belirli hesap avantajlarını etkinleştiren ayrı bir üründür. Elite, Farm, XP, Battle, Craft ve Complete paketlerinin kapsamları birbirinden farklıdır.' },
      { title: 'Teslimat hesap ve sürüme bağlıdır', text: 'Bu katalog yalnız Rise Online World PC ürünlerini içerir. Kod veya doğrudan teslim seçeneği sunuluyorsa hedef hesabın, oyun sürümünün ve seçilen paketin uyumu kontrol edilmelidir. Mobil ürünler, item ve Gold Bar bu sayfanın kapsamı dışındadır.' },
      { title: 'Süre, stok ve hesap güvenliği', text: 'Premium süresi ürün açıklamasında belirtilen kapsamla başlar; dönemsel avantajlar değişebilir. Siparişten önce stok ve süreyi okuyun. Hesap şifresi, doğrulama kodu veya uzaktan erişim paylaşmadan yalnız resmî kullanım alanlarında ilerleyin.' },
    ],
    packs: [
      '500 Cash', '1.020 Cash', '2.050 Cash', '3.090 Cash', '4.140 Cash', '5.200 Cash', '10.500 Cash',
      'Elite Premium', 'Farm Premium', 'XP Premium', 'Battle Premium', 'Craft Premium', 'Complete Premium',
    ].map((label) => ({ id: label.toLowerCase().replace(/\s|\./g, '-'), label, description: `Rise Online ${label}` })),
    howTo: [
      { title: 'PC sürümünü doğrulayın', text: 'Bu katalogdaki Cash ve Premium seçenekleri Rise Online World PC içindir; mobil ürünlerle karıştırmayın.' },
      { title: 'Cash veya Premium seçin', text: 'Bakiye yüklemek için Cash, üyelik avantajı için ihtiyacınıza uygun Premium türünü seçin.' },
      { title: 'Ürün adını eksiksiz okuyun', text: 'Elite, Farm, XP, Battle, Craft ve Complete Premium seçenekleri aynı ürün değildir.' },
      { title: 'Kodu resmî hesapta kullanın', text: 'Kod veya bakiye işlemini Rise Online World hesabınızın resmî mağaza alanından tamamlayın.' },
      { title: 'İşlem kaydını saklayın', text: 'Teslim görünmezse yeniden satın almadan önce kod durumunu ve hesap geçmişini kontrol edin.' },
    ],
    faq: [
      { question: 'Rise Online Cash nedir?', answer: 'Cash, Rise Online World PC mağazasında desteklenen dijital içeriklerde kullanılan oyun bakiyesidir.' },
      { question: 'Premium ile Cash aynı ürün mü?', answer: 'Hayır. Cash bir bakiye, Premium ise seçilen türe göre belirli süre veya avantaj kapsamı sunan ayrı bir üründür.' },
      { question: 'Hangi Premium türleri var?', answer: 'Katalogda Elite, Farm, XP, Battle, Craft ve Complete Premium seçenekleri bulunur; kapsamları aynı değildir.' },
      { question: 'PC Cash kodu mobil sürümde kullanılır mı?', answer: 'Hayır. PC ve mobil ürünler ayrıdır; bu sayfa yalnız PC Cash ve Premium ürünlerini kapsar.' },
      { question: 'Gold Bar veya item burada satılıyor mu?', answer: 'Hayır. Bu katalog bilinçli olarak yalnız Cash ve Premium ürünlerine ayrılmıştır.' },
      { question: 'Kod görünmüyorsa ne yapmalıyım?', answer: 'Hesabın PC sürümüne ait olduğunu, kodun daha önce kullanılmadığını ve doğru mağaza alanında olduğunuzu kontrol edin.' },
      { question: 'Rise Online ürünleri stokta mı?', answer: stockNotice },
    ],
    related: ['knight-online-cash-premium', 'metin2-ejder-parasi', 'steam-cuzdan-kodu'],
  },
  {
    slug: 'knight-online-cash-premium',
    name: 'Knight Online Cash & Premium',
    shortName: 'Knight Online Cash & Premium',
    category: 'Oyun bakiyesi',
    eyebrow: 'Cash & Premium',
    description: 'Cash ESN ve 30 günlük Premium seçeneklerini inceleyin.',
    intro: 'Bu sayfada Knight Online Cash ESN ile Bronze, Gold ve Platinum Premium ürünleri bulunur. Item, Gold Bar ve hesap satışları kataloğa dahil değildir.',
    tone: 'knight',
    coverImage: '/products/knight-online-cover.webp',
    coverVideo: '/products/videos/knight-online.mp4',
    coverPosition: '50% 44%',
    coverLabel: 'KNIGHT ONLINE',
    coverNote: 'CASH ESN · PREMIUM',
    guide: {
      title: 'Knight Online Cash ve Premium rehberi',
      text: 'Knight Cash, Knight Online mağazasında kullanılan dijital bakiyedir. Premium ürünleri Bronze, Gold ve Platinum olarak ayrılır ve bu katalogda 30 günlük MGAME ESN seçenekleri gösterilir. Cash kodunun Steam sürümünde geçerli olup olmadığını ürün koşulundan ayrıca kontrol edin. ESN kodunu ve hesap bilgilerini herkese açık alanda paylaşmayın.',
      sourceLabel: 'Knight Online resmî sitesini aç',
      sourceUrl: 'https://www.nttgame.com/knight/en/',
    },
    details: [
      { title: 'Cash ve Premium ne sağlar?', text: 'Knight Cash, oyun mağazasındaki desteklenen dijital içerikler için kullanılan bakiyedir. Bronze, Gold ve Platinum Premium ise süreli üyelik seçenekleridir. Premium kapsamı ve güncel avantajları ürün türüne göre değiştiği için yalnız ada bakarak seçim yapılmamalıdır.' },
      { title: 'Hesap ve oyun sürümü eşleşmesi', text: 'MGAME/NTTGame ve Steam sürümü için sunulan ürün koşulları aynı olmayabilir. Cash ESN veya Premium almadan önce oynadığınız istemciyi, hesabın bölgesini, paket süresini ve kodun hangi sürümde geçerli olduğunu doğrulayın.' },
      { title: 'ESN kodu tesliminde güvenlik', text: 'ESN kodu tek kullanımlıktır. Tam kodu forumda veya mesaj ekranında paylaşmayın; yalnız resmî etkinleştirme alanına girin. Hesap şifresi, tek kullanımlık doğrulama kodu ve uzaktan bağlantı erişimi hiçbir kod tesliminde gerekli değildir.' },
    ],
    packs: [
      '400 Cash ESN', '800 Cash ESN', '1.200 Cash ESN', '1.600 Cash ESN', '2.000 Cash ESN', '2.400 Cash ESN', '3.200 Cash ESN',
      '30 Gün Bronze Premium', '30 Gün Gold Premium', '30 Gün Platinum Premium',
    ].map((label) => ({ id: label.toLowerCase().replace(/\s|\./g, '-'), label, description: `Knight Online ${label}` })),
    howTo: [
      { title: 'Oyun sürümünü kontrol edin', text: 'Cash ürününün MGAME/NTTGame veya Steam sürümü koşulunu satın almadan önce okuyun.' },
      { title: 'Cash ve Premium’u ayırın', text: 'Bakiye için Cash ESN, üyelik avantajı için Bronze, Gold veya Platinum Premium seçin.' },
      { title: 'Süreyi doğrulayın', text: 'Bu katalogdaki Premium ürünleri 30 günlük seçeneklerdir; ürün adındaki süreyi kontrol edin.' },
      { title: 'ESN kodunu gizli tutun', text: 'Kod tek kullanımlıdır; ekran görüntüsü veya tam kodu forum ve mesaj alanlarında paylaşmayın.' },
      { title: 'Teslim sonrası hesabı kontrol edin', text: 'Cash bakiyesi veya Premium durumu görünmüyorsa yeniden kod almadan işlem kaydıyla destek isteyin.' },
    ],
    faq: [
      { question: 'Knight Cash nedir?', answer: 'Knight Cash, Knight Online mağazasında desteklenen dijital içeriklerde kullanılan oyun bakiyesidir.' },
      { question: 'Cash ESN ne demek?', answer: 'ESN, satın alınan dijital kodun Knight Online hesabında kullanılmasını sağlayan tek kullanımlık teslim biçimidir.' },
      { question: 'Hangi Premium türleri var?', answer: 'Bu sayfada 30 günlük Bronze, Gold ve Platinum Premium seçenekleri gösterilir.' },
      { question: 'Steam sürümünde Cash kodu çalışır mı?', answer: 'Her Cash ürünü Steam sürümünde geçerli olmayabilir. Ürün açıklamasındaki sürüm bilgisini onaylamadan kod almayın.' },
      { question: 'Item veya Gold Bar burada var mı?', answer: 'Hayır. Bu katalog yalnız Cash ve Premium ürünleri için hazırlanmıştır.' },
      { question: 'Kodu kullanılmış gösterirse ne yapmalıyım?', answer: 'Kodu tekrar paylaşmayın; satın alma belgesi, hata ekranı ve ESN bilgisiyle resmî destek incelemesi başlatın.' },
      { question: 'Knight Online ürünleri stokta mı?', answer: stockNotice },
    ],
    related: ['rise-online-cash-premium', 'metin2-ejder-parasi', 'steam-cuzdan-kodu'],
  },
  {
    slug: 'metin2-ejder-parasi',
    name: 'Metin2 Ejder Parası',
    shortName: 'Metin2 Ejder Parası',
    category: 'Oyun bakiyesi',
    eyebrow: 'EP ürünleri',
    description: 'Metin2 EP paketlerini sunucu bilgisiyle karşılaştırın.',
    intro: 'Ejder Parası, Metin2 mağazasında kullanılan oyun içi bakiyedir. Paket seçmeden önce sunucu, karakter ve yükleme koşullarını doğru belirlemek gerekir.',
    tone: 'metin2',
    coverImage: '/products/metin2-vatan-cover.webp',
    coverVideo: '/products/videos/metin2-ejder-parasi.mp4',
    coverPosition: '72% 46%',
    coverLabel: 'METİN2',
    coverNote: 'EJDER PARASI',
    guide: {
      title: 'Metin2 Ejder Parası rehberi',
      text: 'Ejder Parası, Metin2 Nesne Market’te kullanılan oyun içi kredidir. Paket veya kupon türünü, hesabı ve sunucu koşulunu işlemden önce doğrulayın; kuponların saklama süresi ürün tipine göre değişebilir. EP ile Ejderha Markası aynı şey değildir: bazı harcamalarda EP kullanımı ayrıca marka kazandırabilir. Teslim görünmüyorsa tekrar işlem başlatmadan oyun içi marketi ve hesap geçmişini kontrol edin.',
      sourceLabel: 'Gameforge Metin2 Wiki’de Ejderha Parası bilgisini aç',
      sourceUrl: 'https://tr-wiki.metin2.gameforge.com/index.php?stable=1&title=EM',
    },
    details: [
      { title: 'EP, Yang ve Ejderha Markası farkı', text: 'Ejder Parası (EP), Metin2 Nesne Market’te kullanılan premium kredidir. Yang oyun dünyasında kazanılan ve kullanılan ayrı para birimidir. Ejderha Markası da EP ile aynı bakiye değildir; uygun EP harcamaları veya dönemsel sistemler üzerinden ayrı biçimde oluşabilir.' },
      { title: 'Nesne Market ve kupon kullanımı', text: 'Doğrudan EP yüklemesi ile EP kuponu aynı teslim biçimi değildir. Kupon veya kod sunuluyorsa resmî hesap alanında tek kez kullanılır; paket miktarı ve olası kullanım süresi ürün açıklamasından kontrol edilir. Nesne Market içeriği zaman içinde değişebilir.' },
      { title: 'Bonus saatleri ve hesap güvenliği', text: 'Happy Hour gibi ek EP kampanyaları yalnız resmî duyuruda belirtilen tarih ve saatlerde geçerlidir; satın almadan hemen önce kampanyanın aktif olduğunu kontrol edin. Hesap şifresi ve doğrulama kodu paylaşmayın, yalnız hesabınıza uygun TR istemcisi ve paket türüyle ilerleyin.' },
    ],
    packs: ['300', '750', '1.750', '4.800', '11.250'].map((label) => ({ id: label.replace('.', '-'), label: `${label} EP`, description: `Metin2 ${label} Ejder Parası paketi` })),
    howTo: [
      { title: 'Hesap ve sunucu bilgisini doğrulayın', text: 'Yükleme yapılacak Gameforge hesabını ve sunucuyu işlem öncesinde açıkça belirtin.' },
      { title: 'EP ile kuponu ayırın', text: 'Doğrudan bakiye mi, kullanılabilir kupon/kod mu sunulduğunu ürün açıklamasından kontrol edin.' },
      { title: 'Süre ve kullanım koşulunu okuyun', text: 'Kupon veya etkinlik ürünlerinde saklama/son kullanım koşulu bulunabilir; ekran görüntüsünü saklayın.' },
      { title: 'Nesne Market bakiyesini kontrol edin', text: 'Teslim sonrası oyun içi marketteki EP bakiyesini ve işlem geçmişini kontrol edin.' },
      { title: 'Hesap güvenliğini koruyun', text: 'Şifre, SMS kodu veya uzaktan erişim isteyen kişilerle işlem yapmayın.' },
    ],
    faq: [
      { question: 'Ejderha Parası (EP) nedir?', answer: 'EP, Metin2 Nesne Market’te desteklenen oyun içi ürünleri almak için kullanılan dijital kredidir.' },
      { question: 'EP ile Ejderha Markası aynı mı?', answer: 'Hayır. Gameforge Wiki’de EP harcandığında bazı durumlarda Ejderha Markası elde edilebildiği, ancak iki bakiyenin aynı olmadığı belirtilir.' },
      { question: 'EP yüklemesi için sunucu neden sorulur?', answer: 'Hesap ve sunucu eşleşmesi teslim yöntemine göre önem taşıyabilir. Yanlış bilgi, işlemin incelenmesini veya düzeltme gerektirmesini doğurabilir.' },
      { question: 'EP kuponlarının süresi olur mu?', answer: 'Kupon ve etkinlik ürünlerinde süre ürüne göre değişebilir. Doğrudan EP ile kuponu aynı kabul etmeyin; ürün açıklamasındaki tarihi kontrol edin.' },
      { question: 'EP teslim edilmediğinde ne yapmalıyım?', answer: 'Nesne Market’i, hesap geçmişini ve işlem kaydını kontrol edin; aynı işlemi tekrarlamadan Gameforge’un resmî destek kanalına başvurun.' },
      { question: 'Metin2 hesabımın şifresini paylaşmalı mıyım?', answer: 'Hayır. Şifre, tek kullanımlık kod veya uzaktan erişim isteyen kişilerle işlem yapmayın.' },
      { question: 'Metin2 Ejder Parası stokta mı?', answer: stockNotice },
    ],
    related: ['rise-online-cash-premium', 'knight-online-cash-premium', 'razer-gold'],
  },
  {
    slug: 'razer-gold',
    name: 'Razer Gold TL & USD',
    shortName: 'Razer Gold',
    category: 'Dijital kod',
    eyebrow: 'TL & USD ürünleri',
    description: 'TL ve USD PIN seçeneklerini bölgenize göre inceleyin.',
    intro: 'Razer Gold PIN kodlarında tutar kadar para birimi, bölge ve kullanılmamış olma şartı da önemlidir. Kodunuzu hesabınıza yüklemeden önce ürün bilgisini doğrulayın.',
    tone: 'razer',
    coverImage: '/products/razer-gold-centered-v2.webp',
    brandLogo: '/brands/razer/razer.svg',
    brandIntegrated: true,
    coverPosition: '50% 50%',
    coverLabel: 'RAZER',
    coverNote: 'GOLD · TL / USD',
    guide: {
      title: 'Razer Gold TL & USD rehberi',
      text: 'Razer Gold PIN’i yüklemek için gold.razer.com üzerinde doğru bölge cüzdanına giriş yapılır, Reload Now alanından PIN yöntemi seçilir ve iki aşamalı doğrulama tamamlanır. TL ve USD kodları aynı koşullarda değerlendirilmez; PIN’in bölgesi, tam kodu ve kullanım durumu işlem öncesinde doğrulanmalıdır. Bozum düşünülüyorsa kodu kendi cüzdanınıza yüklemeyin; yüklenen bakiye PIN olarak incelenemez.',
      sourceLabel: 'Razer Gold resmî yardım merkezini aç',
      sourceUrl: 'https://gold.razer.com/us/en/help?section=0',
    },
    details: [
      { title: 'PIN ile cüzdan bakiyesi farkı', text: 'Razer Gold PIN, kullanılmadan önce tek kullanımlı bir koddur. Doğru bölgedeki Razer Gold hesabında etkinleştirildiğinde cüzdan bakiyesine dönüşür. TL ve USD PIN’ler aynı ürün değildir; para birimi ve cüzdan bölgesi birlikte eşleşmelidir.' },
      { title: 'Kullanım ve bozum iki ayrı akıştır', text: 'Kodu oyun veya dijital içerik için kullanacaksanız resmî Razer Gold yükleme alanında etkinleştirin. Kodu bozum için iletecekseniz önce yazılı uygunluk ve oran alın; PIN’i kendi cüzdanınıza yüklemeyin. Kullanılmış bakiye, kullanılmamış PIN gibi incelenemez.' },
      { title: 'PIN güvenliği ve hata kontrolü', text: 'Seri numarası ile PIN aynı bilgi değildir. Tam PIN’i yalnız işlem için gerekli güvenli adımda kullanın; ekran görüntüsünü ve kodu herkese açık paylaşmayın. Bölge, kullanım durumu veya PIN hatasında satın alma belgesiyle resmî yardım kanalına başvurun.' },
    ],
    packs: ['50 TL', '100 TL', '250 TL', '500 TL', '1.000 TL', '1.500 TL', '5 USD', '10 USD', '20 USD', '50 USD', '100 USD', '200 USD'].map((label) => ({ id: label.toLowerCase().replace(/\s/g, '-'), label, description: `Razer Gold ${label} PIN` })),
    howTo: [
      { title: 'TL / USD ve bölgeyi doğrulayın', text: 'PIN’in para birimi ile Razer Gold cüzdan bölgesinin eşleştiğini kontrol edin.' },
      { title: 'PIN’i seri numarasından ayırın', text: 'Razer’ın yardım bilgisinde yükleme için tam PIN’in girilmesi gerektiği belirtilir; seri numarası PIN yerine geçmez.' },
      { title: 'Bozum öncesi kodu yüklemeyin', text: 'Cüzdana yüklenen tutar artık kullanılmamış PIN olarak değerlendirilemez.' },
      { title: 'Hata durumunu kaydedin', text: 'Bölge, kullanılan yöntem, hata ekranı ve satın alma kanıtını saklayın; PIN’i herkese açık paylaşmayın.' },
      { title: 'Oranı yazılı teyit edin', text: 'Güncel uygunluk ve oran netleşmeden tam PIN’i göndermeyin.' },
    ],
    faq: [
      { question: 'Razer Gold PIN nasıl yüklenir?', answer: 'Razer Gold hesabında Reload Now alanını açıp Razer Gold PIN yöntemini seçin, tam PIN’i girin ve istenirse iki aşamalı doğrulamayı tamamlayın.' },
      { question: 'TL ve USD Razer Gold arasındaki fark nedir?', answer: 'Para birimi ve cüzdan bölgesi farklıdır. Razer, PIN’in satın alındığı bölgeyle aynı cüzdanda kullanılmasını ve bölgeye uygun para birimi seçilmesini önerir.' },
      { question: 'Razer Gold PIN neden çalışmıyor?', answer: 'Tam PIN yerine seri numarası girilmiş, kod daha önce kullanılmış veya PIN ile cüzdan bölgesi eşleşmiyor olabilir. Bu üç kontrolü yapın.' },
      { question: 'Razer Gold cüzdan bölgesi sonradan değişir mi?', answer: 'Razer yardım bilgisinde cüzdan bölgesinin değiştirilemediği ve yanlış bölge seçildiyse doğru bölgede yeni cüzdan oluşturulması gerektiği belirtilir.' },
      { question: 'Razer Gold bakiyesi veya PIN’in süresi var mı?', answer: 'Razer Gold bakiyesinin süresi dolmaz; PIN’in geçerlilik süresi ise satın alma kanalının koşuluna göre ayrıca kontrol edilmelidir. Promosyon bonusları farklı süreye sahip olabilir.' },
      { question: 'Razer Gold PIN bozum için hesaba yüklenmeli mi?', answer: 'Hayır. Hesaba yüklenen bakiye PIN olmaktan çıkar; işlem öncesi kodu kullanmadan, bölge ve oranı yazılı teyit edin.' },
      { question: 'Razer Gold ürünleri stokta mı?', answer: stockNotice },
    ],
    related: ['steam-cuzdan-kodu', 'itunes-apple-gift-card', 'valorant-vp'],
  },
  {
    slug: 'steam-cuzdan-kodu',
    name: 'Steam Cüzdan Kodu',
    shortName: 'Steam Cüzdan Kodu',
    category: 'Dijital kod',
    eyebrow: 'Steam Wallet',
    description: 'Cüzdan kodlarını bölge ve para birimine göre inceleyin.',
    intro: 'Steam cüzdan kodları tek kullanımlıdır ve hesap mağaza bölgesiyle para birimi uyumu önemlidir. Kodu satın almadan önce hesabınızın bölgesini ve ürünün para birimini kontrol edin.',
    tone: 'steam',
    coverImage: '/products/steam-wallet-centered-v2.webp',
    brandLogo: '/brands/steam/steam.svg',
    brandIntegrated: true,
    coverPosition: '50% 50%',
    coverLabel: 'STEAM',
    coverNote: 'CÜZDAN KODU',
    guide: {
      title: 'Steam Cüzdan Kodu rehberi',
      text: 'Steam cüzdan kodu, kodun para birimi ve hesap mağaza bölgesi uyumluysa Steam cüzdanına bakiye ekler. Kod tek kullanımlıdır; etkinleştirmeden önce doğru Steam hesabında olduğunuzu kontrol edin. Tam kodu mesaj, forum veya ekran görüntüsünde paylaşmayın. Bölge ya da para birimi hatasında kodu tekrar tekrar denemek yerine satın alma kaydıyla Steam desteğine başvurun.',
      sourceLabel: 'Steam resmî hediye kartı sayfasını aç',
      sourceUrl: 'https://store.steampowered.com/digitalgiftcards/',
    },
    details: [
      { title: 'Cüzdan kodu ve dijital hediye farkı', text: 'Steam Cüzdan Kodu, uyumlu hesapta etkinleştirilen ön ödemeli bir koddur. Steam Dijital Hediye Kartı ise Steam üzerinden başka bir kullanıcıya gönderilen ayrı bir teslim yöntemidir. İki ürünün gönderim, bölge ve ödeme koşulları aynı değildir.' },
      { title: 'Mağaza bölgesi ve para birimi', text: 'Steam mağaza ülkesi, hesabın kullandığı para birimini ve bazı kodların uyumluluğunu etkiler. USD kod dahil her ürünün hesap bölgenizde geçerli olduğunu satın almadan önce doğrulayın; yalnız döviz karşılığına bakarak seçim yapmayın.' },
      { title: 'Etkinleştirme ve hata durumları', text: 'Kod doğru Steam hesabında tek kez kullanılmalıdır. Kodu girmeden önce hesap adını kontrol edin. Kullanılmış, geçersiz veya bölge uyumsuzluğu hatasında tam kodu paylaşmadan satın alma belgesi ve hata görüntüsüyle Steam desteğine başvurun.' },
    ],
    packs: ['5 USD', '10 USD', '20 USD', '50 USD', '100 USD'].map((label) => ({ id: label.toLowerCase().replace(/\s/g, '-'), label, description: `Steam Cüzdan Kodu ${label}` })),
    howTo: [
      { title: 'Mağaza bölgesini kontrol edin', text: 'Steam hesabınızın mağaza ülkesi ile kodun bölge ve para birimini karşılaştırın.' },
      { title: 'Doğru hesaba giriş yapın', text: 'Kodu etkinleştirmeden önce hesap adını ve cüzdan para birimini kontrol edin.' },
      { title: 'Kodu tek kez uygulayın', text: 'Steam cüzdan kodu tek kullanımlıdır; sonucu görmeden tekrar denemeyin.' },
      { title: 'Bakiyeyi doğrulayın', text: 'Etkinleştirme sonrası cüzdan bakiyesini ve hesap işlem geçmişini kontrol edin.' },
      { title: 'Kodu gizli tutun', text: 'Tam kodu, hesap şifresini veya doğrulama bilgisini kimseyle paylaşmayın.' },
    ],
    faq: [
      { question: 'Steam Cüzdan Kodu nedir?', answer: 'Steam hesabının cüzdanına desteklenen para biriminde bakiye ekleyen tek kullanımlık dijital koddur.' },
      { question: 'Steam kodu her ülkede çalışır mı?', answer: 'Hayır. Bölge ve para birimi kısıtları bulunabilir; ürün ile hesabın mağaza ülkesini eşleştirin.' },
      { question: 'Kod hangi hesaba yüklenir?', answer: 'Kod, etkinleştirme sırasında giriş yapılmış Steam hesabının cüzdanına uygulanır.' },
      { question: 'Kod kullanılmış görünürse ne yapmalıyım?', answer: 'Tam kodu herkese açık paylaşmadan satın alma belgesi ve hata ekranıyla Steam desteğine başvurun.' },
      { question: 'Steam kodu nakde çevrilir mi?', answer: 'Steam cüzdan bakiyesi platform içi kullanım içindir; nakit para değildir ve Steam kurallarına tabidir.' },
      { question: 'Hesap şifresi gerekir mi?', answer: 'Hayır. Kod satın alımı veya incelemesi için hesap şifresi ve doğrulama kodu paylaşmayın.' },
      { question: 'Steam ürünleri stokta mı?', answer: stockNotice },
    ],
    related: ['itunes-apple-gift-card', 'razer-gold', 'valorant-vp'],
  },
  {
    slug: 'itunes-apple-gift-card',
    name: 'iTunes / Apple Gift Card',
    shortName: 'iTunes / Apple Gift Card',
    category: 'Dijital kod',
    eyebrow: 'Apple Gift Card',
    description: 'Gift Card seçeneklerini hesap bölgenizle eşleştirin.',
    intro: 'Apple Gift Card kodları ülke veya bölgeye bağlıdır. Kodun para birimi ile Apple Hesabı ülkesinin uyumlu olduğundan emin olmadan etkinleştirme yapmayın.',
    tone: 'apple',
    coverImage: '/products/apple-gift-card-centered-v2.webp',
    brandLogo: '/brands/apple/apple.svg',
    brandIntegrated: true,
    coverPosition: '50% 50%',
    coverLabel: 'APPLE',
    coverNote: 'GIFT CARD · iTUNES',
    guide: {
      title: 'Apple Gift Card rehberi',
      text: 'Apple Gift Card ve eski iTunes/App Store kartları, kartın sunulduğu ülke veya bölgeyle uyumlu Apple Hesabında kullanılmalıdır. Kod tek kullanımlıdır. Kodun arkasındaki bilgiyi veya dijital kodu etkinleştirmeden önce hesap ülkesini kontrol edin; kart başka bir bölgede kullanılamıyorsa ülke değişikliği de mevcut abonelik ve bakiyeler nedeniyle kısıtlanabilir.',
      sourceLabel: 'Apple resmî kod kullanma rehberini aç',
      sourceUrl: 'https://support.apple.com/tr-tr/118242',
    },
    details: [
      { title: 'Apple Gift Card neye dönüşür?', text: 'Uyumlu bir Apple Hesabında kullanılan hediye kartı, kart türü ve ülkeye bağlı olarak Apple Hesabı bakiyesine eklenir. Bu bakiye desteklenen uygulama, oyun, abonelik veya Apple hizmetlerinde kullanılabilir; nakit para ve banka bakiyesi değildir.' },
      { title: 'Ülke ve bölge neden kritiktir?', text: 'Apple hediye kartları satın alındıkları ülke veya bölgeyle sınırlıdır. Kartın para birimi ile Apple Hesabının mağaza ülkesi eşleşmelidir. Mevcut bakiye ve abonelikler hesap ülkesini değiştirmeyi kısıtlayabileceği için kodu etkinleştirmeden önce bölgeyi kontrol edin.' },
      { title: 'Dolandırıcılık ve kod güvenliği', text: 'Apple Gift Card; vergi, borç, kargo, banka işlemi veya tanımadığınız bir kişiye ödeme yöntemi değildir. Böyle bir talep dolandırıcılık işareti olabilir. Tam kodu ve kart görüntüsünü paylaşmayın; Apple Hesabı şifresi ile doğrulama kodunu kimseye vermeyin.' },
    ],
    packs: ['25 TL', '50 TL', '100 TL', '250 TL', '500 TL', '1.000 TL'].map((label) => ({ id: label.toLowerCase().replace(/\s|\./g, '-'), label, description: `Apple Gift Card ${label}` })),
    howTo: [
      { title: 'Apple Hesabı ülkesini kontrol edin', text: 'Kartın ülkesi ve para birimi Apple Hesabınızın mağaza bölgesiyle aynı olmalıdır.' },
      { title: 'Kart türünü okuyun', text: 'Apple Gift Card ile eski App Store & iTunes kartlarının kullanım alanı bölgeye göre değişebilir.' },
      { title: 'Doğru hesapta etkinleştirin', text: 'Kodu kullanmadan önce App Store’da açık olan Apple Hesabını doğrulayın.' },
      { title: 'Bakiyeyi kontrol edin', text: 'Etkinleştirme sonrası Apple Hesabı bakiyesini ve satın alma geçmişini inceleyin.' },
      { title: 'Kodu paylaşmayın', text: 'Tam kodu, Apple Hesabı şifresini veya iki faktörlü doğrulama bilgisini kimseye göndermeyin.' },
    ],
    faq: [
      { question: 'Apple Gift Card ne için kullanılır?', answer: 'Kartın türü ve bölgesine göre App Store, abonelikler ve desteklenen Apple ürün veya hizmetlerinde Apple Hesabı bakiyesi olarak kullanılabilir.' },
      { question: 'Türkiye kartı başka ülkedeki hesapta çalışır mı?', answer: 'Genellikle hayır. Apple hediye kartları satın alındıkları ülke veya bölgeyle sınırlıdır.' },
      { question: 'iTunes kartı ile Apple Gift Card aynı mı?', answer: 'Yeni Apple Gift Card bazı bölgelerde daha geniş kullanım sunar; eski App Store & iTunes kartlarının kapsamı farklı olabilir.' },
      { question: 'Kod okunmuyor veya geçersizse ne yapmalıyım?', answer: 'Kodu herkese açık paylaşmadan kartın görüntüsü, satın alma belgesi ve hata mesajıyla Apple desteğine başvurun.' },
      { question: 'Kodu kullandıktan sonra başka hesaba aktarabilir miyim?', answer: 'Apple Hesabı bakiyesi başka hesaba doğrudan aktarılamaz; etkinleştirmeden önce doğru hesapta olduğunuzu kontrol edin.' },
      { question: 'Apple hesabı şifresi gerekir mi?', answer: 'Satıcıya veya destek adı kullanan kişilere şifre ve doğrulama kodu vermeyin.' },
      { question: 'Apple Gift Card ürünleri stokta mı?', answer: stockNotice },
    ],
    related: ['steam-cuzdan-kodu', 'razer-gold', 'mobile-legends-diamond'],
  },
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
