export const v21ExtendedArticlesPart5 = [
  {
    slug: 'paycell-limit-bakiye-farki',
    title: 'Paycell Limit ve Bakiye Farkı Nedir? Kullanılabilir Tutar Rehberi',
    seoTitle: 'Paycell Limit ve Bakiye Farkı Nedir?',
    metaDescription: 'Paycell kart bakiyesi, uygulama bakiyesi ve Turkcell mobil ödeme limiti arasındaki farkı; kullanılabilir tutarı nasıl kontrol edeceğinizi öğrenin.',
    excerpt: 'Paycell kart bakiyesi, uygulama bakiyesi ve Turkcell mobil ödeme limitinin neden aynı olmadığını netleştirin.',
    category: 'Paycell',
    serviceSlug: 'paycell',
    readTime: '7 dk',
    updatedAt: '2026-08-08',
    cover: '/article-covers-v32-5/paycell-nedir-nasil-kullanilir.svg',
    coverAlt: 'Paycell kart bakiyesi, mobil ödeme limiti ve kullanılabilir tutar ayrımını gösteren rehber görseli',
    keywords: ['paycell limit', 'paycell bakiye', 'paycell kullanılabilir bakiye', 'paycell mobil ödeme limiti'],
    links: [
      { label: 'Paycell konu merkezi', href: '/bilgi-merkezi/konu/paycell' },
      { label: 'Paycell hizmeti', href: '/hizmetler/paycell' },
      { label: 'Mobil ödeme nasıl açılır?', href: '/bilgi-merkezi/mobil-odeme-nasil-acilir' },
    ],
    sections: [
      { title: 'Paycell bakiyesi ile mobil ödeme limiti aynı mı?', paragraphs: ['Hayır. Paycell kart veya uygulama bakiyesi ile Turkcell hattına tanımlanan mobil ödeme limiti farklı ödeme kaynaklarıdır. Birinde görünen tutar diğerinde kullanılabilir bakiye bulunduğu anlamına gelmez.', 'Ödeme ekranında seçilen kaynak kontrol edilmelidir. İşlemin karta, uygulama bakiyesine veya telefon faturasına yansıyacağı varsayımla değil ekrandaki güncel bilgiyle doğrulanmalıdır.'] },
      { title: 'Kullanılabilir tutar nereden kontrol edilir?', paragraphs: ['Kart ve uygulama bakiyesi Paycell’in resmî uygulamasındaki ilgili hesap veya kart alanından; hat mobil ödeme limiti ise Turkcell’in resmî kanallarından kontrol edilmelidir. Menü adları ve koşullar değişebileceği için eski kısa kodlar yerine güncel resmî ekran esas alınmalıdır.'], bullets: ['Ödeme kaynağının adını kontrol edin.', 'Kullanılabilir tutar ile toplam işlem tutarını karşılaştırın.', 'Bekleyen veya provizyondaki işlemleri ayrıca inceleyin.'] },
      { title: 'Bakiye var fakat ödeme neden reddedilir?', paragraphs: ['İnternet alışverişi ayarı, kart durumu, ürün kategorisi, satıcı limiti, güvenlik kontrolü veya bekleyen işlem nedeniyle ödeme reddedilebilir. Yeterli bakiye tek başına işlemin onaylanacağını garanti etmez.', 'Art arda tekrar denemek yerine hata mesajını kaydedin, kullanılan ödeme kaynağını doğrulayın ve resmî destekten kısıt nedenini sorun.'] },
      { title: 'Bozum öncesinde hangi tutar esas alınmalı?', paragraphs: ['İşlem planlanırken yalnız uygulamada görünen toplam rakama değil, satın alma ekranında gerçekten kullanılabilen kaynağa bakılmalıdır. Dijital ürün satın almadan önce ürün türü, tutar ve güncel uygunluk yazılı olarak teyit edilmelidir.', 'Şifre, kart güvenlik bilgisi veya SMS doğrulama kodu destek görüşmesinde paylaşılmamalıdır.'] },
    ],
    faq: [
      { question: 'Paycell bakiyem varsa mobil ödeme limitim de var mı?', answer: 'Hayır. Bunlar farklı ödeme kaynaklarıdır ve ayrı ekranlardan kontrol edilmelidir.' },
      { question: 'Paycell kart bakiyesi telefon faturama yansır mı?', answer: 'Her işlem faturaya yansımaz. Ödeme ekranında hangi kaynağın seçildiğini kontrol edin.' },
      { question: 'Bakiye görünüyor fakat kullanılamıyorsa ne yapmalıyım?', answer: 'Kart ayarını, bekleyen işlemleri ve hata mesajını kontrol edin; kesin neden için Paycell’in resmî desteğine başvurun.' },
    ],
  },
  {
    slug: 'pokus-limit-bakiye-farki',
    title: 'Pokus Limit ve Bakiye Farkı Nedir? Kart ve Mobil Ödeme Ayrımı',
    seoTitle: 'Pokus Limit ve Bakiye Farkı Nedir?',
    metaDescription: 'Pokus kart bakiyesi ile Türk Telekom mobil ödeme limitinin farkını, kullanılabilir tutarı ve ödeme reddi kontrollerini öğrenin.',
    excerpt: 'Pokus kart bakiyesi ile Türk Telekom mobil ödeme limitini birbirinden ayırın ve doğru ödeme kaynağını kontrol edin.',
    category: 'Pokus',
    serviceSlug: 'pokus',
    readTime: '7 dk',
    updatedAt: '2026-08-08',
    cover: '/article-covers-v32-5/pokus-nedir-razer-gold-nasil-alinir.svg',
    coverAlt: 'Pokus kart bakiyesi ile Türk Telekom mobil ödeme limiti ayrımını gösteren rehber görseli',
    keywords: ['pokus limit', 'pokus bakiye', 'pokus kart bakiyesi', 'türk telekom mobil ödeme limiti'],
    links: [
      { label: 'Pokus konu merkezi', href: '/bilgi-merkezi/konu/pokus' },
      { label: 'Pokus hizmeti', href: '/hizmetler/pokus' },
      { label: 'Türk Telekom mobil ödeme rehberi', href: '/bilgi-merkezi/turk-telekom-mobil-odeme-rehberi' },
    ],
    sections: [
      { title: 'Pokus bakiyesi ile hat limiti aynı mı?', paragraphs: ['Hayır. Pokus kart veya cüzdan bakiyesi ile Türk Telekom hattına tanımlanan mobil ödeme limiti farklı kaynaklardır. Bir kaynaktaki tutar diğerine otomatik olarak aktarılmış kabul edilmemelidir.', 'Satın alma ekranında kart, cüzdan veya mobil ödeme seçeneklerinden hangisinin kullanıldığı açıkça kontrol edilmelidir.'] },
      { title: 'Pokus kullanılabilir bakiye nasıl kontrol edilir?', paragraphs: ['Kart ve cüzdan tutarı Pokus’un resmî uygulamasındaki güncel hesap ekranından kontrol edilmelidir. Türk Telekom mobil ödeme limiti için operatörün resmî uygulaması veya destek kanalları kullanılmalıdır.'], bullets: ['Hesap doğrulama durumunu inceleyin.', 'Kartın internet alışverişi ayarını kontrol edin.', 'Toplam tutar ve varsa hizmet bedelini birlikte değerlendirin.'] },
      { title: 'Limit var fakat işlem neden gerçekleşmez?', paragraphs: ['Satıcının kartı kabul etmemesi, ürün kategorisi kısıtı, günlük işlem sınırı, güvenlik kontrolü veya yetersiz kullanılabilir bakiye işlemi engelleyebilir. Ekrandaki hata metni sorunun hangi aşamada olduğunu anlamak için saklanmalıdır.', 'Aynı işlemi kısa sürede tekrar tekrar denemek yerine resmî uygulamadaki hareketleri ve kart durumunu kontrol edin.'] },
      { title: 'Dijital ürün almadan önce son kontrol', paragraphs: ['Bozum amacıyla dijital kod alınacaksa ürünün markası, tutarı, para birimi ve bölgesi satın alma öncesinde teyit edilmelidir. Kod kişisel hesaba yüklenmemeli ve uygunluk alınmadan üçüncü kişilerle paylaşılmamalıdır.'] },
    ],
    faq: [
      { question: 'Pokus bakiyesi mobil ödeme limiti midir?', answer: 'Hayır. Pokus bakiyesi ve Türk Telekom mobil ödeme limiti ayrı kaynaklardır.' },
      { question: 'Pokus kartım neden ödeme yapmıyor?', answer: 'Kart ayarı, bakiye, satıcı kabulü, işlem sınırı veya güvenlik kontrolü etkili olabilir. Hata mesajını saklayarak resmî desteğe başvurun.' },
      { question: 'Pokus ile alınan her dijital kod değerlendirilebilir mi?', answer: 'Hayır. Ürün, bölge ve tutar uygunluğu satın alma öncesinde ayrıca teyit edilmelidir.' },
    ],
  },
  {
    slug: 'mobil-odeme-limiti-var-islem-reddediliyor',
    title: 'Mobil Ödeme Limitim Var Ama İşlem Reddediliyor: Nedenleri ve Kontroller',
    seoTitle: 'Mobil Ödeme Limiti Var Ama İşlem Neden Reddedilir?',
    metaDescription: 'Mobil ödeme limitiniz görünmesine rağmen işlem reddediliyorsa hat durumu, ürün kategorisi, satıcı limiti ve güvenlik kontrollerini inceleyin.',
    excerpt: 'Limit görünmesine rağmen başarısız olan mobil ödeme işlemlerinde hangi kontrollerin sırayla yapılacağını öğrenin.',
    category: 'Mobil Ödeme',
    serviceSlug: 'sms-mobil-odeme',
    readTime: '8 dk',
    updatedAt: '2026-08-08',
    cover: '/images/bilgi-merkezi/mobil-odeme/category/mobil-odeme-category-hero.webp',
    coverAlt: 'Mobil ödeme limiti bulunmasına rağmen reddedilen işlem için kontrol adımlarını gösteren görsel',
    keywords: ['mobil ödeme reddedildi', 'mobil ödeme limit var kullanamıyorum', 'mobil ödeme başarısız', 'mobil ödeme hata'],
    links: [
      { label: 'Mobil ödeme konu merkezi', href: '/bilgi-merkezi/konu/sms-mobil-odeme' },
      { label: 'Sorun çözme merkezi', href: '/bilgi-merkezi/sorun-cozme' },
      { label: 'Güven Merkezi', href: '/guven-merkezi' },
    ],
    sections: [
      { title: 'Limit görünürken işlem neden reddedilir?', paragraphs: ['Kullanılabilir limit, işlemin tamamlanması için gereken koşullardan yalnızca biridir. Hat durumu, ürün kategorisi, satıcı sınırı, günlük adet, güvenlik değerlendirmesi ve doğrulama sonucu da işlemi etkileyebilir.', 'Uygulamada görünen üst limit ile o anda belirli bir mağazada kullanılabilecek tutar aynı olmayabilir.'] },
      { title: 'İlk yapılması gereken kontroller', paragraphs: ['Mobil ödemenin açık olduğunu, gecikmiş borç veya yeni SIM kısıtı bulunmadığını ve onay ekranındaki hizmet adının doğru olduğunu kontrol edin. Ardından ürünün mobil ödeme kabul edip etmediğini ve toplam tutarın hizmet bedeliyle birlikte limiti aşmadığını doğrulayın.'], bullets: ['Hat ve mobil ödeme durumu', 'Kullanılabilir güncel limit', 'Ürün ve satıcı uygunluğu', 'Toplam tutar ve hizmet bedeli', 'Onay SMS’indeki firma bilgisi'] },
      { title: 'Tekrar denemek doğru mu?', paragraphs: ['Aynı işlemi arka arkaya denemek geçici güvenlik kontrolünü tetikleyebilir veya birden fazla bekleyen kayıt oluşturabilir. Önce hata mesajını ve operatör uygulamasındaki hareketleri kontrol edin.', 'Başarısız görünen işlemin faturaya veya bakiyeye yansıyıp yansımadığını doğrulamadan yeni işlem başlatmayın.'] },
      { title: 'Ne zaman resmî destek kullanılmalı?', paragraphs: ['Hata devam ediyorsa operatörün resmî desteğine tarih, tutar, satıcı adı ve hata mesajıyla başvurun. Şifre, SMS kodu veya ekran erişimi paylaşmayın.', 'Bozum amacıyla ürün satın alıyorsanız yeni denemeden önce kabul edilen ürün ve tutar için güncel uygunluk alın.'] },
    ],
    faq: [
      { question: 'Limitim yeterli olduğu hâlde neden ödeme olmuyor?', answer: 'Satıcı, ürün kategorisi, güvenlik kontrolü veya toplam hizmet bedeli işlemi engelleyebilir.' },
      { question: 'Başarısız işlem faturaya yansır mı?', answer: 'Bazı işlemler bekleyen kayıt oluşturabilir. Operatör uygulamasındaki hareketi kontrol etmeden tekrar denemeyin.' },
      { question: 'SMS kodunu destek ekibine göndermeli miyim?', answer: 'Hayır. Tek kullanımlık doğrulama kodu üçüncü kişilerle paylaşılmamalıdır.' },
    ],
  },
  {
    slug: 'razer-gold-kodu-calismiyor',
    title: 'Razer Gold Kodu Çalışmıyor: Bölge, Kullanım ve Kod Hatası Çözümü',
    seoTitle: 'Razer Gold Kodu Çalışmıyor: Hata Çözüm Rehberi',
    metaDescription: 'Razer Gold kodu çalışmıyorsa bölge, para birimi, karakter hatası, kullanım durumu ve satıcı teslimatını nasıl kontrol edeceğinizi öğrenin.',
    excerpt: 'Razer Gold kodu hata verdiğinde tekrar denemeden önce bölge, karakter ve kullanım durumunu sistemli biçimde kontrol edin.',
    category: 'Razer Gold',
    serviceSlug: 'razer-gold-tl',
    readTime: '8 dk',
    updatedAt: '2026-08-08',
    cover: '/blog-covers/razer-gold-strateji.webp',
    coverAlt: 'Razer Gold kod hatası, bölge ve karakter kontrolünü temsil eden rehber görseli',
    keywords: ['razer gold kodu çalışmıyor', 'razer gold kod hatası', 'razer gold invalid pin', 'razer gold bölge hatası'],
    links: [
      { label: 'Razer Gold konu merkezi', href: '/bilgi-merkezi/konu/razer-gold-tl' },
      { label: 'Razer Gold nedir?', href: '/bilgi-merkezi/razer-gold-nedir' },
      { label: 'Dijital kod güvenliği', href: '/bilgi-merkezi/dijital-kod-hediye-karti-rehberi' },
    ],
    sections: [
      { title: 'Razer Gold kodu neden çalışmaz?', paragraphs: ['En yaygın nedenler yanlış karakter girişi, kodun farklı bölge veya para birimine ait olması, daha önce kullanılmış olması, aktivasyonun tamamlanmaması ya da satıcı teslimat hatasıdır.', 'Hata mesajının tam metni kaydedilmeden yapılan tekrar denemeleri sorunun kaynağını bulmayı zorlaştırabilir.'] },
      { title: 'Kod ve bölge nasıl kontrol edilir?', paragraphs: ['Sipariş sayfasındaki ürün adı, para birimi ve ülke bilgisini hesabınızın bölgesiyle karşılaştırın. Benzer görünen 0/O, 1/I ve 5/S gibi karakterleri teslim edilen orijinal metinden kontrol edin.'], bullets: ['Kodun tamamını ve karakter sayısını kontrol edin.', 'TL veya USD bilgisini doğrulayın.', 'Hesap ve ürün bölgesini karşılaştırın.', 'Sipariş ve teslimat kaydını saklayın.'] },
      { title: 'Kod kullanılmış görünüyorsa ne yapılmalı?', paragraphs: ['Kodu farklı hesaplarda tekrar tekrar denemeyin. Satıcıya sipariş numarası, teslim zamanı ve hata ekranıyla başvurun; kodun aktivasyon ve kullanım kaydının incelenmesini isteyin.', 'Kodun tamamını herkese açık alanda veya tanımadığınız destek hesaplarında paylaşmayın.'] },
      { title: 'Bozum için alınan kodda hata varsa', paragraphs: ['Kod satın alma sonrasında hata veriyorsa yeni kod almadan önce mevcut siparişin çözülmesini bekleyin. Uygunluk ve oran onayı, hatalı veya bölge uyumsuz bir kodu geçerli hâle getirmez.', 'İşlem desteğinde hesap şifresi, ekran paylaşımı veya uzaktan erişim talep edilmemelidir.'] },
    ],
    faq: [
      { question: 'Invalid PIN hatası ne anlama gelir?', answer: 'Kod karakteri, bölge, aktivasyon veya kullanım durumu uyuşmazlığı olabilir. Tam hata metniyle satıcı desteğine başvurun.' },
      { question: 'Razer Gold kodunu kaç kez deneyebilirim?', answer: 'Tekrar sınırları değişebilir. Art arda denemek yerine kod ve bölge bilgisini kontrol edin.' },
      { question: 'Hatalı kodu bozdurabilir miyim?', answer: 'Doğrulanamayan veya kullanılmış görünen kod işlem için uygun kabul edilmez; önce satıcıyla teslimat sorunu çözülmelidir.' },
    ],
  },
  {
    slug: 'kredi-karti-sanal-kart-islem-reddedildi',
    title: 'Kredi Kartı veya Sanal Kart İşlemi Reddedildi: Güvenli Kontrol Rehberi',
    seoTitle: 'Kart İşlemi Neden Reddedilir? Sanal Kart Hata Rehberi',
    metaDescription: 'Kredi kartı veya sanal kart işlemi reddedildiğinde limit, internet alışverişi, 3D Secure, banka güvenlik kontrolü ve bekleyen provizyonu güvenle inceleyin.',
    excerpt: 'Kart işlemi çalışmıyor veya hata veriyorsa art arda denemeden önce limit, işlem izni, doğrulama ve provizyon durumunu sistemli biçimde kontrol edin.',
    category: 'Kart İşlemleri',
    serviceSlug: 'kredi-karti-sanal-kart',
    readTime: '9 dk',
    updatedAt: '2026-08-08',
    cover: '/images/bilgi-merkezi/editorial-covers-v46/kart-islemleri-urun-dogrulama.webp',
    coverAlt: 'Fiziksel ve sanal karttan uygun dijital ürün, kod doğrulama ve onaylı TL ödeme akışını gösteren rehber görseli',
    keywords: ['kart işlemi reddedildi', 'sanal kart çalışmıyor', '3d secure hatası', 'kart işlemleri sık sorulan sorular'],
    links: [
      { label: 'Kart İşlemleri konu merkezi', href: '/bilgi-merkezi/konu/kredi-karti-sanal-kart' },
      { label: 'Dijital kod güvenliği', href: '/bilgi-merkezi/dijital-kod-hediye-karti-rehberi' },
      { label: 'Güven Merkezi', href: '/guven-merkezi' },
    ],
    sections: [
      { title: 'Kart işlemi neden reddedilir?', paragraphs: ['Yeterli limit bulunması işlemin kesin olarak onaylanacağı anlamına gelmez. İnternet alışverişi izni, sanal kart limiti, 3D Secure doğrulaması, satıcı kategorisi, banka güvenlik değerlendirmesi veya geçici teknik kesinti sonucu etkileyebilir.', 'Hata mesajını ve işlem saatini kaydetmek, bankanın doğru kaydı incelemesini kolaylaştırır.'] },
      { title: 'İlk kontrol sırası nasıl olmalı?', paragraphs: ['Önce kartın aktif olduğunu, son kullanma tarihini, kullanılabilir limiti ve internet alışverişi iznini kontrol edin. Sanal kart kullanıyorsanız ana kart limitinden ayrı tanımlanan sanal kart limitinin işlem tutarını karşıladığından emin olun.'], bullets: ['Kullanılabilir kart veya sanal kart limiti', 'İnternet alışverişi izni', 'Kart bilgileri ve son kullanma tarihi', '3D Secure ekranı ve banka bildirimi', 'Satıcı adı ile toplam işlem tutarı'] },
      { title: 'Başarısız işlemde provizyon oluşabilir mi?', paragraphs: ['Bazı reddedilen veya yarıda kalan denemeler geçici provizyon olarak görünebilir. Banka hareketlerini kontrol etmeden aynı ödemeyi tekrar başlatmak birden fazla bekleyen kayıt oluşturabilir.', 'Tutar çekilmiş görünüyor ancak ürün teslim edilmediyse satıcı ve banka kayıtlarını birlikte inceleyin; yeni satın alma yapmadan önce mevcut kaydın sonucunu bekleyin.'] },
      { title: 'Güvenli destek başvurusu', paragraphs: ['Bankaya işlem zamanı, tutarı, satıcı adı ve ekrandaki hata mesajıyla başvurun. Kartın tam numarasını, CVV kodunu, şifreyi veya SMS doğrulama kodunu mesajla paylaşmayın.', 'Bir ürün bozum amacıyla satın alınacaksa karttan ödeme yapmadan önce ürün, bölge ve güncel işlem uygunluğunu yazılı olarak doğrulayın.'] },
    ],
    faq: [
      { question: 'Limitim olduğu hâlde kartım neden reddediliyor?', answer: 'İnternet alışverişi izni, sanal kart alt limiti, güvenlik kontrolü, satıcı kategorisi veya doğrulama sorunu işlemi engelleyebilir.' },
      { question: 'Reddedilen işlemde para çekilmiş görünür mü?', answer: 'Geçici provizyon oluşabilir. Hareketin kesin durumunu bankanızdan doğrulamadan işlemi tekrarlamayın.' },
      { question: '3D Secure kodunu destek görevlisine vermeli miyim?', answer: 'Hayır. Tek kullanımlık doğrulama kodu, kart şifresi ve CVV bilgisi hiç kimseyle paylaşılmamalıdır.' },
    ],
  },
];
