import type { Metadata } from "next";
import Link from "next/link";
import ServiceCard from "../components/services/ServiceCard";
import { services } from "../lib/site";
import { ArrowIcon, ShieldIcon } from "../components/ui/Icons";

export const metadata: Metadata = { title: "Hizmetler", description: "Mobil ödeme, Razer Gold, Paycell, Pokus, Apple, Steam ve sanal kart hizmetlerini inceleyin." };

export default function ServicesPage() {
  const groups = [...new Set(services.map(s=>s.category))];
  return <main className="bg-[#f6f8fc]">
    <section className="relative isolate overflow-hidden bg-slate-950 text-white"><div className="absolute -left-48 -top-48 h-[36rem] w-[36rem] rounded-full bg-blue-600/25 blur-[130px]"/><div className="absolute -bottom-48 -right-32 h-[36rem] w-[36rem] rounded-full bg-cyan-500/15 blur-[130px]"/><div className="relative mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-blue-200"><ShieldIcon className="h-4 w-4"/>Sky Bozum Hizmet Merkezi</span><h1 className="mt-7 max-w-4xl text-4xl font-black leading-[1.06] tracking-[-.045em] sm:text-5xl lg:text-7xl">Dijital bakiyeniz için <span className="block bg-gradient-to-r from-blue-400 to-cyan-300 bg-clip-text text-transparent">doğru işlem çözümü</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">Mobil ödeme, dijital cüzdan, oyun bakiyesi ve sanal kart işlemlerini tek merkezden inceleyin.</p><a href="#tum-hizmetler" className="mt-8 inline-flex min-h-14 items-center justify-center gap-3 rounded-full bg-white px-7 text-sm font-black text-slate-950">Hizmetleri incele <ArrowIcon/></a></div></section>
    <section id="tum-hizmetler" className="scroll-mt-20 py-20 lg:py-28"><div className="mx-auto max-w-7xl space-y-20 px-5 lg:px-8">{groups.map((group,index)=><div key={group}><div className="mb-8 border-b border-slate-200 pb-7"><div className="flex items-center gap-3"><span className="flex h-8 min-w-8 items-center justify-center rounded-full bg-slate-950 px-2 text-xs font-black text-white">{String(index+1).padStart(2,'0')}</span><span className="text-xs font-black uppercase tracking-[.2em] text-blue-700">{group}</span></div><h2 className="mt-4 text-3xl font-black tracking-[-.035em] text-slate-950 sm:text-4xl">{group === 'Dijital Kodlar' ? 'Oyun ve dijital bakiye işlemleri' : group === 'Mobil Ödeme' ? 'Operatör ve dijital cüzdan çözümleri' : 'Kredi kartı ve sanal kart işlemleri'}</h2></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{services.filter(s=>s.category===group).map(service=><ServiceCard key={service.slug} service={service}/>)}</div></div>)}</div></section>
    <section className="px-5 pb-24 lg:px-8"><div className="mx-auto max-w-7xl rounded-[34px] bg-slate-950 px-7 py-12 text-white shadow-2xl sm:px-12 lg:flex lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-300">Karar veremediniz mi?</p><h2 className="mt-3 text-3xl font-black">Size uygun işlem yöntemini birlikte belirleyelim.</h2></div><Link href="/iletisim" className="mt-7 inline-flex min-h-14 items-center justify-center gap-3 rounded-full bg-white px-7 text-sm font-black text-slate-950 lg:mt-0">Destek alın <ArrowIcon/></Link></div></section>
  </main>;
}
