import type { Metadata } from 'next';
import PrivacyControls from '../components/personalization/PrivacyControls';

export const metadata: Metadata = { title: 'Gizlilik Politikası', description: 'Sky Bozum gizlilik, veri kullanımı ve güvenlik bilgilendirmesi.', alternates: { canonical: '/gizlilik-politikasi' } };
const sections = [
  ['Toplanan bilgiler', 'İletişim sırasında paylaştığınız ad, iletişim bilgisi, hizmet türü ve işlemle ilgili gerekli kayıtlar talebinizi değerlendirmek amacıyla işlenebilir.'],
  ['Kullanım amacı', 'Bilgiler yalnızca iletişimi yürütmek, işlem uygunluğunu kontrol etmek, güvenliği sağlamak ve yasal yükümlülükleri yerine getirmek amacıyla kullanılır.'],
  ['Hassas bilgiler', 'Şifre, tek kullanımlık doğrulama kodu veya gereksiz kart bilgisi talep edilmez. Dijital kodları herkese açık alanlarda paylaşmayın.'],
  ['Saklama ve güvenlik', 'Kayıtlar hizmet ve yasal gereklilik için gerekli süre boyunca korunur. Gereksiz kişisel verilerin paylaşılmaması esastır.'],
  ['Anonim kişiselleştirme', 'Onay vermeniz halinde rastgele oluşturulan anonim ziyaretçi ID’si, ziyaret sayısı ve ilgilendiğiniz hizmetlere ait puanlar yalnızca kullandığınız tarayıcıda saklanır. Bu bilgiler Sky Bozum sunucusuna gönderilmez, gerçek kimliğinizle eşleştirilmez ve en fazla 90 gün sonra kendiliğinden geçersiz olur.'],
  ['Çerez ve tercih yönetimi', 'Kişiselleştirme zorunlu değildir. Kabul veya ret tercihiniz, seçiminizi tekrar tekrar sormamak amacıyla tarayıcınızda tutulur. Tercihinizi değiştirebilir veya anonim profilinizi dilediğiniz zaman sıfırlayabilirsiniz.'],
  ['İletişim', 'Gizlilik talepleriniz için iletişim sayfasındaki e-posta adresini kullanabilirsiniz.'],
];
export default function Page(){return <main className="min-h-screen bg-[#090b10] text-white"><header className="border-b border-white/8 py-14"><div className="content-shell max-w-4xl"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-rose-400">Yasal bilgilendirme</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">Gizlilik Politikası</h1><p className="mt-4 text-sm text-slate-500">Son güncelleme: 18 Temmuz 2026</p></div></header><article className="content-shell max-w-4xl py-12 sm:py-16"><div className="premium-card p-6 sm:p-9"><p className="rounded-xl border border-amber-400/15 bg-amber-500/[0.05] p-4 text-sm leading-7 text-amber-100/75">Bu metin genel bilgilendirme taslağıdır; yayına almadan önce faaliyet modelinize uygun biçimde hukuk uzmanına inceletilmelidir.</p>{sections.map(([title,text],index)=><section key={title} className="mt-8 border-t border-white/8 pt-8"><h2 className="text-xl font-black"><span className="mr-3 text-xs text-rose-400">{String(index+1).padStart(2,'0')}</span>{title}</h2><p className="mt-3 text-sm leading-8 text-slate-300">{text}</p></section>)}<section className="mt-8 border-t border-white/8 pt-8"><h2 className="text-xl font-black">Tercihlerinizi yönetin</h2><p className="mb-4 mt-3 text-sm leading-8 text-slate-300">Kişiselleştirme kararınızı değiştirebilir veya bu tarayıcıdaki anonim profili sıfırlayabilirsiniz.</p><PrivacyControls showReset /></section></div></article></main>}
