import type { Metadata } from 'next';
import PrivacyControls from '../components/personalization/PrivacyControls';
import { siteConfig } from '../lib/site-config';

export const metadata: Metadata = { title: 'Gizlilik Politikası', description: 'Sky Bozum gizlilik, veri kullanımı ve güvenlik bilgilendirmesi.', alternates: { canonical: '/gizlilik-politikasi' } };
const sections = [
  ['Toplanan bilgiler', 'İletişim sırasında paylaştığınız ad, iletişim bilgisi, hizmet türü ve işlemle ilgili gerekli kayıtlar talebinizi değerlendirmek amacıyla işlenebilir.'],
  ['Kullanım amacı', 'Bilgiler yalnızca iletişimi yürütmek, işlem uygunluğunu kontrol etmek, güvenliği sağlamak ve yasal yükümlülükleri yerine getirmek amacıyla kullanılır.'],
  ['Hassas bilgiler', 'Şifre, tek kullanımlık doğrulama kodu veya gereksiz kart bilgisi talep edilmez. Dijital kodları herkese açık alanlarda paylaşmayın.'],
  ['Saklama ve güvenlik', 'Kayıtlar hizmet ve yasal gereklilik için gerekli süre boyunca korunur. Gereksiz kişisel verilerin paylaşılmaması esastır.'],
  ['Anonim kişiselleştirme', 'Onay vermeniz halinde rastgele oluşturulan anonim ziyaretçi ID’si, ziyaret sayısı ve ilgilendiğiniz hizmetlere ait puanlar yalnızca kullandığınız tarayıcıda saklanır. Bu bilgiler Sky Bozum sunucusuna gönderilmez, gerçek kimliğinizle eşleştirilmez ve en fazla 90 gün sonra kendiliğinden geçersiz olur.'],
  ['Çerez ve tercih yönetimi', 'Kişiselleştirme zorunlu değildir. Kabul veya ret tercihiniz, seçiminizi tekrar tekrar sormamak amacıyla tarayıcınızda tutulur. Tercihinizi değiştirebilir veya anonim profilinizi dilediğiniz zaman sıfırlayabilirsiniz.'],
  ['Hizmet sağlayıcıları', 'Kimlik doğrulama ve veri saklama için Firebase, site yayını için Vercel gibi teknik hizmetlerden yararlanılabilir. Bu hizmetlere yalnız işlev için gereken sınırlı veriler aktarılır; şifre ve ödeme kartı bilgileri Sky Bozum tarafından saklanmaz.'],
  ['Haklarınız ve iletişim', `Kayıtlarınıza ilişkin erişim, düzeltme veya silme talebinizi ${siteConfig.email} adresine iletebilirsiniz. Talebin yalnızca ${siteConfig.domain} alanındaki resmî kanallardan geldiğini doğrulayın.`],
];
export default function Page(){return <main className="min-h-screen bg-[#090b10] text-white"><header className="border-b border-white/8 py-14"><div className="content-shell max-w-4xl"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-rose-400">Yasal bilgilendirme</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">Gizlilik Politikası</h1><p className="mt-4 text-sm text-slate-500">Son güncelleme: 13 Ağustos 2026</p></div></header><article className="content-shell max-w-4xl py-12 sm:py-16"><div className="premium-card p-6 sm:p-9"><p className="rounded-xl border border-white/8 bg-white/[.025] p-4 text-sm leading-7 text-slate-300">Bu sayfa, Sky Bozum hizmetleriyle ilgili kişisel veri işleme ve tercih yönetimi hakkında bilgi verir.</p>{sections.map(([title,text],index)=><section key={title} className="mt-8 border-t border-white/8 pt-8"><h2 className="text-xl font-black"><span className="mr-3 text-xs text-rose-400">{String(index+1).padStart(2,'0')}</span>{title}</h2><p className="mt-3 text-sm leading-8 text-slate-300">{text}</p></section>)}<section className="mt-8 border-t border-white/8 pt-8"><h2 className="text-xl font-black">Tercihlerinizi yönetin</h2><p className="mb-4 mt-3 text-sm leading-8 text-slate-300">Kişiselleştirme kararınızı değiştirebilir veya bu tarayıcıdaki anonim profili sıfırlayabilirsiniz.</p><PrivacyControls showReset /></section></div></article></main>}
