import Link from'next/link';import{communityEditorials}from'../lib/communityEditorials';import'./forum-directory.css';
const groups=[
{title:'Sky Bozum',icon:'✦',description:'Topluluk duyuruları, kullanım rehberleri ve güvenli işlem bilgilendirmeleri.',topics:['Duyurular ve forum kuralları','Kampanyalar ve fırsatlar','Kullanıcı deneyimleri']},
{title:'Şikâyet ve Çözüm',icon:'!',description:'Yaşanan sorunu belgeleriyle anlatın, çözüm sürecini takip edin.',topics:['Bozum işlemi şikâyetleri','Operatör ve mobil ödeme sorunları','Dijital kod sorunları','Dolandırıcılık ihbarları','Çözülen şikâyetler']},
{title:'Danış ve Bilgi Al',icon:'?',description:'İşlem öncesinde soru sorun; kullanıcı ve editör yanıtlarını karşılaştırın.',topics:['Mobil ödeme','Gift Card ve oyun kodları','Hat limitleri','Bozum oranları','İşlem öncesi yardım']},
{title:'Teknoloji ve SEO',icon:'⌘',description:'Web sitesi, arama görünürlüğü, sosyal medya ve dijital güvenlik.',topics:['Web sitesi geliştirme','SEO ve arama motorları','Yapay zekâ araçları','Sosyal medya','Tasarım ve içerik','Teknik destek']},
{title:'Online Ticaret',icon:'₺',description:'E-ticaret, ödeme, müşteri güveni ve dijital ürün satışı üzerine bilgi paylaşımı.',topics:['E-ticaret ve pazaryerleri','Dijital ürün satışı','Ödeme yöntemleri','Reklam ve müşteri kazanımı','Güvenli alışveriş','Girişimcilik']},
{title:'Sohbet',icon:'☵',description:'Topluluk üyelerinin gündem, eğlence ve günlük deneyimlerini paylaştığı alan.',topics:['Tanışma alanı','Güncel konular','Oyun ve eğlence','Film, dizi ve müzik','Öneriler','Serbest sohbet']},
{title:'Forum Destek',icon:'⚙',description:'Üyelik, forum kullanımı, öneriler ve içerik bildirimleri.',topics:['Forum kullanım rehberi','Hesap ve üyelik sorunları','Öneri ve geri bildirim','İçerik şikâyetleri']}
];
export default function ForumDirectory(){return <section className="forum-directory"><header><div><span>FORUM BÖLÜMLERİ</span><h2>Doğru alanı seçin, konunuzu kaybolmadan paylaşın.</h2></div><Link href="/hesabim/yeni-konu">+ Yeni konu aç</Link></header><div className="forum-groups">{groups.map(group=>{const guides=communityEditorials.filter(item=>item.category===group.title);return <article key={group.title}><div className="forum-group-icon">{group.icon}</div><div className="forum-group-main"><h3>{group.title}</h3><p>{group.description}</p><div>{group.topics.map(topic=><span key={topic}>{topic}</span>)}</div></div><aside><small>EDİTÖR REHBERİ</small>{guides.length?<><Link href={`/topluluk/rehber/${guides[0].slug}`}>{guides[0].title}</Link><span>{guides.length} doğrulanmış rehber</span></>:<><b>İlk içerikler hazırlanıyor</b><span>Üyeler konu açabilir</span></>}</aside></article>})}</div></section>}
